import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { AdminLoginPageHelper } from '../../../../page-objects/pages/admin-login-page/admin-login.helper';
import { ThreshHoldConfigurationManagerConstant } from '../../../../page-objects/pages/administer-system/analytics/threshhold-configuration-manager/threshhold-configuration-manager.constants';
import { ThreshHoldConfigurationManagerHelper } from '../../../../page-objects/pages/administer-system/analytics/threshhold-configuration-manager/threshhold-configuration-manager.helper';
import { ThreshHoldConfigurationManagerPage } from '../../../../page-objects/pages/administer-system/analytics/threshhold-configuration-manager/threshhold-configuration-manager.po';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: AdminLoginPageHelper;
    const blank = ThreshHoldConfigurationManagerConstant.errorConditionTestData.blank;
    const zero = ThreshHoldConfigurationManagerConstant.errorConditionTestData.zero;
    const doubleDigit = ThreshHoldConfigurationManagerConstant.errorConditionTestData.doubleDigit;
    const decimalValue = ThreshHoldConfigurationManagerConstant.errorConditionTestData.decimalValue;
    const ratingDecimalValue = ThreshHoldConfigurationManagerConstant.errorConditionTestData.ratingDecimalValue;
    const alphabets = ThreshHoldConfigurationManagerConstant.errorConditionTestData.alphabets;
    const specialCharacter = ThreshHoldConfigurationManagerConstant.errorConditionTestData.specialCharacter;
    const textBoxField = ThreshHoldConfigurationManagerPage.textBox;

    beforeAll(async () => {
        loginPageHelper = AdminLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        await loginPageHelper.goTo();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await AdminLoginPageHelper.logout();
    });

    // Jira References - KNOV-95
    it('To verify the error message when alphabets or special characters are provided to Rating: Low Threshold attribute field. - [22375348]', async () => {
        // Auto generated by aurea-automation - util on Wed, 06 Mar 2019 10:36:54 GMT

        StepLogger.caseId = 22375348;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Rating: Low Threshold" attribute.');
        StepLogger.verification('"Rating: Low Threshold" attribute should be displayed.');
        await textBoxField.lowRating.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide any alphabetical value.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lowRating, alphabets);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyRatingErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide specials characters in the field.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lowRating, specialCharacter);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyRatingErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-95
    it(`To verify the error message when the field is left blank or zero is provided to
        Negative Feedback Threshold attribute field. - [22375438]`, async () => {
        // Auto generated by aurea-automation - util on Wed, 06 Mar 2019 10:36:54 GMT

        StepLogger.caseId = 22375438;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Negative Feedback Threshold" attribute.');
        StepLogger.verification('"Negative Feedback Threshold" attribute should be displayed.');
        await textBoxField.feedbacks.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Leave the field blank.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.feedbacks, blank);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide "0" in the field.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.feedbacks, zero);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-95
    it('To verify the error message when the field is left blank or zero is provided to Rating: High Threshold attribute field. - [22375452]', async () => {
        // Auto generated by aurea-automation - util on Wed, 06 Mar 2019 10:36:54 GMT

        StepLogger.caseId = 22375452;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Rating: High Threshold" attribute.');
        StepLogger.verification('"Rating: High Threshold" attribute should be displayed.');
        await textBoxField.highRating.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Leave the field blank.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.highRating, blank);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyRatingErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide "0" in the field.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.highRating, zero);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyRatingErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-95
    it('To verify the error message when the field is left blank or zero is provided to Rating: Low Threshold attribute field. - [22375453]', async () => {
        // Auto generated by aurea-automation - util on Wed, 06 Mar 2019 10:36:54 GMT

        StepLogger.caseId = 22375453;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Rating: Low Threshold" attribute.');
        StepLogger.verification('"Rating: Low Threshold" attribute should be displayed.');
        await textBoxField.lowRating.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Leave the field blank.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lowRating, blank);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyRatingErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide "0" in the field.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lowRating, zero);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyRatingErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-95
    it('To verify the error message when a decimal value is provided to Negative Feedback Threshold attribute field. - [22378039]', async () => {
        // Auto generated by aurea-automation - util on Wed, 06 Mar 2019 10:36:54 GMT

        StepLogger.caseId = 22378039;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Negative Feedback Threshold" attribute.');
        StepLogger.verification('"Negative Feedback Threshold" attribute should be displayed.');
        await textBoxField.feedbacks.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a decimal value between the range 1 to 9999 (For Ex: 14.8)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.feedbacks, decimalValue);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-95
    it(`To verify the error message when the tenth place value is not ranging from 1 to 5 or non-decimal value is provided to
        Rating: High Threshold attribute field. - [22378060]`, async () => {
        // Auto generated by aurea-automation - util on Wed, 06 Mar 2019 10:36:54 GMT

        StepLogger.caseId = 22378060;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Rating: High Threshold" attribute.');
        StepLogger.verification('"Rating: High Threshold" attribute should be displayed.');
        await textBoxField.highRating.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a decimal value in the field in which the tenth place does not belong in the range 1 to 5. (For Ex:6.2)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.highRating, ratingDecimalValue);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyRatingErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide a non-decimal double digit value.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.highRating, doubleDigit);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyRatingErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-95
    it(`To verify the error message when the tenth place value is not ranging from 1 to 5 or non-decimal value is provided to
        Rating: Low Threshold attribute field. - [22378084]`, async () => {
        // Auto generated by aurea-automation - util on Wed, 06 Mar 2019 10:36:54 GMT

        StepLogger.caseId = 22378084;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Rating: Low Threshold" attribute.');
        StepLogger.verification('"Rating: Low Threshold" attribute should be displayed.');
        await textBoxField.lowRating.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a decimal value in the field in which the tenth place does not belong in the range 1 to 5. (For Ex:6.2)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lowRating, ratingDecimalValue);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyRatingErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide a non-decimal double digit value.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lowRating, doubleDigit);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyRatingErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });
});
