import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { CredentialsHelper } from '../../../components/misc-utils/credentials-helper';
import { AdminHomePageHelper } from '../../../page-objects/pages/admin-home-page/admin-home.helper';
import { AdminHomePage } from '../../../page-objects/pages/admin-home-page/admin-home.po';
import { AdminLoginPageHelper } from '../../../page-objects/pages/admin-login-page/admin-login.helper';
import {
    EmailTemplateManagerPageConstant
} from '../../../page-objects/pages/administer-system/email-template-manager-page/email-template-manager.constants';
import {
    EmailTemplateManagerPageHelper
} from '../../../page-objects/pages/administer-system/email-template-manager-page/email-template-manager.helper';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.smokeSuite, () => {
    let loginPageHelper: AdminLoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = AdminLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        await loginPageHelper.goTo();
    });

    beforeEach(async () => {
        await AdminLoginPageHelper.logout(true);
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await AdminLoginPageHelper.loginAsAdmin();
    });

     // Jira References - KNOV-96
    it('To access Email Template Manager screen. - [22383820]', async () => {
        // Auto generated by aurea-automation - util on Tue, 12 Mar 2019 15:51:19 GMT
        StepLogger.caseId = 22383820;

        StepLogger.preCondition('Execute test case C22308069 to login.');
        await AdminHomePageHelper.verifyUserNameAtTheTopRightCorner(CredentialsHelper.admin.username);

        StepLogger.stepId(1);
        StepLogger.step('Click on the options icon (3 lines at the top left corner).');
        await AdminHomePageHelper.clickOnBurgerIcon();
        StepLogger.verification(`The following options should be displayed.
        -Home
        -Manage workbench
        -Manage communities
        -Manage Knowledge
        -Manage People
        -Manage site experience
        -Administer systems
        -Settings
        -Logout`);
        await AdminHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on Administer systems.');
        await AdminHomePageHelper.clickAdministerSystem();
        StepLogger.verification('List of options should be displayed.');
        await AdminHomePageHelper.verifyAdministerSystemSubMenu();

        StepLogger.stepId(3);
        StepLogger.step('Click on Notifications and Subscriptions.');
        await AdminHomePage.administerSystem.nofiticationsAndSubscriptions.hoverOverAndClick();
        StepLogger.verification(`Following options should be displayed.
        -Email Template Manager
        -RSS feed manager`);
        await AdminHomePageHelper.verifyNotificationAndSubscriptionSubMenu();

        StepLogger.stepId(4);
        StepLogger.step('Click on Email Template manager.');
        await AdminHomePage.administerSystem.emailTemplateManager.hoverOverAndClick();
        StepLogger.verification('Email Template manager screen should be displayed with Create template button at the top.');
        await EmailTemplateManagerPageHelper.verifyNavigation();
    });

    // Jira References - KNOV-96
    it('To create a template. - [22383831]', async () => {
        // Auto generated by aurea-automation - util on Tue, 12 Mar 2019 17:16:50 GMT
        const vals = EmailTemplateManagerPageConstant.testData;
        const templateSubject = await PageHelper.getUniqueId();
        StepLogger.caseId = 22383831;

        StepLogger.preCondition('Execute test case C22308069 to login.');
        await AdminHomePageHelper.verifyUserNameAtTheTopRightCorner(CredentialsHelper.admin.username);
        StepLogger.preCondition('Execute test case C22383820 to access Email Template Manager screen.');
        await EmailTemplateManagerPageHelper.navigateToEmailTemplateManager();

        StepLogger.stepId(1);
        StepLogger.step('Click on Create template.');
        StepLogger.verification('Email Template properties window should be displayed.');
        await EmailTemplateManagerPageHelper.clickOnEmailTemplateAndVerify();

        StepLogger.stepId(2);
        StepLogger.step(`Provide Template type.
        Provide Language
        Provide Subject
        Provide body content.`);
        StepLogger.verification('All the values should be displayed.');
        await EmailTemplateManagerPageHelper
            .enterAndverifyTemplatePropertiesFields(templateSubject, vals.language);

        StepLogger.stepId(3);
        StepLogger.step('Click on submit.');
        await EmailTemplateManagerPageHelper.clickOnSubmit();
        StepLogger.verification('The template should be created successfully and should be visible in the template listing.');
        await EmailTemplateManagerPageHelper.verifyTemplateIsVisibleInTemplateListing(templateSubject);

        StepLogger.postCondition('Delete created template');
        await EmailTemplateManagerPageHelper.deleteTemplateBySubject(templateSubject);
        await EmailTemplateManagerPageHelper.verifyDeleteTemplate();
    });

    // Jira References - KNOV-96
    it('To verify the error message when Template type field is left empty. - [22383854]', async () => {
        // Auto generated by aurea-automation - util on Tue, 12 Mar 2019 18:51:10 GMT
        const errorMsgBlankTemplateType = EmailTemplateManagerPageConstant.titles.errorMsgBlankTemplateType;
        const vals = EmailTemplateManagerPageConstant.testData;
        const templateSubject = await PageHelper.getUniqueId();
        StepLogger.caseId = 22383854;

        StepLogger.preCondition('Execute test case C22308069 to login.');
        await AdminHomePageHelper.verifyUserNameAtTheTopRightCorner(CredentialsHelper.admin.username);
        StepLogger.preCondition('Execute test case C22383820 to access Email Template Manager screen.');
        await EmailTemplateManagerPageHelper.navigateToEmailTemplateManager();

        StepLogger.stepId(1);
        StepLogger.step('Click on Create template.');
        StepLogger.verification('Email Template properties window should be displayed.');
        await EmailTemplateManagerPageHelper.clickOnEmailTemplateAndVerify();

        StepLogger.stepId(2);
        StepLogger.step(`Leave the Template type field empty.
        Provide Language
        Provide Subject
        Provide body content.`);
        StepLogger.verification('All the values should be displayed.');
        await EmailTemplateManagerPageHelper
            .enterAndverifyTemplatePropertiesFieldsExceptTemplateType(templateSubject, vals.language);

        StepLogger.stepId(3);
        StepLogger.step('Click on submit.');
        await EmailTemplateManagerPageHelper.clickOnSubmit();
        StepLogger.verification('An error message should be displayed.');
        await EmailTemplateManagerPageHelper.verifyAlertErrorPopUpDisplayed(errorMsgBlankTemplateType);

        StepLogger.stepId(4);
        StepLogger.step('Click on OK.');
        await EmailTemplateManagerPageHelper.clickOnOkAlert();
        StepLogger.verification('The error message should be closed.');
        await EmailTemplateManagerPageHelper
            .verifyAlertErrorPopUpNoDisplayed(errorMsgBlankTemplateType);

        StepLogger.postCondition('Close create template window');
        await EmailTemplateManagerPageHelper.clickOnCancel();
    });

    // Jira References - KNOV-96
    it('To verify the error message when Subject field is left empty. - [22383861]', async () => {
        // Auto generated by aurea-automation - util on Tue, 12 Mar 2019 21:07:52 GMT
        const subjectBlankMsg = EmailTemplateManagerPageConstant.titles.errorMsgBlankSubject;
        const vals = EmailTemplateManagerPageConstant.testData;
        StepLogger.caseId = 22383861;

        StepLogger.preCondition('Execute test case C22308069 to login.');
        await AdminHomePageHelper.verifyUserNameAtTheTopRightCorner(CredentialsHelper.admin.username);
        StepLogger.preCondition('Execute test case C22383820 to access Email Template Manager screen.');
        await EmailTemplateManagerPageHelper.navigateToEmailTemplateManager();

        StepLogger.stepId(1);
        StepLogger.step('Click on Create template.');
        StepLogger.verification('Email Template properties window should be displayed.');
        await EmailTemplateManagerPageHelper.clickOnEmailTemplateAndVerify();

        StepLogger.stepId(2);
        StepLogger.step(`Provide Template type
        Provide Language
        Leave the Subject field empty.
        Provide body content.`);
        StepLogger.verification('All the values should be displayed.');
        await EmailTemplateManagerPageHelper.enterAndverifyTemplatePropertiesFieldsExceptSubject(vals.language);

        StepLogger.stepId(3);
        StepLogger.step('Click on submit.');
        await EmailTemplateManagerPageHelper.clickOnSubmit();
        StepLogger.verification('An error message should be displayed.');
        await EmailTemplateManagerPageHelper.verifyAlertErrorPopUpDisplayed(subjectBlankMsg);

        StepLogger.stepId(4);
        StepLogger.step('Click on OK.');
        await EmailTemplateManagerPageHelper.clickOnOkAlert();
        StepLogger.verification('The error message should be closed.');
        await EmailTemplateManagerPageHelper.verifyAlertErrorPopUpNoDisplayed(subjectBlankMsg);

        StepLogger.postCondition('Close create template window');
        await EmailTemplateManagerPageHelper.clickOnCancel();
    });

    // Jira References - KNOV-96
    it('To verify the Cancel button. - [22383903]', async () => {
        // Auto generated by aurea-automation - util on Tue, 12 Mar 2019 22:29:17 GMT
        const templateSubject = await PageHelper.getUniqueId();
        const vals = EmailTemplateManagerPageConstant.testData;
        StepLogger.caseId = 22383903;

        StepLogger.preCondition('Execute test case C22308069 to login.');
        await AdminHomePageHelper.verifyUserNameAtTheTopRightCorner(CredentialsHelper.admin.username);
        StepLogger.preCondition('Execute test case C22383820 to access Email Template Manager screen.');
        await EmailTemplateManagerPageHelper.navigateToEmailTemplateManager();

        StepLogger.stepId(1);
        StepLogger.step('Click on Create template.');
        StepLogger.verification('Email Template properties window should be displayed.');
        await EmailTemplateManagerPageHelper.clickOnEmailTemplateAndVerify();

        StepLogger.stepId(2);
        StepLogger.step(`Provide Template type.
        Provide Language
        Provide Subject
        Provide body content.`);
        StepLogger.verification('All the values should be displayed.');
        await EmailTemplateManagerPageHelper.enterAndverifyTemplatePropertiesFields(templateSubject, vals.language);

        StepLogger.stepId(3);
        StepLogger.step('Click on Cancel');
        await EmailTemplateManagerPageHelper.clickOnCancel();
        StepLogger.verification('The template should not be created.');
        await EmailTemplateManagerPageHelper.verifyTemplateIsNotVisibleInTemplateListing(templateSubject);
    });

    // Jira References - KNOV-96
    it('To verify the error message when Body Contents field is left empty. - [22383862]', async () => {
        // Auto generated by aurea-automation - util on Tue, 12 Mar 2019 22:50:12 GMT
        const templateSubject = await PageHelper.getUniqueId();
        const vals = EmailTemplateManagerPageConstant.testData;
        const blankBodyContentsMsg = EmailTemplateManagerPageConstant.titles.errorMsgBlankBodyContents;
        StepLogger.caseId = 22383862;

        StepLogger.preCondition('Execute test case C22308069 to login.');
        await AdminHomePageHelper.verifyUserNameAtTheTopRightCorner(CredentialsHelper.admin.username);
        StepLogger.preCondition('Execute test case C22383820 to access Email Template Manager screen.');
        await EmailTemplateManagerPageHelper.navigateToEmailTemplateManager();

        StepLogger.stepId(1);
        StepLogger.step('Click on Create template.');
        StepLogger.verification('Email Template properties window should be displayed.');
        await EmailTemplateManagerPageHelper.clickOnEmailTemplateAndVerify();

        StepLogger.stepId(2);
        StepLogger.step(`Provide Template type
        Provide Language
        Provide Subject
        Leave the body content field empty.`);
        StepLogger.verification('All the values should be displayed.');
        await EmailTemplateManagerPageHelper
            .enterAndverifyTemplatePropertiesFieldsExceptBodyContent(templateSubject, vals.language);

        StepLogger.stepId(3);
        StepLogger.step('Click on submit.');
        await EmailTemplateManagerPageHelper.clickOnSubmit();
        StepLogger.verification('An error message should be displayed.');
        await EmailTemplateManagerPageHelper.verifyAlertErrorPopUpDisplayed(blankBodyContentsMsg);

        StepLogger.stepId(4);
        StepLogger.step('Click on OK.');
        await EmailTemplateManagerPageHelper.clickOnOkAlert();
        StepLogger.verification('The error message should be closed.');
        await EmailTemplateManagerPageHelper.verifyAlertErrorPopUpNoDisplayed(blankBodyContentsMsg);

        StepLogger.postCondition('Close create template window');
        await EmailTemplateManagerPageHelper.clickOnCancel();
    });

    // Jira References - KNOV-96
    it('To verify the error message when All the fields are left empty. - [22383887]', async () => {
        // Auto generated by aurea-automation - util on Tue, 12 Mar 2019 23:04:48 GMT
        const allBlankMsg = EmailTemplateManagerPageConstant.titles.errorMsgAllBlank;
        StepLogger.caseId = 22383887;

        StepLogger.preCondition('Execute test case C22308069 to login.');
        await AdminHomePageHelper.verifyUserNameAtTheTopRightCorner(CredentialsHelper.admin.username);
        StepLogger.preCondition('Execute test case C22383820 to access Email Template Manager screen.');
        await EmailTemplateManagerPageHelper.navigateToEmailTemplateManager();

        StepLogger.stepId(1);
        StepLogger.step('Click on Create template.');
        StepLogger.verification('Email Template properties window should be displayed.');
        await EmailTemplateManagerPageHelper.clickOnEmailTemplateAndVerify();

        StepLogger.stepId(2);
        StepLogger.step(`Don"t fill any field (Language field will be filled by default)
        Click on submit.`);
        await EmailTemplateManagerPageHelper.clickOnSubmit();
        StepLogger.verification('An error message should be displayed.');
        await EmailTemplateManagerPageHelper.verifyAlertErrorPopUpDisplayed(allBlankMsg);

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await EmailTemplateManagerPageHelper.clickOnOkAlert();
        StepLogger.verification('The error message should be closed.');
        await EmailTemplateManagerPageHelper.verifyAlertErrorPopUpNoDisplayed(allBlankMsg);
    });

    // Jira References - KNOV-96
    it('To verify the error message when a template is created using the template type and language which is already existing. - [22383893]', async () => {
        // Auto generated by aurea-automation - util on Tue, 12 Mar 2019 22:12:56 GMT
        const templateSubject = await PageHelper.getUniqueId();
        const vals = EmailTemplateManagerPageConstant.testData;
        const templateExistMsg = EmailTemplateManagerPageConstant.titles.errorTemplateExists;
        StepLogger.caseId = 22383893;

        StepLogger.preCondition('Execute test case C22308069 to login.');
        await AdminHomePageHelper.verifyUserNameAtTheTopRightCorner(CredentialsHelper.admin.username);
        StepLogger.preCondition('Execute test case C22383820 to access Email Template Manager screen.');
        await EmailTemplateManagerPageHelper.navigateToEmailTemplateManager();
        StepLogger.preCondition('Create a Template to then edit');
        await EmailTemplateManagerPageHelper.createTemplateDefaultValues(templateSubject, vals.language);

        StepLogger.stepId(1);
        StepLogger.step('Click on Create template.');
        StepLogger.verification('Email Template properties window should be displayed.');
        await EmailTemplateManagerPageHelper.clickOnEmailTemplateAndVerify();

        StepLogger.stepId(2);
        StepLogger.step(`Provide a template type which is already existing in the list using the same language.
        Click on Submit`);
        await EmailTemplateManagerPageHelper.enterAndverifyTemplatePropertiesFields(templateSubject, vals.language);
        await EmailTemplateManagerPageHelper.clickOnSubmit();
        StepLogger.verification('An error message should be displayed.');
        await EmailTemplateManagerPageHelper.verifyAlertErrorPopUpDisplayed(templateExistMsg);

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await EmailTemplateManagerPageHelper.clickOnOkAlert();
        StepLogger.verification('The error message should be closed.');
        await EmailTemplateManagerPageHelper.verifyAlertErrorPopUpNoDisplayed(templateExistMsg);

        StepLogger.postCondition('Close create template window');
        await EmailTemplateManagerPageHelper.clickOnCancel();
        StepLogger.postCondition('Delete created template');
        await EmailTemplateManagerPageHelper.deleteTemplateBySubject(templateSubject);
        await EmailTemplateManagerPageHelper.verifyDeleteTemplate();
    });

    // Jira References - KNOV-96
    it('To edit the language field. - [22384364]', async () => {
        // Auto generated by aurea-automation - util on Tue, 12 Mar 2019 23:19:35 GMT
        const templateSubject = await PageHelper.getUniqueId();
        const vals = EmailTemplateManagerPageConstant.testData;
        StepLogger.caseId = 22384364;

        StepLogger.preCondition('Execute test case C22308069 to login.');
        await AdminHomePageHelper.verifyUserNameAtTheTopRightCorner(CredentialsHelper.admin.username);
        StepLogger.preCondition('Execute test case C22383820 to access Email Template Manager screen.');
        await EmailTemplateManagerPageHelper.navigateToEmailTemplateManager();
        StepLogger.preCondition('Create a Template to then edit');
        await EmailTemplateManagerPageHelper.createTemplateDefaultValues(templateSubject, vals.language);

        StepLogger.stepId(1);
        StepLogger.step('Click on the subject of the template to be edited.');
        StepLogger.verification('Email Template properties window should be displayed.');
        await EmailTemplateManagerPageHelper.clickAndVerifyOnSpecificEmailTemplate(templateSubject);

        StepLogger.stepId(2);
        StepLogger.step('Edit the language field using the drop down.');
        StepLogger.verification('The new language should be displayed in the field.');
        await EmailTemplateManagerPageHelper.selectAndVerifyLanguageDd(vals.newLanguage);

        StepLogger.stepId(3);
        StepLogger.step('Click on Submit.');
        await EmailTemplateManagerPageHelper.clickOnSubmit();
        StepLogger.verification('Another template should be created with the updated language.');
        await EmailTemplateManagerPageHelper
            .verifyTemplateIsVisibleInTemplateListingByLanguage(templateSubject, vals.newLanguage);

        StepLogger.postCondition('Delete created template by modification');
        await EmailTemplateManagerPageHelper.deleteTemplateBySubjectAndLanguage(templateSubject, vals.newLanguage);
        await EmailTemplateManagerPageHelper.verifyDeleteTemplate();
        StepLogger.postCondition('Delete created template');
        await EmailTemplateManagerPageHelper.deleteTemplateBySubject(templateSubject);
        await EmailTemplateManagerPageHelper.verifyDeleteTemplate();
    });

    it('To edit the template type field. - [22383916]', async () => {
        // Auto generated by aurea-automation - util on Wed, 13 Mar 2019 16:49:57 GMT
        const templateSubject = await PageHelper.getUniqueId();
        const vals = EmailTemplateManagerPageConstant.testData;
        StepLogger.caseId = 22383916;

        StepLogger.preCondition('Execute test case C22308069 to login.');
        await AdminHomePageHelper.verifyUserNameAtTheTopRightCorner(CredentialsHelper.admin.username);
        StepLogger.preCondition('Execute test case C22383820 to access Email Template Manager screen.');
        await EmailTemplateManagerPageHelper.navigateToEmailTemplateManager();
        StepLogger.preCondition('Create a Template to then edit');
        await EmailTemplateManagerPageHelper.createTemplateDefaultValues(templateSubject, vals.language);

        StepLogger.stepId(1);
        StepLogger.step('Click on the subject of the template to be edited.');
        StepLogger.verification('Email Template properties window should be displayed.');
        await EmailTemplateManagerPageHelper.clickAndVerifyOnSpecificEmailTemplate(templateSubject);

        StepLogger.stepId(2);
        StepLogger.step('Edit the template type field using the drop down.');
        StepLogger.verification('The new template type should be displayed in the field.');
        await EmailTemplateManagerPageHelper.selectAndVerifySpecificTemplateTypeDd(vals.newTemplateType);

        StepLogger.stepId(3);
        StepLogger.step('Click on Submit.');
        await EmailTemplateManagerPageHelper.clickOnSubmit();
        StepLogger.verification('Another template should be created with the updated template type.');
        await EmailTemplateManagerPageHelper
            .verifyTemplateIsVisibleInTemplateListingByTemplateType(templateSubject, vals.language, vals.newTemplateType);

        StepLogger.postCondition('Delete created template by modification');
        await EmailTemplateManagerPageHelper.deleteTemplateBySubjectAndLanguage(templateSubject, vals.language);
        await EmailTemplateManagerPageHelper.verifyDeleteTemplate();
        StepLogger.postCondition('Delete created template');
        await EmailTemplateManagerPageHelper.deleteTemplateBySubject(templateSubject);
        await EmailTemplateManagerPageHelper.verifyDeleteTemplate();
    });

    // Jira References - KNOV-96
    it('To edit subject and body contents fields. - [22384909]', async () => {
        // Auto generated by aurea-automation - util on Wed, 13 Mar 2019 20:20:15 GMT
        const templateSubject = await PageHelper.getUniqueId();
        const vals = EmailTemplateManagerPageConstant.testData;
        StepLogger.caseId = 22384909;

        StepLogger.preCondition('Execute test case C22308069 to login.');
        await AdminHomePageHelper.verifyUserNameAtTheTopRightCorner(CredentialsHelper.admin.username);
        StepLogger.preCondition('Execute test case C22383820 to access Email Template Manager screen.');
        await EmailTemplateManagerPageHelper.navigateToEmailTemplateManager();
        StepLogger.preCondition('Create a Template to then edit');
        await EmailTemplateManagerPageHelper.createTemplateDefaultValues(templateSubject, vals.language);

        StepLogger.stepId(1);
        StepLogger.step('Click on the subject of the template to be edited.');
        StepLogger.verification('Email Template properties window should be displayed.');
        await EmailTemplateManagerPageHelper.clickAndVerifyOnSpecificEmailTemplate(templateSubject);

        StepLogger.stepId(2);
        StepLogger.step('Edit subject and body contents fields.');
        StepLogger.verification('The new details should be displayed in the field.');
        await EmailTemplateManagerPageHelper.enterAndVerifySubjectAndBody(vals.newSubject, vals.newBodyContents);

        StepLogger.stepId(3);
        StepLogger.step('Click on Submit.');
        await EmailTemplateManagerPageHelper.clickOnSubmit();
        StepLogger.verification('The same template should be updated.');
        await EmailTemplateManagerPageHelper.verifyTemplateIsVisibleInTemplateListing(vals.newSubject);

        StepLogger.postCondition('Delete created template');
        await EmailTemplateManagerPageHelper.deleteTemplateBySubject(vals.newSubject);
        await EmailTemplateManagerPageHelper.verifyDeleteTemplate();
    });
});
