import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { RandomHelper } from '../../../components/misc-utils/random-helper';
import {
        AgentMicrositeSelfServiceHelper
} from '../../../page-objects/pages/self-service/agent-microsite-tab/agent-microsite.helper';
import { SelfServiceHomePageHelper } from '../../../page-objects/pages/self-service/self-service-home-page.helper';
import { SelfServiceLoginPageHelper } from '../../../page-objects/pages/self-service/self-service-login.helper';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.healthCheckSuite, () => {
    let loginPageHelper: SelfServiceLoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = SelfServiceLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        await loginPageHelper.goTo();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await SelfServiceLoginPageHelper.logout();
        await SelfServiceLoginPageHelper.loginAsAdmin();
    });

    // Jira References - KNOV-528
    it('Verify the page navigates to on a document from What"s Popular Widget. - [22894606]', async () => {
        // Auto generated by aurea-automation - util on Mon, 11 Mar 2019 14:15:43 GMT
        StepLogger.caseId = 22894606;

        // Step 1 is covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step('Log in to the application.');
        StepLogger.verification('The user is able to log in to application.');

        StepLogger.stepId(2);
        StepLogger.step('Scroll the bar down to search and see What"s Popular section.');
        StepLogger.verification('What"s popular section is present.');
        await AgentMicrositeSelfServiceHelper.scrollAndClickWhatsPopularSection();

        StepLogger.stepId(3);
        StepLogger.step('Click on document name.');
        StepLogger.verification('Page navigates to document details.');
        await AgentMicrositeSelfServiceHelper.clickAndVerifyDetailsFirstDocument();

        StepLogger.postCondition('Navigate to Self-Service Main Page');
        await AgentMicrositeSelfServiceHelper.clickOnUpwardArrow();
    });

    // Jira References - KNOV-528
    it('Verify by clicking on Full Screen icon in Top LHS to view the document in Full Screen Mode. - [22894609]', async () => {
        // Auto generated by aurea-automation - util on Mon, 11 Mar 2019 15:22:58 GMT
        StepLogger.caseId = 22894609;

        StepLogger.preCondition('Run the TC C22894606.');
        await AgentMicrositeSelfServiceHelper.navigateToFirstWhatsPopularDocument();

        StepLogger.stepId(1);
        StepLogger.step('Click on full screen icon.');
        StepLogger.verification('A new window is displayed for viewing the document.');
        const amountTabBars = await AgentMicrositeSelfServiceHelper.clickFullScreenIcon();

        // Step 2 is covered in step 3
        StepLogger.stepId(2);
        StepLogger.step('Verify the details on view document page displayed are same as customer microsite document details page.');
        StepLogger.verification('Details on both the page are same.');

        StepLogger.stepId(3);
        StepLogger.step('Verify the full screen icon is not present on view document page.');
        StepLogger.verification('The full screen icon is not present on view document details page.');
        await AgentMicrositeSelfServiceHelper.compareAndVerifyDocumentDetails(amountTabBars);

        StepLogger.postCondition('Close Dialog Window');
        await AgentMicrositeSelfServiceHelper.closeNewPage();
        StepLogger.postCondition('Navigate to Self-Service Main Page');
        await AgentMicrositeSelfServiceHelper.clickOnUpwardArrow();
    });

   // Jira References - KNOV-528
    it('Verify the user can email the document . - [22894617]', async () => {
        // Auto generated by aurea-automation - util on Mon, 11 Mar 2019 18:55:41 GMT
        const email = await RandomHelper.getRandomEmail();
        StepLogger.caseId = 22894617;

        StepLogger.preCondition('Run the TC C22894606.');
        await AgentMicrositeSelfServiceHelper.navigateToFirstWhatsPopularDocument();

        StepLogger.stepId(1);
        StepLogger.step('Click on email document.');
        await AgentMicrositeSelfServiceHelper.clickOnEmailDocument();
        StepLogger.verification('Email Document window is displayed.');
        await AgentMicrositeSelfServiceHelper.verifyEmailTheDocumentWindowPage();

        StepLogger.stepId(2);
        StepLogger.step('Fill in the to field.');
        StepLogger.verification('user is able to enter the To field.');
        await AgentMicrositeSelfServiceHelper.enterAndVerifyToEmailField(email);

        StepLogger.stepId(3);
        StepLogger.step('Click on Submit button.');
        await AgentMicrositeSelfServiceHelper.clickOnSubmit();
        StepLogger.verification('It will display error message or success message as the mail is sent or not.');
        await AgentMicrositeSelfServiceHelper.verifyEmailAknowledgement();

        StepLogger.postCondition('Navigate to Self-Service Main Page');
        await AgentMicrositeSelfServiceHelper.clickOnUpwardArrow();
    });

    // Jira References - KNOV-528
    it('Verify a user can subscribe by clicking through RSS icon. - [22894618]', async () => {
        // Auto generated by aurea-automation - util on Mon, 11 Mar 2019 21:08:49 GMT
        StepLogger.caseId = 22894618;

        StepLogger.preCondition('Run the TC C22894606.');
        await AgentMicrositeSelfServiceHelper.navigateToFirstWhatsPopularDocument();

        StepLogger.stepId(1);
        StepLogger.step('Click on Subscribe to Document Through RSS icon.');
        await AgentMicrositeSelfServiceHelper.clickOnSubscribeByRSS();
        StepLogger.verification('RSS subscription details window  is displayed.');
        await AgentMicrositeSelfServiceHelper.verifyRSSSubscriptionWindow();

        StepLogger.stepId(2);
        StepLogger.step('Click on close button.');
        StepLogger.verification('the window gets closed.');
        await AgentMicrositeSelfServiceHelper.clickOnClose();

        StepLogger.postCondition('Navigate to Self-Service Main Page');
        await AgentMicrositeSelfServiceHelper.clickOnUpwardArrow();
    });

    // Jira References - KNOV-528
    it('Verify the upward arrow functionality and back icon to previous page. - [22894621]', async () => {
        // Auto generated by aurea-automation - util on Mon, 11 Mar 2019 22:09:18 GMT
        StepLogger.caseId = 22894621;

        StepLogger.preCondition('Run the TC C22894606.');
        await AgentMicrositeSelfServiceHelper.navigateToFirstWhatsPopularDocument();

        StepLogger.stepId(1);
        StepLogger.step('Click on upward arrow icon.');
        await AgentMicrositeSelfServiceHelper.clickOnUpwardArrow();
        StepLogger.verification('It goes back to What"s popular section.');
        await SelfServiceHomePageHelper.verifyWelcomeLabelDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on the document name again.');
        StepLogger.verification('Details page is displayed.');
        await AgentMicrositeSelfServiceHelper.clickAndVerifyDetailsFirstDocument();

        StepLogger.stepId(3);
        StepLogger.step('Click on Back icon.');
        await AgentMicrositeSelfServiceHelper.clickOnBackToPreviousPage();
        StepLogger.verification('It transfers to previous page.');
        await SelfServiceHomePageHelper.verifyWelcomeLabelDisplayed();
    });

    // Jira References - KNOV-528
    it('Verify a user can subscribe by clicking through email icon. - [22894619]', async () => {
        // Auto generated by aurea-automation - util on Mon, 11 Mar 2019 22:21:39 GMT
        StepLogger.caseId = 22894619;

        StepLogger.preCondition('Run the TC C22894606.');
        await AgentMicrositeSelfServiceHelper.navigateToFirstWhatsPopularDocument();

        StepLogger.stepId(1);
        StepLogger.step('Click on Subscribe to Document Through Email icon.');
        await AgentMicrositeSelfServiceHelper.clickOnSubscribeByEmail();
        StepLogger.verification('Email Subscription Details  window is displayed.');
        await AgentMicrositeSelfServiceHelper.verifyEmailSubscriptionWindow();

        StepLogger.stepId(2);
        StepLogger.step('Select any value from drop down list of Send emails.');
        StepLogger.verification('user is able to select drop down list of send emails.');

        StepLogger.stepId(3);
        StepLogger.step('Click on submit button.');
        await AgentMicrositeSelfServiceHelper.clickOnSubmit();
        StepLogger.verification('the window is closed.');
        await AgentMicrositeSelfServiceHelper.verifyDialogWindowClosedDocumentDisplayed();

        StepLogger.postCondition('Navigate to Self-Service Main Page');
        await AgentMicrositeSelfServiceHelper.clickOnUpwardArrow();
    });

    // Jira References - KNOV-528
    it('Verify the user can print the document. - [22894620]', async () => {
        // Auto generated by aurea-automation - util on Mon, 11 Mar 2019 21:33:45 GMT
        StepLogger.caseId = 22894620;

        StepLogger.preCondition('Run the TC C22894606.');
        await AgentMicrositeSelfServiceHelper.navigateToFirstWhatsPopularDocument();

        // Step 1 verification is included in step 2
        StepLogger.stepId(1);
        StepLogger.step('Click on print icon.');
        const docTitle = await AgentMicrositeSelfServiceHelper.clickOnPrint();
        StepLogger.verification('the document details are displayed in a new window.');

        StepLogger.stepId(2);
        StepLogger.step('Verify the details are as displayed on customer microsite page.');
        StepLogger.verification('the details are as present on microsite page.');
        await AgentMicrositeSelfServiceHelper.verifyDocumentDetaisInNewPage(docTitle);

        StepLogger.stepId(3);
        StepLogger.step('Close the print window by clicking the "X" option available on top right of the page.');
        await AgentMicrositeSelfServiceHelper.closeNewPage();
        StepLogger.verification(`The print window launched on clicking the "Print" option should be closed and the
        user should be navigated to the "Content" page of the selected document.`);
        await AgentMicrositeSelfServiceHelper.verifyDocDetailsContent(docTitle);

        StepLogger.postCondition('Navigate to Self-Service Main Page');
        await AgentMicrositeSelfServiceHelper.clickOnUpwardArrow();
    });
});
