import { StepLogger } from '../../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../../components/html/page-helper';
import { AdminHomePageHelper } from '../../../../../page-objects/pages/admin-home-page/admin-home.helper';
import { RssFeedManagerHelper } from '../../../../../page-objects/pages/administer-system/rss-feed-manager/rss-feed-manager.helper';
import { KnowledgeCentralHomePageConstant } from '../../../../../page-objects/pages/knowledge-central-home-page/knowledge-central-home.constants';
import { KnowledgeCentralHomePageHelper } from '../../../../../page-objects/pages/knowledge-central-home-page/knowledge-central-home.helper';
import { KnowledgeCentralHomePage } from '../../../../../page-objects/pages/knowledge-central-home-page/knowledge-central-home.po';
import { KnowledgeCentralLoginPageHelper } from '../../../../../page-objects/pages/knowledge-central-login-page/knowledge-central-login.helper';
import { KnowledgeCentralLoginPage } from '../../../../../page-objects/pages/knowledge-central-login-page/knowledge-central-login.po';
import { SuiteNames } from '../../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: KnowledgeCentralLoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = KnowledgeCentralLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        await loginPageHelper.goTo();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await KnowledgeCentralLoginPageHelper.logout();
        await loginPageHelper.goTo();
        await KnowledgeCentralLoginPageHelper.loginAsAdmin();
    });

    // Jira References - KNOV-494
    it('Verify Admin user is able to access the "About" pane of "Settings"  page in Knova knowledge Central application - [22936981]', async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:20 GMT

        StepLogger.caseId = 22936981;
        const about = KnowledgeCentralHomePageConstant.elementNames.about;

        // Step -1 is covered in before each
        StepLogger.stepId(1);
        StepLogger.step('Launch the Knova Knowledge Central application and login with admin credentials');
        StepLogger.verification('Admin User should be able to login to the Knova Knowledge Central application successfully');
        await KnowledgeCentralHomePageHelper.verifyHeaderBannerDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click the burger icon from the top left corner of the page.');
        await KnowledgeCentralHomePageHelper.clickOnMenuIcon();
        StepLogger.verification(
            'The vertical menu bar with the available modules and options should be displayed on the left end of the page.'
        );
        await KnowledgeCentralHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on the "Settings"');
        await AdminHomePageHelper.clickSettings();
        StepLogger.verification(`The below options should be displayed on the right side
			About
			Help`);
        await KnowledgeCentralHomePageHelper.verifySettingsSubMenu();

        StepLogger.stepId(4);
        StepLogger.step('Click on the "About" option');
        await KnowledgeCentralHomePageHelper.clickAbout();
        StepLogger.verification('"About" pane should open with details of Knova Knowledge Central');
        await KnowledgeCentralHomePageHelper.verifyPopUp(about);

        StepLogger.stepId(5);
        StepLogger.step('Click on "X" in the About Pane');
        await KnowledgeCentralHomePageHelper.clickPopupClose();
        StepLogger.verification('"About" window should get closed');
        await RssFeedManagerHelper.verifyPopClosed();

        StepLogger.stepId(6);
        StepLogger.step('Click the burger icon from the top left corner of the page and select the "Logout" option.');
        await KnowledgeCentralHomePageHelper.logout();
        StepLogger.verification('user should be logged out and the Knova knowledge central application login page should be displayed');
        await KnowledgeCentralLoginPage.loginForm.login.verifyPresentStatus();
    });

    // Jira References - KNOV-494
    it('Verify Admin user is able to access the "Help" pane of "Settings"  page in Knova knowledge Central application - [22937006]', async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:19 GMT

        StepLogger.caseId = 22937006;
        // Step -1 is covered in before each
        StepLogger.stepId(1);
        StepLogger.step('Launch the Knova Knowledge Central application and login with admin credentials');
        StepLogger.verification('Admin User should be able to login to the Knova Knowledge Central application successfully');
        await KnowledgeCentralHomePageHelper.verifyHeaderBannerDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click the burger icon from the top left corner of the page.');
        await KnowledgeCentralHomePageHelper.clickOnMenuIcon();
        StepLogger.verification(
            'The vertical menu bar with the available modules and options should be displayed on the left end of the page.'
        );
        await KnowledgeCentralHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on the "Settings"');
        await AdminHomePageHelper.clickSettings();
        StepLogger.verification(`The below options should be displayed on the right side
			About
			Help`);
        await KnowledgeCentralHomePageHelper.verifySettingsSubMenu();

        StepLogger.stepId(4);
        StepLogger.step('Click on the "Help" option');
        await KnowledgeCentralHomePageHelper.clickHelp();
        StepLogger.verification('"KNOVA KNOWLEDGE CENTRAL HELP" window pane should get displayed');
        await KnowledgeCentralHomePageHelper.verifyHelpPane();

        StepLogger.stepId(5);
        StepLogger.step('Click on "X" in the Help window');
        await PageHelper.closeCurrentTab();
        StepLogger.verification('"Help" window should get closed');
        await KnowledgeCentralHomePageHelper.verifyWindowClosed();

        StepLogger.stepId(6);
        StepLogger.step('Click the burger icon from the top left corner of the page and select the "Logout" option');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
        StepLogger.verification('user should be logged out and the Knova knowledge central application login page should be displayed');
        await KnowledgeCentralLoginPage.loginForm.login.verifyPresentStatus();
    });

    // Jira References - KNOV-494
    it(`Verify Admin user is able to access the "TOC", "Index" and "Search" page sections of
		Settings>Help pane  in Knova knowledge Central application - [22937029]`, async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:20 GMT

        StepLogger.caseId = 22937029;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelp();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "Help" pane as specified in the Precondition [C22937006]');
        await KnowledgeCentralHomePageHelper.clickHelp();
        StepLogger.verification('"KNOVA KNOWLEDGE CENTRAL HELP" window pane should get displayed');
        await KnowledgeCentralHomePageHelper.verifyHelpPane();

        StepLogger.stepId(2);
        StepLogger.step('Click on "TOC" section available at the bottom in the left pane');
        await KnowledgeCentralHomePageHelper.clickToc();
        StepLogger.verification('"TOC" section should get displayed to the user');
        await KnowledgeCentralHomePageHelper.verifyTocSection();

        StepLogger.stepId(3);
        StepLogger.step('Click on "Index" section available below the "TOC" section');
        await KnowledgeCentralHomePageHelper.clickIndex();
        StepLogger.verification('"Index" section should get displayed to the user');
        await KnowledgeCentralHomePageHelper.verifyIndexSection();

        StepLogger.stepId(4);
        StepLogger.step('Click on "Search" section available below the "Index" section');
        await KnowledgeCentralHomePageHelper.clickSearch();
        StepLogger.verification('A free text field with Search button should get displayed to the user');
        await KnowledgeCentralHomePageHelper.verifySearchSection();

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });

    // Jira References - KNOV-494
    it('Verify Admin user is able to view and access topics of  "TOC" in "Help" pane of Knova knowledge Central application - [22937032]', async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:18 GMT

        StepLogger.caseId = 22937032;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelp();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "Help" pane as specified in the Precondition');
        await KnowledgeCentralHomePageHelper.clickHelp();
        StepLogger.verification('"KNOVA KNOWLEDGE CENTRAL HELP" window pane should get displayed');
        await KnowledgeCentralHomePageHelper.verifyHelpPane();

        StepLogger.stepId(2);
        StepLogger.step('Click on "TOC" page section');
        await KnowledgeCentralHomePageHelper.clickToc();
        StepLogger.verification('User should get navigated to "TOC" page section');
        await KnowledgeCentralHomePageHelper.verifyTocSection();

        StepLogger.stepId(3);
        StepLogger.step('Click on "KNOVA KNOWLEDGE CENTRAL HELP"  hyperlink in the left pane');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.knovaCentralHelp);
        StepLogger.verification('Topics of  "KNOVA KNOWLEDGE CENTRAL HELP" should get displayed');
        await KnowledgeCentralHomePageHelper.verifyTocOption();

        StepLogger.stepId(4);
        StepLogger.step('Randomly click on any topic Ex : "Navigating Knova Knowledge Central"');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.navigateKnovaCentral);
        StepLogger.verification('User should get navigated to the respective topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.navigateKnovaCentralTitle);

        StepLogger.stepId(5);
        StepLogger.step('Repeat the above step for other topics and verify user is able to navigate to the topics');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.introToKnovaCentral);
        StepLogger.verification('User should be able to navigate to selected topic without errors');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.introToKnovaCentralTitle);

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });

    // Jira References - KNOV-494
    it('Verify Admin user is able to perform search in a selected topic page of "TOC" page section - [22937051]', async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:19 GMT

        StepLogger.caseId = 22937051;
        const access = KnowledgeCentralHomePageConstant.elementNames.access;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelpPage();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "TOC" page of Settings> Help pane');
        await KnowledgeCentralHomePageHelper.clickToc();
        StepLogger.verification('User should get navigated to "TOC" page');
        await KnowledgeCentralHomePageHelper.verifyTocSection();

        StepLogger.stepId(2);
        StepLogger.step('Click on "KNOVA KNOWLEDGE CENTRAL HELP" in the left pane');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.knovaCentralHelp);
        StepLogger.verification('All topics of  "KNOVA KNOWLEDGE CENTRAL HELP" should get displayed');
        await KnowledgeCentralHomePageHelper.verifyTocOption();

        StepLogger.stepId(3);
        StepLogger.step('Randomly click on any topic Ex : "Navigating Knova Knowledge Central"');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.navigateKnovaCentral);
        StepLogger.verification('User should get navigated to the respective topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.navigateKnovaCentralTitle);

        StepLogger.stepId(4);
        StepLogger.step('Observe that at the top of the page a free text search field is available with magnifying glass');
        StepLogger.verification('Search this topic free text field should be available with magnifying glass');
        await KnowledgeCentralHomePageHelper.verifySearchBox();

        StepLogger.stepId(5);
        StepLogger.step('Enter Text Ex: User in the free text search field and click on magnifying glass');
        await KnowledgeCentralHomePageHelper.enterTextInSearchBoxAndClickSearch(access);
        StepLogger.verification('The Search results should be displayed and highlighted in the topic page');
        await KnowledgeCentralHomePageHelper.verifyHighlightedResult(access);

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });

    // Jira References - KNOV-494
    it(`Verify "Remove Search Highlighting" option removes the highlight on search after the search is performed in a
		selected topic page of "TOC" page section - [22937055]`, async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:18 GMT

        StepLogger.caseId = 22937055;
        const access = KnowledgeCentralHomePageConstant.elementNames.access;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelpPage();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "TOC" page of Settings> Help pane');
        await KnowledgeCentralHomePageHelper.clickToc();
        StepLogger.verification('User should get navigated to "TOC" page');
        await KnowledgeCentralHomePageHelper.verifyTocSection();

        StepLogger.stepId(2);
        StepLogger.step('Click on "KNOVA KNOWLEDGE CENTRAL HELP" in the left pane');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.knovaCentralHelp);
        StepLogger.verification('All topics of  "KNOVA KNOWLEDGE CENTRAL HELP" should get displayed');
        await KnowledgeCentralHomePageHelper.verifyTocOption();

        StepLogger.stepId(3);
        StepLogger.step('Randomly click on any topic Ex : "Navigating Knova Knowledge Central"');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.navigateKnovaCentral);
        StepLogger.verification('User should get navigated to the respective topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.navigateKnovaCentralTitle);

        StepLogger.stepId(4);
        StepLogger.step('Enter Text Ex: User in the free text search field and click on magnifying glass');
        await KnowledgeCentralHomePageHelper.enterTextInSearchBoxAndClickSearch(access);
        StepLogger.verification('The Search results should be displayed and highlighted in the topic page');
        await KnowledgeCentralHomePageHelper.verifyHighlightedResult(access);

        StepLogger.stepId(5);
        StepLogger.step('Click on "Remove Search Highlighting" option present beside Search button');
        await KnowledgeCentralHomePageHelper.clickRemoveHighlight();
        StepLogger.verification('Searched text should no longer be highlighted');
        await KnowledgeCentralHomePageHelper.verifyHighlightedRemoved();

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });
});
