import { StepLogger } from '../../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../../components/html/page-helper';
import { KnowledgeCentralHomePageConstant } from '../../../../../page-objects/pages/knowledge-central-home-page/knowledge-central-home.constants';
import { KnowledgeCentralHomePageHelper } from '../../../../../page-objects/pages/knowledge-central-home-page/knowledge-central-home.helper';
import { KnowledgeCentralHomePage } from '../../../../../page-objects/pages/knowledge-central-home-page/knowledge-central-home.po';
import { KnowledgeCentralLoginPageHelper } from '../../../../../page-objects/pages/knowledge-central-login-page/knowledge-central-login.helper';
import { SuiteNames } from '../../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: KnowledgeCentralLoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = KnowledgeCentralLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        await loginPageHelper.goTo();
    });

    beforeEach(async () => {
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
        await loginPageHelper.goTo();
        await KnowledgeCentralLoginPageHelper.loginAsAdmin();
    });

    // Jira References - KNOV-494
    it(`Verify Admin user is able to navigate back to the previous topic from current topic by selecting the "Back"
		button in the current topic page of "TOC" page section - [22937071]`, async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:18 GMT

        StepLogger.caseId = 22937071;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelpPage();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "TOC" page of Settings> Help pane');
        await KnowledgeCentralHomePageHelper.clickToc();
        StepLogger.verification('User should get navigated to "TOC" page');
        await KnowledgeCentralHomePageHelper.verifyTocSection();

        StepLogger.stepId(2);
        StepLogger.step('Click on "KNOVA KNOWLEDGE CENTRAL HELP"  in the left pane');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.knovaCentralHelp);
        StepLogger.verification('All topics of  "KNOVA KNOWLEDGE CENTRAL HELP" should get displayed');
        await KnowledgeCentralHomePageHelper.verifyTocOption();

        StepLogger.stepId(3);
        StepLogger.step('Randomly click on any topic Ex : "Navigating Knova Knowledge Central"');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.navigateKnovaCentral);
        StepLogger.verification('User should get navigated to the  "Navigating Knova Knowledge Central" topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.navigateKnovaCentralTitle);

        StepLogger.stepId(4);
        StepLogger.step('Now select an other topic Ex : Collaboration');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.introToKnovaCentral);
        StepLogger.verification('User should get navigated to the  "Collaboration" topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.introToKnovaCentralTitle);

        StepLogger.stepId(5);
        StepLogger.step('Click on "Back" button in the "Collaboration" topic page');
        await KnowledgeCentralHomePageHelper.clickBack();
        StepLogger.verification('User should get navigated to his previous topic "Navigating Knova Knowledge Central" page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.navigateKnovaCentralTitle);

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });

    // Jira References - KNOV-494
    it(`Verify Admin user is able to navigate to the current topic from previous topic by selecting the
		"Forward" option in the previous topic page of "TOC" page section - [22937078]`, async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:19 GMT

        StepLogger.caseId = 22937078;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelpPage();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "TOC" section of Settings> Help pane');
        await KnowledgeCentralHomePageHelper.clickToc();
        StepLogger.verification('User should get navigated to "TOC" page section');
        await KnowledgeCentralHomePageHelper.verifyTocSection();

        StepLogger.stepId(2);
        StepLogger.step('Click on "KNOVA KNOWLEDGE CENTRAL HELP"  in the left pane');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.knovaCentralHelp);
        StepLogger.verification('All topics of  "KNOVA KNOWLEDGE CENTRAL HELP" should get displayed');
        await KnowledgeCentralHomePageHelper.verifyTocOption();

        StepLogger.stepId(3);
        StepLogger.step('Randomly click on any topic Ex : "Navigating Knova Knowledge Central"');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.navigateKnovaCentral);
        StepLogger.verification('User should get navigated to the  "Navigating Knova Knowledge Central" topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.navigateKnovaCentralTitle);

        StepLogger.stepId(4);
        StepLogger.step('Now select another topic Ex : Collaboration');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.introToKnovaCentral);
        StepLogger.verification('User should get navigated to the  "Collaboration" topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.introToKnovaCentralTitle);

        StepLogger.stepId(5);
        StepLogger.step('Click on "Back" button in the "Collaboration" topic page');
        await KnowledgeCentralHomePageHelper.clickBack();
        StepLogger.verification('User should get navigated to his previous topic "Navigating Knova Knowledge Central"');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.navigateKnovaCentralTitle);

        StepLogger.stepId(6);
        StepLogger.step('Now click on "Forward" button in "Navigating Knova Knowledge Central" topic page');
        await KnowledgeCentralHomePageHelper.clickForward();
        StepLogger.verification('User should get navigated to his current topic page  "Collaboration"');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.introToKnovaCentralTitle);

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });

    // Jira References - KNOV-494
    it(`Verify Admin user is able click on hyperlinks available on a selected topic page to navigate to
		previous topics in the "TOC" page section - [22937081]`, async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:20 GMT

        StepLogger.caseId = 22937081;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelpPage();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "TOC" section of Settings> Help pane');
        await KnowledgeCentralHomePageHelper.clickToc();
        StepLogger.verification('User should get navigated to "TOC" page section');
        await KnowledgeCentralHomePageHelper.verifyTocSection();

        StepLogger.stepId(2);
        StepLogger.step('Click on "KNOVA KNOWLEDGE CENTRAL HELP"  in the left pane');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.knovaCentralHelp);
        StepLogger.verification('All topics of  "KNOVA KNOWLEDGE CENTRAL HELP" should get displayed');
        await KnowledgeCentralHomePageHelper.verifyTocOption();

        StepLogger.stepId(3);
        StepLogger.step('Randomly click on any topic Ex : "Navigating Knova Knowledge Central"');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.navigateKnovaCentral);
        StepLogger.verification('User should get navigated to the  "Navigating Knova Knowledge Central" topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.navigateKnovaCentralTitle);

        StepLogger.stepId(4);
        StepLogger.step('Randomly click on any sub-topic in the "Navigating Knova Knowledge Central" topic page Ex: Case Management');
        await KnowledgeCentralHomePageHelper.clickTocOption(KnowledgeCentralHomePage.helpPane.caseManagement);
        StepLogger.verification('User should get navigated to the "Case Management" topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.caseManagerTitle);

        StepLogger.stepId(5);
        StepLogger.step(`Click on Hyperlinks present at the top in the "Case Management" topic page
            Ex : Knova Knowledge Central Help`);
        await KnowledgeCentralHomePageHelper.clickBreadCrumb(KnowledgeCentralHomePage.helpPane.navigateKnovaCentralBreadCrumb);
        StepLogger.verification('User should get navigated to the selected Hyperlink page successfully without errors');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.navigateKnovaCentralTitle);

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });

    // Jira References - KNOV-494
    it(`Verify Admin user is able to navigate to the current topic from previous topic by selecting the "Forward" option in the
        previous topic page of "Index" page section - [22937143]`, async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:42 GMT

        StepLogger.caseId = 22937143;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelp();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "Help" pane as specified in the Precondition [C22937006]');
        await KnowledgeCentralHomePageHelper.clickHelp();
        StepLogger.verification('"KNOVA KNOWLEDGE CENTRAL HELP" window should get displayed');
        await KnowledgeCentralHomePageHelper.verifyHelpPane();

        StepLogger.stepId(2);
        StepLogger.step('Click on "Index" page section');
        await KnowledgeCentralHomePageHelper.clickIndex();
        StepLogger.verification('User should get navigated to "Index" page section');
        await KnowledgeCentralHomePageHelper.verifyIndexSection();

        StepLogger.stepId(3);
        StepLogger.step('Randomly click on any topic Ex : "Access Levels"');
        await KnowledgeCentralHomePageHelper.clickIndexOption(KnowledgeCentralHomePage.helpPane.accessLevels);
        StepLogger.verification('User should get navigated to the respective topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.accessLevelsTitle);

        StepLogger.stepId(4);
        StepLogger.step('Now select an other topic Ex : "alerts"');
        await KnowledgeCentralHomePageHelper.clickIndexOption(KnowledgeCentralHomePage.helpPane.alerts);
        StepLogger.verification('User should get navigated to the "alerts" topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.alertsTitle);

        StepLogger.stepId(5);
        StepLogger.step('Click on "Back" button in the "alerts" topic page');
        await KnowledgeCentralHomePageHelper.clickBack();
        StepLogger.verification('User should get navigated to his previous topic "Access Levels"');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.accessLevelsTitle);

        StepLogger.stepId(6);
        StepLogger.step('Now click on "Forward" button in "Access Levels" topic page');
        await KnowledgeCentralHomePageHelper.clickForward();
        StepLogger.verification('User should get navigated to his current topic page  "alerts"');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.alertsTitle);

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });

    // Jira References - KNOV-494
    it('Verify admin user is able to search a topic using Search bar in the Settings>Help pane - [22937167]', async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:42 GMT

        StepLogger.caseId = 22937167;
        const collaboration = KnowledgeCentralHomePageConstant.elementNames.collaboration;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelp();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "Help" pane as specified in the Precondition [C22937006]');
        await KnowledgeCentralHomePageHelper.clickHelp();
        StepLogger.verification('"KNOVA KNOWLEDGE CENTRAL HELP" window should get displayed');
        await KnowledgeCentralHomePageHelper.verifyHelpPane();

        StepLogger.stepId(2);
        StepLogger.step('Click on Search bar available in the left pane');
        await KnowledgeCentralHomePageHelper.clickSearch();
        StepLogger.verification('A free text field with Search button should get displayed for User');
        await KnowledgeCentralHomePageHelper.verifySearchField();

        StepLogger.stepId(3);
        StepLogger.step('Enter any Search text Ex: Collaboration and click on Search button');
        await KnowledgeCentralHomePageHelper.enterTextAndClickSearch(collaboration);
        StepLogger.verification('User should be able to enter the specified search text and click on Search');
        await KnowledgeCentralHomePageHelper.verifyTextInSearchField(collaboration);

        StepLogger.stepId(4);
        StepLogger.step('Verify all the topics related to the searched text gets displayed as results');
        StepLogger.verification('All the topics related to the searched text should get displayed as results');
        await KnowledgeCentralHomePageHelper.verifySearchResults();

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });

    // Jira References - KNOV-494
    it(`Verify "Remove Search Highlighting" option removes the highlight on search after
        the search is performed in a selected topic page of "Index" page section - [22937100]`, async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:42 GMT

        StepLogger.caseId = 22937100;
        const access = KnowledgeCentralHomePageConstant.elementNames.access;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelp();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "Help" pane as specified in the Precondition [C22937006]');
        await KnowledgeCentralHomePageHelper.clickHelp();
        StepLogger.verification('"KNOVA KNOWLEDGE CENTRAL HELP" window should get displayed');
        await KnowledgeCentralHomePageHelper.verifyHelpPane();

        StepLogger.stepId(2);
        StepLogger.step('Click on "Index" page section');
        await KnowledgeCentralHomePageHelper.clickIndex();
        StepLogger.verification('User should get navigated to "Index" page section');
        await KnowledgeCentralHomePageHelper.verifyIndexSection();

        StepLogger.stepId(3);
        StepLogger.step('Randomly click on any topic Ex : "Access Levels"');
        await KnowledgeCentralHomePageHelper.clickIndexOption(KnowledgeCentralHomePage.helpPane.accessLevels);
        StepLogger.verification('User should get navigated to the respective topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.accessLevelsTitle);

        StepLogger.stepId(4);
        StepLogger.step('Enter Text Ex: User in the free text search field and click on magnifying glass');
        await KnowledgeCentralHomePageHelper.enterTextInSearchBoxAndClickSearch(access);
        StepLogger.verification('The Search results should be displayed and highlighted in the topic page');
        await KnowledgeCentralHomePageHelper.verifyHighlightedResult(access);

        StepLogger.stepId(5);
        StepLogger.step('Click on "Remove Search Highlighting" option present beside Search button');
        await KnowledgeCentralHomePageHelper.clickRemoveHighlight();
        StepLogger.verification('Searched text should no longer be highlighted');
        await KnowledgeCentralHomePageHelper.verifyHighlightedRemoved();

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });

    // Jira References - KNOV-494
    it(`Verify Admin user is able to click on hyperlinks available on a selected topic page to
        navigate to previous topics  in the "Index" section - [22937151]`, async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:43 GMT

        StepLogger.caseId = 22937151;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelp();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "Help" pane as specified in the Precondition C22937006');
        await KnowledgeCentralHomePageHelper.clickHelp();
        StepLogger.verification('"KNOVA KNOWLEDGE CENTRAL HELP" window should get displayed');
        await KnowledgeCentralHomePageHelper.verifyHelpPane();

        StepLogger.stepId(2);
        StepLogger.step('Click on "Index" page section');
        await KnowledgeCentralHomePageHelper.clickIndex();
        StepLogger.verification('User should get navigated to "Index" page section');
        await KnowledgeCentralHomePageHelper.verifyIndexSection();

        StepLogger.stepId(3);
        StepLogger.step('Randomly click on any topic Ex : "Access Levels"');
        await KnowledgeCentralHomePageHelper.clickIndexOption(KnowledgeCentralHomePage.helpPane.accessLevels);
        StepLogger.verification('User should get navigated to the respective topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.accessLevelsTitle);

        StepLogger.stepId(4);
        StepLogger.step(`Click on Hyperlinks present at the top in the 'Access Levels' topic page
            Ex : Knova Knowledge Central Help`);
        await KnowledgeCentralHomePageHelper.clickBreadCrumb(KnowledgeCentralHomePage.helpPane.contentEditorBreadCrumb);
        StepLogger.verification('User should get navigated to the selected Hyperlink page  successfully without errors');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.contentEditorTitle);

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });

    // Jira References - KNOV-494
    it(`Verify Admin user is able to view and access topics of  "Index" page section in "Help"
        pane of Knova Knowledge Central application - [22937089]`, async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:43 GMT

        StepLogger.caseId = 22937089;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelp();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "Help" pane as specified in the Precondition [C22937006]');
        await KnowledgeCentralHomePageHelper.clickHelp();
        StepLogger.verification('"KNOVA KNOWLEDGE CENTRAL HELP" window should get displayed');
        await KnowledgeCentralHomePageHelper.verifyHelpPane();

        StepLogger.stepId(2);
        StepLogger.step('Click on "Index" page section');
        await KnowledgeCentralHomePageHelper.clickIndex();
        StepLogger.verification('User should get navigated to "Index" page section');
        await KnowledgeCentralHomePageHelper.verifyIndexSection();

        StepLogger.stepId(3);
        StepLogger.step('Randomly click on any topic Ex : "Access Levels"');
        await KnowledgeCentralHomePageHelper.clickIndexOption(KnowledgeCentralHomePage.helpPane.accessLevels);
        StepLogger.verification('User should get navigated to the respective topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.accessLevelsTitle);

        StepLogger.stepId(4);
        StepLogger.step('Repeat the above step for other topics and verify user is able to navigate to the selected topics');
        await KnowledgeCentralHomePageHelper.clickIndexOption(KnowledgeCentralHomePage.helpPane.alerts);
        StepLogger.verification('User should be able to navigate to selected topics successfully without errors');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.alertsTitle);

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });

    // Jira References - KNOV-494
    it('Verify Admin user is able to perform search on a selected topic page of "Index" page section in Settings>Help pane - [22937096]', async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:43 GMT

        StepLogger.caseId = 22937096;
        const access = KnowledgeCentralHomePageConstant.elementNames.access;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelp();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "Help" pane as specified in the Precondition [C22937006]');
        await KnowledgeCentralHomePageHelper.clickHelp();
        StepLogger.verification('"KNOVA KNOWLEDGE CENTRAL HELP" window should get displayed');
        await KnowledgeCentralHomePageHelper.verifyHelpPane();

        StepLogger.stepId(2);
        StepLogger.step('Click on "Index" page section');
        await KnowledgeCentralHomePageHelper.clickIndex();
        StepLogger.verification('User should get navigated to "Index" page section');
        await KnowledgeCentralHomePageHelper.verifyIndexSection();

        StepLogger.stepId(3);
        StepLogger.step('Randomly click on any topic Ex : "Access Levels"');
        await KnowledgeCentralHomePageHelper.clickIndexOption(KnowledgeCentralHomePage.helpPane.accessLevels);
        StepLogger.verification('User should get navigated to the respective topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.accessLevelsTitle);

        StepLogger.stepId(4);
        StepLogger.step('Observe that at the top of the page a free text search field is available with magnifying glass');
        StepLogger.verification('Search this topic free text field should be available with magnifying glass');
        await KnowledgeCentralHomePageHelper.verifySearchBox();

        StepLogger.stepId(5);
        StepLogger.step('Enter Text Ex: User in the free text search field and click on magnifying glass');
        await KnowledgeCentralHomePageHelper.enterTextInSearchBoxAndClickSearch(access);
        StepLogger.verification('The Search results should be displayed and highlighted in the topic page');
        await KnowledgeCentralHomePageHelper.verifyHighlightedResult(access);

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });

    // Jira References - KNOV-494
    it(`Verify Admin user is able to navigate back to the previous topic from current topic by selecting the "Back"
        button in the current topic page of "Index" page section - [22937125]`, async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:47 GMT

        StepLogger.caseId = 22937125;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelp();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "Help" pane as specified in the Precondition [C22937006]');
        await KnowledgeCentralHomePageHelper.clickHelp();
        StepLogger.verification('"KNOVA KNOWLEDGE CENTRAL HELP" window should get displayed');
        await KnowledgeCentralHomePageHelper.verifyHelpPane();

        StepLogger.stepId(2);
        StepLogger.step('Click on "Index" page section');
        await KnowledgeCentralHomePageHelper.clickIndex();
        StepLogger.verification('User should get navigated to "Index" page section');
        await KnowledgeCentralHomePageHelper.verifyIndexSection();

        StepLogger.stepId(3);
        StepLogger.step('Randomly click on any topic Ex : "Access Levels"');
        await KnowledgeCentralHomePageHelper.clickIndexOption(KnowledgeCentralHomePage.helpPane.accessLevels);
        StepLogger.verification('User should get navigated to the respective topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.accessLevelsTitle);

        StepLogger.stepId(4);
        StepLogger.step('Now select an other topic Ex : "alerts"');
        await KnowledgeCentralHomePageHelper.clickIndexOption(KnowledgeCentralHomePage.helpPane.alerts);
        StepLogger.verification('User should get navigated to the  "alerts" topic page');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.alertsTitle);

        StepLogger.stepId(5);
        StepLogger.step('Click on "Back" button in the "alerts" topic page');
        await KnowledgeCentralHomePageHelper.clickBack();
        StepLogger.verification('User should get navigated to his previous topic  "Access Levels"');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.accessLevelsTitle);

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });

    // Jira References - KNOV-494
    it('Verify admin user is able to perform search for a topic in the free text search field of  Index page section - [22937160]', async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 06:30:47 GMT

        StepLogger.caseId = 22937160;
        const accessLevels = KnowledgeCentralHomePageConstant.elementNames.accessLevels;
        StepLogger.preCondition('Execute C22937006 : Admin User accessing Settings>Help pane');
        await KnowledgeCentralHomePageHelper.navigateToHelp();

        StepLogger.stepId(1);
        StepLogger.step('Click on the "Help" pane as specified in the Precondition [C22937006]');
        await KnowledgeCentralHomePageHelper.clickHelp();
        StepLogger.verification('"KNOVA KNOWLEDGE CENTRAL HELP" window should get displayed');
        await KnowledgeCentralHomePageHelper.verifyHelpPane();

        StepLogger.stepId(2);
        StepLogger.step('Click on "Index" page section');
        await KnowledgeCentralHomePageHelper.clickIndex();
        StepLogger.verification('User should get navigated to "Index" page section');
        await KnowledgeCentralHomePageHelper.verifyIndexSection();

        StepLogger.stepId(3);
        StepLogger.step('Enter search text Ex: Case in the free text search field below the "Index" heading in the left pane');
        await KnowledgeCentralHomePageHelper.enterTextInIndexSearchField(accessLevels);
        StepLogger.verification('Index section displays the searched text results at the top in the left pane');
        await KnowledgeCentralHomePageHelper.verifySearchedIndexOption(KnowledgeCentralHomePage.helpPane.accessLevels);

        StepLogger.stepId(4);
        StepLogger.step('Click on the searched topic page');
        await KnowledgeCentralHomePageHelper.clickIndexOption(KnowledgeCentralHomePage.helpPane.accessLevels);
        StepLogger.verification('User should get navigated to the searched topic page successfully');
        await KnowledgeCentralHomePageHelper.verifyTocPage(KnowledgeCentralHomePage.helpPane.accessLevelsTitle);

        StepLogger.postCondition('Logout');
        await KnowledgeCentralHomePageHelper.switchToFirstTabAndLogOut();
    });
});
