import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { Constants } from '../../../components/misc-utils/constants';
import { AdminLoginPageHelper } from '../../../page-objects/pages/admin-login-page/admin-login.helper';
import { ContentAlertManagerConstant } from '../../../page-objects/pages/manage-communities/content-alert-manager/content-alert-manager.constants';
import { ContentAlertManagerHelper } from '../../../page-objects/pages/manage-communities/content-alert-manager/content-alert-manager.helper';
import { ContentAlertManagerPage } from '../../../page-objects/pages/manage-communities/content-alert-manager/content-alert-manager.po';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: AdminLoginPageHelper;
    const textArea = ContentAlertManagerConstant.textArea;
    const buttons = ContentAlertManagerPage.buttons;

    beforeAll(async () => {
        loginPageHelper = AdminLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        await loginPageHelper.goTo();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await AdminLoginPageHelper.loginAsAdmin();
    });

    // Jira References - KNOV-753
    it(`To verify the error message when input field is left blank and Add is clicked for automatic rejection-
        Exact match/Partial match. - [22336300]`, async () => {
        // Auto generated by aurea-automation - util on Thu, 21 Feb 2019 09:17:55 GMT
        StepLogger.caseId = 22336300;

        StepLogger.preCondition('Access the content alert manager section');
        await ContentAlertManagerHelper.navigateToContentAlertManager();

        StepLogger.stepId(1);
        StepLogger.step(`Go to automatic rejection-exact match section.
        Leave the field blank and click on Add.`);
        await ContentAlertManagerHelper.addWord(textArea.level1Exact, buttons.addLevel1Exact, Constants.EMPTY_STRING);
        StepLogger.verification('An error message should be displayed.');
        await ContentAlertManagerHelper.verifyBlankErrorWindow();

        StepLogger.stepId(2);
        StepLogger.step('Click on OK');
        await ContentAlertManagerHelper.closeErrorWindow();
        StepLogger.verification('The error message should be closed.');
        await ContentAlertManagerHelper.verifyErrorWindowClosed();

        StepLogger.stepId(3);
        StepLogger.step(`Go to automatic rejection-partial match section.
        Leave the field blank and click on Add.`);
        await ContentAlertManagerHelper.addWord(textArea.level1Partial, buttons.addLevel1Partial, Constants.EMPTY_STRING);
        StepLogger.verification('An error message should be displayed.');
        await ContentAlertManagerHelper.verifyBlankErrorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Click on OK');
        await ContentAlertManagerHelper.closeErrorWindow();
        StepLogger.verification('The error message should be closed.');
        await ContentAlertManagerHelper.verifyErrorWindowClosed();

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-754
    it(`To verify the error message when input field is left blank and Add is clicked for high alert-
        Exact match/Partial match. - [22336326]`, async () => {
        // Auto generated by aurea-automation - util on Thu, 21 Feb 2019 09:17:55 GMT
        StepLogger.caseId = 22336326;

        StepLogger.preCondition('Access the content alert manager section');
        await ContentAlertManagerHelper.navigateToContentAlertManager();

        StepLogger.stepId(1);
        StepLogger.step(`Go to high alert-exact match section.
            Leave the field blank and click on Add.`);
        await ContentAlertManagerHelper.addWord(textArea.level2Exact, buttons.addLevel2Exact, Constants.EMPTY_STRING);
        StepLogger.verification('An error message should be displayed.');
        await ContentAlertManagerHelper.verifyBlankErrorWindow();

        StepLogger.stepId(2);
        StepLogger.step('Click on OK');
        await ContentAlertManagerHelper.closeErrorWindow();
        StepLogger.verification('The error message should be closed.');
        await ContentAlertManagerHelper.verifyErrorWindowClosed();

        StepLogger.stepId(3);
        StepLogger.step(`Go to high alert-partial match section.
        Leave the field blank and click on Add.`);
        await ContentAlertManagerHelper.addWord(textArea.level2Partial, buttons.addLevel2Partial, Constants.EMPTY_STRING);
        StepLogger.verification('An error message should be displayed.');
        await ContentAlertManagerHelper.verifyBlankErrorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Click on OK');
        await ContentAlertManagerHelper.closeErrorWindow();
        StepLogger.verification('The error message should be closed.');
        await ContentAlertManagerHelper.verifyErrorWindowClosed();

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-755
    it(`To verify the error message when input field is left blank and Add is clicked for medium alert-
        Exact match/Partial match. - [22336327]`, async () => {
        // Auto generated by aurea-automation - util on Thu, 21 Feb 2019 09:17:55 GMT
        StepLogger.caseId = 22336327;

        StepLogger.preCondition('Access the content alert manager section');
        await ContentAlertManagerHelper.navigateToContentAlertManager();

        StepLogger.stepId(1);
        StepLogger.step(`Go to medium alert-exact match section.
        Leave the field blank and click on Add.`);
        await ContentAlertManagerHelper.addWord(textArea.level2Exact, buttons.addLevel3Exact, Constants.EMPTY_STRING);
        StepLogger.verification('An error message should be displayed.');
        await ContentAlertManagerHelper.verifyBlankErrorWindow();

        StepLogger.stepId(2);
        StepLogger.step('Click on OK');
        await ContentAlertManagerHelper.closeErrorWindow();
        StepLogger.verification('The error message should be closed.');
        await ContentAlertManagerHelper.verifyErrorWindowClosed();

        StepLogger.stepId(3);
        StepLogger.step(`Go to medium alert-partial match section.
        Leave the field blank and click on Add.`);
        await ContentAlertManagerHelper.addWord(textArea.level3Partial, buttons.addLevel3Partial, Constants.EMPTY_STRING);
        StepLogger.verification('An error message should be displayed.');
        await ContentAlertManagerHelper.verifyBlankErrorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Click on OK');
        await ContentAlertManagerHelper.closeErrorWindow();
        StepLogger.verification('The error message should be closed.');
        await ContentAlertManagerHelper.verifyErrorWindowClosed();

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-868
    it(`To verify the error message when delete button is clicked without selecting any value from the list for automatic rejection-
        Exact match/Partial match. - [22336371]`, async () => {
        // Auto generated by aurea-automation - util on Thu, 21 Feb 2019 09:17:55 GMT
        StepLogger.caseId = 22336371;

        StepLogger.preCondition('Access the content alert manager section');
        await ContentAlertManagerHelper.navigateToContentAlertManager();

        StepLogger.stepId(1);
        StepLogger.step(`Go to automatic rejection-exact match section.
        Don't select any value from the list and click on delete button.`);
        await buttons.deleteLevel1Exact.clickButton();
        StepLogger.verification('An error message should be displayed.');
        await ContentAlertManagerHelper.verifyNoneDeletedErrorWindow();

        StepLogger.stepId(2);
        StepLogger.step('Click on OK');
        await ContentAlertManagerHelper.closeErrorWindow();
        StepLogger.verification('The error message should be closed.');
        await ContentAlertManagerHelper.verifyErrorWindowClosed();

        StepLogger.stepId(3);
        StepLogger.step(`Go to automatic rejection-partial match section.
            Don't select any value from the list and click on delete button.`);
        await buttons.deleteLevel1Partial.clickButton();
        StepLogger.verification('An error message should be displayed.');
        await ContentAlertManagerHelper.verifyNoneDeletedErrorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Click on OK');
        await ContentAlertManagerHelper.closeErrorWindow();
        StepLogger.verification('The error message should be closed.');
        await ContentAlertManagerHelper.verifyErrorWindowClosed();

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-869
    it(`To verify the error message when delete button is clicked without selecting any value from the list for high alert-
        Exact match/Partial match. - [22336377]`, async () => {
        // Auto generated by aurea-automation - util on Thu, 21 Feb 2019 09:17:55 GMT
        StepLogger.caseId = 22336377;

        StepLogger.preCondition('Access the content alert manager section');
        await ContentAlertManagerHelper.navigateToContentAlertManager();

        StepLogger.stepId(1);
        StepLogger.step(`Go to high alert-exact match section.
            Don't select any value from the list and click on delete button.`);
        await buttons.deleteLevel2Exact.clickButton();
        StepLogger.verification('An error message should be displayed.');
        await ContentAlertManagerHelper.verifyNoneDeletedErrorWindow();

        StepLogger.stepId(2);
        StepLogger.step('Click on OK');
        await ContentAlertManagerHelper.closeErrorWindow();
        StepLogger.verification('The error message should be closed.');
        await ContentAlertManagerHelper.verifyErrorWindowClosed();

        StepLogger.stepId(3);
        StepLogger.step(`Go to high alert-partial match section.
            Don't select any value from the list and click on delete button.`);
        await buttons.deleteLevel2Partial.clickButton();
        StepLogger.verification('An error message should be displayed.');
        await ContentAlertManagerHelper.verifyNoneDeletedErrorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Click on OK');
        await ContentAlertManagerHelper.closeErrorWindow();
        StepLogger.verification('The error message should be closed.');
        await ContentAlertManagerHelper.verifyErrorWindowClosed();

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-870
    it(`To verify the error message when delete button is clicked without selecting any value from the list for medium alert-
        Exact match/Partial match. - [22336378]`, async () => {
        // Auto generated by aurea-automation - util on Thu, 21 Feb 2019 09:17:55 GMT
        StepLogger.caseId = 22336378;

        StepLogger.preCondition('Access the content alert manager section');
        await ContentAlertManagerHelper.navigateToContentAlertManager();

        StepLogger.stepId(1);
        StepLogger.step(`Go to medium alert-exact match section.
            Don't select any value from the list and click on delete button.`);
        await buttons.deleteLevel3Exact.clickButton();
        StepLogger.verification('An error message should be displayed.');
        await ContentAlertManagerHelper.verifyNoneDeletedErrorWindow();

        StepLogger.stepId(2);
        StepLogger.step('Click on OK');
        await ContentAlertManagerHelper.closeErrorWindow();
        StepLogger.verification('The error message should be closed.');
        await ContentAlertManagerHelper.verifyErrorWindowClosed();

        StepLogger.stepId(3);
        StepLogger.step(`Go to medium alert-partial match section.
            Don't select any value from the list and click on delete button.`);
        await buttons.deleteLevel3Partial.clickButton();
        StepLogger.verification('An error message should be displayed.');
        await ContentAlertManagerHelper.verifyNoneDeletedErrorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Click on OK');
        await ContentAlertManagerHelper.closeErrorWindow();
        StepLogger.verification('The error message should be closed.');
        await ContentAlertManagerHelper.verifyErrorWindowClosed();

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });
});
