import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { Constants } from '../../../components/misc-utils/constants';
import { AdminHomePageHelper } from '../../../page-objects/pages/admin-home-page/admin-home.helper';
import { AdminLoginPageHelper } from '../../../page-objects/pages/admin-login-page/admin-login.helper';
import { ContentAccessLevelManagerConstant } from '../../../page-objects/pages/manage-knowledge/knowledge-model/content-access-level-manager.contants';
import { ContentAccessLevelManagerHelper } from '../../../page-objects/pages/manage-knowledge/knowledge-model/content-access-level-manager.helper';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.smokeSuite, () => {
    let loginPageHelper: AdminLoginPageHelper;
    const levels = ContentAccessLevelManagerConstant.levels;
    const random = PageHelper.getUniqueId();
    const levelName = `${ContentAccessLevelManagerConstant.levels.test}${random}`;

    beforeAll(async () => {
        loginPageHelper = AdminLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        await loginPageHelper.goTo();
        await AdminLoginPageHelper.logout();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await AdminLoginPageHelper.loginAsAdmin();
    });

    // Jira References - KNOV-949
    it('To access Content Access Level Manager screen. - [22341184]', async () => {
        // Auto generated by aurea-automation - util on Mon, 25 Feb 2019 07:56:11 GMT
        StepLogger.caseId = 22341184;

        StepLogger.stepId(1);
        StepLogger.step('Click on the options icon (3 lines at the top left corner).');
        await AdminHomePageHelper.clickOnBurgerIcon();
        StepLogger.verification(`The following options should be displayed.
            -Home
            -Manage workbench
            -Manage communities
            -Manage Knowledge
            -Manage People
            -Settings
            -Logout`);
        await AdminHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on Manage Knowledge.');
        await AdminHomePageHelper.clickOnManageKnowledgeMenu();
        StepLogger.verification(`Following 3 options should be displayed.
            -Knowledge Model
            -Knowledge Authoring
            -Knowledge Contribution`);
        await AdminHomePageHelper.verifyManageKnowledgeSubMenu();

        StepLogger.stepId(3);
        StepLogger.step('Click on knowledge model.');
        await AdminHomePageHelper.clickOnKnowledgeModelSubmenu();
        StepLogger.verification('List of options should be displayed.');
        await AdminHomePageHelper.verifyKnowledgeModelSubmenuOptions();

        StepLogger.stepId(4);
        StepLogger.step('Click on Content access Level manager.');
        await AdminHomePageHelper.clickContentAccessLevelManager();
        StepLogger.verification('Content access Level manager page should be displayed with content access levels and select a category sections.');
        await ContentAccessLevelManagerHelper.verifyPageTitle();

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-950
    it('To select the language for which the content levels need to be created. - [22341200]', async () => {
        // Auto generated by aurea-automation - util on Mon, 25 Feb 2019 07:56:07 GMT
        StepLogger.caseId = 22341200;

        StepLogger.preCondition('Access the Content Access Level Manager section.');
        await ContentAccessLevelManagerHelper.navigateToContentAccessLevelManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to the top right section of the page.');
        StepLogger.verification('Language drop down should be displayed.');
        await ContentAccessLevelManagerHelper.verifyLanguagesDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Click on the arrow of the language drop down.');
        await ContentAccessLevelManagerHelper.clickLanguagesDropdown();
        StepLogger.verification('Different language options should be available.');
        await ContentAccessLevelManagerHelper.verifyLanguages();

        StepLogger.stepId(3);
        StepLogger.step('Select one of the languages in which the content levels need to be created.');
        await ContentAccessLevelManagerHelper.selectLanguage(ContentAccessLevelManagerConstant.languageDropdown.english);
        StepLogger.verification('The language should be selected successfully.');
        await ContentAccessLevelManagerHelper.verifySelectedLanguage(ContentAccessLevelManagerConstant.languageDropdown.english);

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-951
    it('To create a new access level. - [22341232]', async () => {
        // Auto generated by aurea-automation - util on Mon, 25 Feb 2019 07:56:11 GMT
        StepLogger.caseId = 22341232;

        StepLogger.preCondition('Access the Content Access Level Manager section.');
        await ContentAccessLevelManagerHelper.navigateToContentAccessLevelManager();

        StepLogger.stepId(1);
        StepLogger.step('Click on the name of the level under which a new level needs to be created.');
        await ContentAccessLevelManagerHelper.selectLevel(levels.internal);
        StepLogger.verification('The selected level name will be displayed next to Category title at the bottom of the page.');
        await ContentAccessLevelManagerHelper.verifySelectedLevel(levels.internal);

        StepLogger.stepId(2);
        StepLogger.step('Click on Add button at the bottom of the page.');
        await ContentAccessLevelManagerHelper.clickAddButton();
        StepLogger.verification('New access level dialog box should be displayed.');
        await ContentAccessLevelManagerHelper.verifyNewAccessDialogDisplayedStatus();

        StepLogger.stepId(3);
        StepLogger.step(`-Provide the new access level name which can include letters, numbers and special characters.
            It should not be more than 80 characters long. -Click on Submit.`);
        await ContentAccessLevelManagerHelper.addNewAccessLevelNameAndSubmit(levelName);
        StepLogger.verification('New access level should be created successfully and displayed in the access levels hierarchy.');
        await ContentAccessLevelManagerHelper.verifyCreatedLevel(levelName);

        StepLogger.postCondition('Delete level and logout');
        await ContentAccessLevelManagerHelper.deleteLevelAndLogout(levelName);
    });

    // Jira References - KNOV-952
    it('To verify the range of the input field in the New access level dialog box. - [22341506]', async () => {
        // Auto generated by aurea-automation - util on Mon, 25 Feb 2019 07:56:11 GMT
        StepLogger.caseId = 22341506;
        const levelNameLarger = `${levelName}${levelName}${levelName}${levelName}${levelName}${levelName}${levelName}${levelName}`;

        StepLogger.preCondition('Access the Content Access Level Manager section.');
        await ContentAccessLevelManagerHelper.navigateToContentAccessLevelManager();

        StepLogger.stepId(1);
        StepLogger.step('Click on the name of the access level under which a new access level needs to be created.');
        await ContentAccessLevelManagerHelper.selectLevel(levels.internal);
        StepLogger.verification('The selected access level name will be displayed next to Category title at the bottom of the page.');
        await ContentAccessLevelManagerHelper.verifySelectedLevel(levels.internal);

        StepLogger.stepId(2);
        StepLogger.step('Click on Add button at the bottom of the page.');
        await ContentAccessLevelManagerHelper.clickAddButton();
        StepLogger.verification('New access level dialog box should be displayed.');
        await ContentAccessLevelManagerHelper.verifyNewAccessDialogDisplayedStatus();

        StepLogger.stepId(3);
        StepLogger.step('- Provide the value in the input field which is more then 80 characters.');
        await ContentAccessLevelManagerHelper.addNewAccessLevelName(levelNameLarger);
        StepLogger.verification('The user should not be able to fill more than 80 characters in the field.');
        await ContentAccessLevelManagerHelper.verifyLevelNameLength();

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-953
    it('To verify the error when the input field is left blank while creating the new access level. - [22341507]', async () => {
        // Auto generated by aurea-automation - util on Mon, 25 Feb 2019 07:56:11 GMT
        StepLogger.caseId = 22341507;

        StepLogger.preCondition('Access the Content Access Level Manager section.');
        await ContentAccessLevelManagerHelper.navigateToContentAccessLevelManager();

        StepLogger.stepId(1);
        StepLogger.step('Click on the name of the access level under which a new access level needs to be created.');
        await ContentAccessLevelManagerHelper.selectLevel(levels.internal);
        StepLogger.verification('The selected access level name will be displayed next to Category title at the bottom of the page.');
        await ContentAccessLevelManagerHelper.verifySelectedLevel(levels.internal);

        StepLogger.stepId(2);
        StepLogger.step('Click on Add button at the bottom of the page.');
        await ContentAccessLevelManagerHelper.clickAddButton();
        StepLogger.verification('New access level dialog box should be displayed.');
        await ContentAccessLevelManagerHelper.verifyNewAccessDialogDisplayedStatus();

        StepLogger.stepId(3);
        StepLogger.step(`-Leave the input field blank.
            -Click on Submit.`);
        await ContentAccessLevelManagerHelper.addNewAccessLevelNameAndSubmit(Constants.EMPTY_STRING);
        StepLogger.verification('An error message should be displayed.');
        await ContentAccessLevelManagerHelper.verifyBlankNameErrorWindow();

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-954
    it('To verify the cancel button in New access level dialog box. - [22341529]', async () => {
        // Auto generated by aurea-automation - util on Mon, 25 Feb 2019 07:56:11 GMT
        StepLogger.caseId = 22341529;

        StepLogger.preCondition('Access the Content Access Level Manager section.');
        await ContentAccessLevelManagerHelper.navigateToContentAccessLevelManager();

        StepLogger.stepId(1);
        StepLogger.step('Click on the name of the access level under which a new access level needs to be created.');
        await ContentAccessLevelManagerHelper.selectLevel(levels.internal);
        StepLogger.verification('The selected access level name will be displayed next to Category title at the bottom of the page.');
        await ContentAccessLevelManagerHelper.verifySelectedLevel(levels.internal);

        StepLogger.stepId(2);
        StepLogger.step('Click on Add button at the bottom of the page.');
        await ContentAccessLevelManagerHelper.clickAddButton();
        StepLogger.verification('New access level dialog box should be displayed.');
        await ContentAccessLevelManagerHelper.verifyNewAccessDialogDisplayedStatus();

        StepLogger.stepId(3);
        StepLogger.step(`-Provide the new access level name which can include letters, numbers and special characters.
            It should not be more than 80 characters long. -Click on Cancel.`);
        await ContentAccessLevelManagerHelper.addNewAccessLevelNameAndCancel(levelName);
        StepLogger.verification('New access level should not be created and content access level page should be displayed.');
        await ContentAccessLevelManagerHelper.verifyLevelNotCreatedAndPage(levelName);

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-955
    it('To verify the error message when a name is provided which already exists while creating a new access level. - [22341540]', async () => {
        // Auto generated by aurea-automation - util on Mon, 25 Feb 2019 07:56:08 GMT
        StepLogger.caseId = 22341540;

        StepLogger.preCondition('Access the Content Access Level Manager section and create level');
        await ContentAccessLevelManagerHelper.navigateToContentAccessLevelManager();
        await ContentAccessLevelManagerHelper.createNewAccessLevelName(levelName);

        StepLogger.stepId(1);
        StepLogger.step('Click on the name of the access level under which a new access level needs to be created.');
        StepLogger.verification('The selected access level name will be displayed next to Category title at the bottom of the page.');
        await ContentAccessLevelManagerHelper.verifySelectedLevel(levels.internal);

        StepLogger.stepId(2);
        StepLogger.step('Click on Add button at the bottom of the page.');
        await ContentAccessLevelManagerHelper.clickAddButton();
        StepLogger.verification('New access level dialog box should be displayed.');
        await ContentAccessLevelManagerHelper.verifyNewAccessDialogDisplayedStatus();

        StepLogger.stepId(3);
        StepLogger.step(`-Provide the new access level name which already exists in the hierarchy.
            -Click on Submit.`);
        await ContentAccessLevelManagerHelper.addNewAccessLevelNameAndSubmit(levelName);
        StepLogger.verification('An error message should be displayed.');
        await ContentAccessLevelManagerHelper.verifyAlreadyExistsErrorWindow();

        StepLogger.postCondition('Delete level and logout');
        await ContentAccessLevelManagerHelper.deleteLevelAndLogout(levelName, true);
    });
});
