import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { Constants } from '../../../components/misc-utils/constants';
import { AdminHomePageHelper } from '../../../page-objects/pages/admin-home-page/admin-home.helper';
import { AdminLoginPageHelper } from '../../../page-objects/pages/admin-login-page/admin-login.helper';
import { ContentAccessLevelManagerConstant } from '../../../page-objects/pages/manage-knowledge/knowledge-model/content-access-level-manager.contants';
import { ContentAccessLevelManagerHelper } from '../../../page-objects/pages/manage-knowledge/knowledge-model/content-access-level-manager.helper';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.smokeSuite, () => {
    let loginPageHelper: AdminLoginPageHelper;
    const levels = ContentAccessLevelManagerConstant.levels;
    const random = PageHelper.getUniqueId();
    const levelName = `${ContentAccessLevelManagerConstant.levels.test}${random}`;

    beforeAll(async () => {
        loginPageHelper = AdminLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        await loginPageHelper.goTo();
        await AdminLoginPageHelper.logout();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await AdminLoginPageHelper.loginAsAdmin();
    });

    // Jira References - KNOV-986
    it('To access Content Access Level Manager screen. - [22344661]', async () => {
        // Auto generated by aurea-automation - util on Tue, 26 Feb 2019 08:57:54 GMT
        StepLogger.caseId = 22344661;

        StepLogger.stepId(1);
        StepLogger.step('Click on the options icon (3 lines at the top left corner).');
        await AdminHomePageHelper.clickOnBurgerIcon();
        StepLogger.verification(`The following options should be displayed.
            -Home
            -Manage workbench
            -Manage communities
            -Manage Knowledge
            -Manage People
            -Settings
            -Logout`);
        await AdminHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on Manage Knowledge.');
        await AdminHomePageHelper.clickOnManageKnowledgeMenu();
        StepLogger.verification(`Following 3 options should be displayed.
            -Knowledge Model
            -Knowledge Authoring
            -Knowledge Contribution`);
        await AdminHomePageHelper.verifyManageKnowledgeSubMenu();

        StepLogger.stepId(3);
        StepLogger.step('Click on knowledge model.');
        await AdminHomePageHelper.clickOnKnowledgeModelSubmenu();
        StepLogger.verification('List of options should be displayed.');
        await AdminHomePageHelper.verifyKnowledgeModelSubmenuOptions();

        StepLogger.stepId(4);
        StepLogger.step('Click on Content access Level manager.');
        await AdminHomePageHelper.clickContentAccessLevelManager();
        StepLogger.verification('Content access Level manager page should be displayed with content access levels and select a category sections.');
        await ContentAccessLevelManagerHelper.verifyPageTitle();

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-987
    it('To rename the Content Access Level. - [22344667]', async () => {
        // Auto generated by aurea-automation - util on Tue, 26 Feb 2019 08:57:55 GMT
        StepLogger.caseId = 22344667;
        const editedLevel = `${levelName}${ContentAccessLevelManagerConstant.levels.edited}`;

        StepLogger.preCondition('Access the Content Access Level Manager section and create level');
        await ContentAccessLevelManagerHelper.navigateToContentAccessLevelManager();
        await ContentAccessLevelManagerHelper.createNewAccessLevelName(levelName);

        StepLogger.stepId(1);
        StepLogger.step('Click on the name of the access level which had to be renamed.');
        await ContentAccessLevelManagerHelper.selectLevel(levelName);
        StepLogger.verification('The selected access level name will be displayed next to Category title at the bottom of the page.');
        await ContentAccessLevelManagerHelper.verifySelectedLevel(levelName);

        StepLogger.stepId(2);
        StepLogger.step('Click on Edit button at the bottom of the page.');
        await ContentAccessLevelManagerHelper.clickEditButton();
        StepLogger.verification('Edit content access level dialog box should be displayed.');
        await ContentAccessLevelManagerHelper.verifyEditDialogDisplayedStatus();

        StepLogger.stepId(3);
        StepLogger.step(`Edit the Name. (Name can include letters, numbers and special characters. It should not be more than 80 characters long.)
            Click on Submit.`);
        await ContentAccessLevelManagerHelper.editLevelNameAndSubmit(editedLevel);
        StepLogger.verification('Access level should be edited successfully and displayed in the access levels hierarchy.');
        await ContentAccessLevelManagerHelper.verifyEditedLevel(editedLevel);

        StepLogger.postCondition('Delete level and logout');
        await ContentAccessLevelManagerHelper.deleteLevelAndLogout(editedLevel);
    });

    // Jira References - KNOV-988
    it('To verify the range of the input field in the Edit Content access level dialog box. - [22344678]', async () => {
        // Auto generated by aurea-automation - util on Tue, 26 Feb 2019 08:57:55 GMT
        StepLogger.caseId = 22344678;
        const levelNameLarger = `${levelName}${levelName}${levelName}${levelName}${levelName}${levelName}${levelName}${levelName}`;

        StepLogger.preCondition('Access the Content Access Level Manager section and create level');
        await ContentAccessLevelManagerHelper.navigateToContentAccessLevelManager();

        StepLogger.stepId(1);
        StepLogger.step('Click on the name of the access level has to be renamed.');
        await ContentAccessLevelManagerHelper.selectLevel(levels.internal);
        StepLogger.verification('The selected access level name will be displayed next to Category title at the bottom of the page.');
        await ContentAccessLevelManagerHelper.verifySelectedLevel(levels.internal);

        StepLogger.stepId(2);
        StepLogger.step('Click on Edit button at the bottom of the page.');
        await ContentAccessLevelManagerHelper.clickEditButton();
        StepLogger.verification('Edit content access level dialog box should be displayed.');
        await ContentAccessLevelManagerHelper.verifyEditDialogDisplayedStatus();

        StepLogger.stepId(3);
        StepLogger.step('Provide the value in the input field which is more then 80 characters.');
        await ContentAccessLevelManagerHelper.editLevelName(levelNameLarger);
        StepLogger.verification('The user should not be able to fill more than 80 characters in the field.');
        await ContentAccessLevelManagerHelper.verifyEditLevelNameLength();

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-989
    it('To verify the error message when the input field is left blank while editing the access level. - [22344679]', async () => {
        // Auto generated by aurea-automation - util on Tue, 26 Feb 2019 08:57:54 GMT
        StepLogger.caseId = 22344679;

        StepLogger.preCondition('Access the Content Access Level Manager section and create level');
        await ContentAccessLevelManagerHelper.navigateToContentAccessLevelManager();

        StepLogger.stepId(1);
        StepLogger.step('Click on the name of the access level which has to be renamed.');
        await ContentAccessLevelManagerHelper.selectLevel(levels.internal);
        StepLogger.verification('The selected access level name will be displayed next to Category title at the bottom of the page.');
        await ContentAccessLevelManagerHelper.verifySelectedLevel(levels.internal);

        StepLogger.stepId(2);
        StepLogger.step('Click on Edit button at the bottom of the page.');
        await ContentAccessLevelManagerHelper.clickEditButton();
        StepLogger.verification('Edit content access level dialog box should be displayed.');
        await ContentAccessLevelManagerHelper.verifyEditDialogDisplayedStatus();

        StepLogger.stepId(3);
        StepLogger.step(`-Leave the input field blank.
            -Click on Submit.`);
        await ContentAccessLevelManagerHelper.editLevelNameAndSubmit(Constants.EMPTY_STRING);
        StepLogger.verification('An error message should be displayed.');
        await ContentAccessLevelManagerHelper.verifyBlankNameErrorWindow();

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-990
    it('To verify the error message when a name is provided which already exists while editing an access level. - [22344680]', async () => {
        // Auto generated by aurea-automation - util on Tue, 26 Feb 2019 08:57:54 GMT
        StepLogger.caseId = 22344680;

        StepLogger.preCondition('Access the Content Access Level Manager section and create level');
        await ContentAccessLevelManagerHelper.navigateToContentAccessLevelManager();
        await ContentAccessLevelManagerHelper.createNewAccessLevelName(levelName);

        StepLogger.stepId(1);
        StepLogger.step('Click on the name of the access level which has to be renamed.');
        await ContentAccessLevelManagerHelper.selectLevel(levelName);
        StepLogger.verification('The selected access level name will be displayed next to Category title at the bottom of the page.');
        await ContentAccessLevelManagerHelper.verifySelectedLevel(levelName);

        StepLogger.stepId(2);
        StepLogger.step('Click on Edit button at the bottom of the page.');
        await ContentAccessLevelManagerHelper.clickEditButton();
        StepLogger.verification('Edit content access level dialog box should be displayed.');
        await ContentAccessLevelManagerHelper.verifyEditDialogDisplayedStatus();

        StepLogger.stepId(3);
        StepLogger.step(`-Provide the access level name which already exists in the hierarchy.
            -Click on Submit.`);
        await ContentAccessLevelManagerHelper.editLevelNameAndSubmit(levels.internal);
        StepLogger.verification('An error message should be displayed.');
        await ContentAccessLevelManagerHelper.verifyAlreadyExistsErrorWindow();

        StepLogger.postCondition('Delete level and logout');
        await ContentAccessLevelManagerHelper.deleteLevelAndLogout(levelName, true, false);
    });

    // Jira References - KNOV-991
    it('To verify the cancel button in Edit content access level dialog box. - [22344681]', async () => {
        // Auto generated by aurea-automation - util on Tue, 26 Feb 2019 08:57:55 GMT
        StepLogger.caseId = 22344681;

        StepLogger.preCondition('Access the Content Access Level Manager section and create level');
        await ContentAccessLevelManagerHelper.navigateToContentAccessLevelManager();

        StepLogger.stepId(1);
        StepLogger.step('Click on the name of the access level which has to be renamed.');
        await ContentAccessLevelManagerHelper.selectLevel(levels.internal);
        StepLogger.verification('The selected access level name will be displayed next to Category title at the bottom of the page.');
        await ContentAccessLevelManagerHelper.verifySelectedLevel(levels.internal);

        StepLogger.stepId(2);
        StepLogger.step('Click on Edit button at the bottom of the page.');
        await ContentAccessLevelManagerHelper.clickEditButton();
        StepLogger.verification('Edit content access level dialog box should be displayed.');
        await ContentAccessLevelManagerHelper.verifyEditDialogDisplayedStatus();

        StepLogger.stepId(3);
        StepLogger.step(`-Provide the updated access level name which can include letters, numbers and special characters.
            It should not be more than 80 characters long. -Click on Cancel.`);
        await ContentAccessLevelManagerHelper.editLevelNameAndCancel(levelName);
        StepLogger.verification('New access level should not be created and content access level page should be displayed.');
        await ContentAccessLevelManagerHelper.verifyLevelNotCreatedAndPage(levelName);

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-992
    it('To delete the Content Access Level. - [22344719]', async () => {
        // Auto generated by aurea-automation - util on Tue, 26 Feb 2019 08:57:55 GMT
        StepLogger.caseId = 22344719;

        StepLogger.preCondition('Access the Content Access Level Manager section and create level');
        await ContentAccessLevelManagerHelper.navigateToContentAccessLevelManager();
        await ContentAccessLevelManagerHelper.createNewAccessLevelName(levelName);

        StepLogger.stepId(1);
        StepLogger.step('Click on the name of the access level which has to be deleted.');
        await ContentAccessLevelManagerHelper.selectLevel(levelName);
        StepLogger.verification('The selected access level name will be displayed next to Category title at the bottom of the page.');
        await ContentAccessLevelManagerHelper.verifySelectedLevel(levelName);

        StepLogger.stepId(2);
        StepLogger.step('Click on Delete button at the bottom of the page.');
        await ContentAccessLevelManagerHelper.clickDeleteButton();
        StepLogger.verification('A confirmation dialog box should be displayed.');
        await ContentAccessLevelManagerHelper.verifyDeleteLevelWindow();

        StepLogger.stepId(3);
        StepLogger.step('Click on Yes');
        await ContentAccessLevelManagerHelper.clickYesButton();
        StepLogger.verification('The access level should be deleted and should not be visible in the hierarchy.');
        await ContentAccessLevelManagerHelper.verifyLevelNotCreatedAndPage(levelName);

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-993
    it('To Cancel deleting the Content Access Level. - [22344727]', async () => {
        // Auto generated by aurea-automation - util on Tue, 26 Feb 2019 08:57:54 GMT
        StepLogger.caseId = 22344727;

        StepLogger.preCondition('Access the Content Access Level Manager section and create level');
        await ContentAccessLevelManagerHelper.navigateToContentAccessLevelManager();

        StepLogger.stepId(1);
        StepLogger.step('Click on the name of the access level which has to be deleted.');
        await ContentAccessLevelManagerHelper.selectLevel(levels.internal);
        StepLogger.verification('The selected access level name will be displayed next to Category title at the bottom of the page.');
        await ContentAccessLevelManagerHelper.verifySelectedLevel(levels.internal);

        StepLogger.stepId(2);
        StepLogger.step('Click on Delete button at the bottom of the page.');
        await ContentAccessLevelManagerHelper.clickDeleteButton();
        StepLogger.verification('A confirmation dialog box should be displayed.');
        await ContentAccessLevelManagerHelper.verifyDeleteLevelWindow();

        StepLogger.stepId(3);
        StepLogger.step('Click on No.');
        await ContentAccessLevelManagerHelper.clickNoButton();
        StepLogger.verification('The access level should be not be deleted and should be visible in the hierarchy.');
        await ContentAccessLevelManagerHelper.verifyLevelNotDeleted(levels.internal);

        StepLogger.postCondition('Logout');
        await AdminLoginPageHelper.logout(true);
    });
});
