import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { Constants } from '../../../components/misc-utils/constants';
import { RandomHelper } from '../../../components/misc-utils/random-helper';
import { AdminHomePageHelper } from '../../../page-objects/pages/admin-home-page/admin-home.helper';
import { AdminHomePage } from '../../../page-objects/pages/admin-home-page/admin-home.po';
import { AdminLoginPageHelper } from '../../../page-objects/pages/admin-login-page/admin-login.helper';
import { UserAndGroupFinderHelper } from '../../../page-objects/pages/manage-people/user-and-group-finder/user-and-group-finder.helper';
import { UserCreatorConstant } from '../../../page-objects/pages/manage-people/user-creator/user-creator.constant';
import { UserCreatorHelper } from '../../../page-objects/pages/manage-people/user-creator/user-creator.helper';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.smokeSuite, () => {
    let loginPageHelper: AdminLoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = AdminLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        await loginPageHelper.goTo();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await AdminLoginPageHelper.logout();
        await AdminLoginPageHelper.loginAsAdmin();
    });

    // Jira References - KNOV-1174
    it('Verify User Creator menu option - [22345084]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Feb 2019 17:51:45 GMT

        StepLogger.caseId = 22345084;
        StepLogger.stepId(1);
        StepLogger.step('Click on the Menu icon.');
        await AdminHomePageHelper.clickOnBurgerIcon();
        StepLogger.verification('The menu list should be opened.');
        await AdminHomePageHelper.verifySideMenuDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on Manage People.');
        await AdminHomePageHelper.clickOnManagePeopleButton();
        StepLogger.verification('The sub menu list should be opened.');
        await AdminHomePageHelper.verifyManagePeopleSubMenu();

        StepLogger.stepId(3);
        StepLogger.step('Verify that the option User Creator should be available.');
        StepLogger.verification('The option User Creator should be available.');
        await AdminHomePage.managePeople.userCreator.verifyDisplayedStatus();

        StepLogger.stepId(4);
        StepLogger.step('Click on User Creator.');
        await AdminHomePageHelper.clickOnUserCreatorOption();
        StepLogger.verification('Profile Editor page should be displayed.');
        await UserCreatorHelper.verifyProfileEditorPageDisplayed();
    });

    // Jira References - KNOV-1175
    it('Verify Create User - [22345113]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Feb 2019 17:51:45 GMT

        StepLogger.caseId = 22345113;
        StepLogger.preCondition('Navigate to Edit profile page');
        await AdminHomePageHelper.navigateToEditProfilePage();

        StepLogger.stepId(1);
        StepLogger.step('Enter Mandatory info like Username, Password, FirstName, LastName, Bio Information and Roles.');
        StepLogger.verification('User should be able to set the mandatory fields.');
        await UserCreatorHelper.typeAndVerifyMandatoryFields();

        StepLogger.stepId(2);
        StepLogger.step('Click Save.');
        await UserCreatorHelper.clickOnSaveButton();
        StepLogger.verification('User Saved Successfully message should be displayed.');
        await UserCreatorHelper.verifyUserCreatedMessage();

        StepLogger.stepId(3);
        StepLogger.step('Click Submit.');
        await UserCreatorHelper.clickOnSubmitButton();
        StepLogger.verification('Welcome page should be displayed.');
        await AdminHomePageHelper.verifyWelcomePage();
    });

    // Jira References - KNOV-1177
    it('Verify User & Group Finder  menu option - [22345153]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Feb 2019 17:51:45 GMT

        StepLogger.caseId = 22345153;
        StepLogger.stepId(1);
        StepLogger.step('Click on the Menu icon.');
        await AdminHomePageHelper.clickOnBurgerIcon();
        StepLogger.verification('The menu list should be opened.');
        await AdminHomePageHelper.verifySideMenuDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on Manage People.');
        await AdminHomePageHelper.clickOnManagePeopleButton();
        StepLogger.verification('The sub menu list should be opened.');
        await AdminHomePageHelper.verifyManagePeopleSubMenu();

        StepLogger.stepId(3);
        StepLogger.step('Verify that the option User & Group Finder should be available.');
        StepLogger.verification('The option User & Group Finder should be available.');
        await AdminHomePage.managePeople.userCreator.verifyDisplayedStatus();
        await AdminHomePage.managePeople.userGroupFinder.verifyDisplayedStatus();

        StepLogger.stepId(4);
        StepLogger.step('Click on User & Group Finder.');
        await AdminHomePageHelper.clickOnUserGroupFinderOption();
        StepLogger.verification('User & Group Finder page should be displayed.');
        await UserAndGroupFinderHelper.verifyUserAndGroupFinderPageDisplayed();
    });

    // Jira References - KNOV-1195
    it('Verify Authoring Controls- Inactive User - [22375988]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Feb 2019 17:51:41 GMT

        StepLogger.caseId = 22375988;
        StepLogger.preCondition('Navigate to Edit Profile page');
        await AdminHomePageHelper.navigateToEditProfilePage();

        StepLogger.stepId(1);
        StepLogger.step('In the Authoring Controls, Verify Inactive User check box is available.');
        StepLogger.verification('In the Authoring Controls, Verify Inactive User check box should be available.');
        await UserCreatorHelper.verifyInactiveUserCheckbox();

        StepLogger.stepId(2);
        StepLogger.step('Check Inactive User check box.');
        await UserCreatorHelper.markInactiveUserCheckbox();
        StepLogger.verification('User should be able to check Inactive User check box.');
        await UserCreatorHelper.verifyInactiveUserCheckboxIsMarked();

        StepLogger.stepId(3);
        StepLogger.step('UnCheck Inactive User check box.');
        await UserCreatorHelper.unmarkInactiveUserCheckbox();
        StepLogger.verification('User should be able to uncheck Inactive User check box.');
        await UserCreatorHelper.verifyInactiveUserCheckboxIsUnmarked();
    });

    // Jira References - KNOV-1186
    it('Verify User Controls - Add User to Group(s) - [22352957]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Feb 2019 17:51:41 GMT

        StepLogger.caseId = 22352957;
        StepLogger.preCondition('Navigate to User and Group Finder page');
        await AdminHomePageHelper.navigateToEditProfilePage();

        // Step 1 is covered in the pre-condition
        StepLogger.stepId(1);
        StepLogger.step('Click on Select for Groups.');
        await UserCreatorHelper.clickOnSelectGroups();
        StepLogger.verification('Select Groups window should be displayed.');
        await UserCreatorHelper.verifySelectGroupsDialogDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click Show All');
        await UserCreatorHelper.clickOnShowAll();
        StepLogger.verification('All available groups should be displayed.');
        await UserCreatorHelper.verifyAvailableGroupsDisplayed();
        const group = await UserCreatorHelper.getARandomAvailableGroupFromTheList();

        StepLogger.stepId(3);
        StepLogger.step('Enter Group name/Author name. click Search.');
        await UserCreatorHelper.typeAGroupNameFromFindGroupsDialogAndClickSearch(group);
        StepLogger.verification('All the groups matching the specified search criteria should be displayed.');
        await UserCreatorHelper.verifyAvailableGroupDisplayed(group);

        StepLogger.stepId(4);
        StepLogger.step('Select groups after doing step 2 and/or Step3. Click OK.');
        await UserCreatorHelper.markDisplayedAvailableGroup();
        await UserCreatorHelper.clickOkButton();
        StepLogger.verification('Select Groups window should be dismissed..');
        await UserCreatorHelper.verifyProfileEditorPageDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Verify the number of groups in Groups section in User controls.');
        StepLogger.verification('The Member of Groups will display the number of groups selected in Select Groups dialog.');
        await UserCreatorHelper.verifyTheSelectedNumberOfGroups(Constants.number.one);
    });

    // Jira References - KNOV-1189
    it('Verify Select Roles - [22353707]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Feb 2019 17:51:41 GMT

        StepLogger.caseId = 22353707;
        StepLogger.preCondition('Navigate to User and Group Finder page and fill in the mandatory fields');
        await AdminHomePageHelper.navigateToEditProfilePage();
        await UserCreatorHelper.typeAndVerifyMandatoryFields();

        StepLogger.stepId(1);
        StepLogger.step('In Roles section, check/Uncheck Roles to grant the user permissions to access Knova applications');
        await UserCreatorHelper.selectRole(UserCreatorConstant.roles.agent);
        StepLogger.verification('User should be able to check/uncheck Roles to grant the user permissions to access Knova applications.');
        await UserCreatorHelper.verifySelectRole(UserCreatorConstant.roles.agent);

        StepLogger.stepId(2);
        StepLogger.step('Click Save.');
        await UserCreatorHelper.clickOnSaveButton();
        StepLogger.verification('The page should be refreshed.');
        // This can't be verified

        StepLogger.stepId(3);
        StepLogger.step('Verify that the selected Roles are saved.');
        StepLogger.verification('The selected Roles should be saved.');
        await UserCreatorHelper.verifySelectRole(UserCreatorConstant.roles.agent);
    });

    // Jira References - KNOV-1192
    it('Verify Authoring Controls- Languages - [22375957]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Feb 2019 17:51:41 GMT

        StepLogger.caseId = 22375957;
        StepLogger.preCondition('Navigate to User and Group Finder page');
        await AdminHomePageHelper.navigateToEditProfilePage();

        StepLogger.stepId(1);
        StepLogger.step('In the Authoring Controls, Click Select for Languages.');
        await UserCreatorHelper.clickOnSelectLanguages();
        StepLogger.verification('Select Languages dialog should be displayed.');
        await UserCreatorHelper.verifySelectLanguagesDialogDisplayed();
        const language = await UserCreatorHelper.getRandomLanguage();

        StepLogger.stepId(2);
        StepLogger.step('Select Languages. Click Right Arrow to Add.');
        await UserCreatorHelper.clickOnAnAvailableLanguageAndClickAddIcon(language);
        StepLogger.verification('Selected Languages should be displayed in the right section.');
        await UserCreatorHelper.verifyIncludedLanguage(language);

        StepLogger.stepId(3);
        StepLogger.step('Select Languages in the right section . Click Left Arrow to remove.');
        await UserCreatorHelper.clickOnAnIncludedLanguageAndClickRemoveIcon(language);
        StepLogger.verification('Removed Languages should be displayed in the left section.');
        await UserCreatorHelper.verifyAvailableLanguage(language);

        StepLogger.stepId(4);
        StepLogger.step('Click OK.');
        await UserCreatorHelper.clickOnAnAvailableLanguageAndClickAddIcon(language);
        await UserCreatorHelper.clickOkButtonFromSelectLanguagesPopup();
        StepLogger.verification(`Select  Languages dialog should be dismissed.
        The selected languages should be displayed in the Authoring controls section.`);
        await UserCreatorHelper.verifySelectedLanguageFromUserProfileDialog(language);
    });

    // Jira References - KNOV-1179
    it('Verify Find User - [22345155]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Feb 2019 17:51:44 GMT

        StepLogger.caseId = 22345155;
        StepLogger.preCondition('Create a user and navigate to User & Group Finder');
        const firstName = RandomHelper.getRandomString();
        await UserAndGroupFinderHelper.createUserAndNavigateToUserAndGroupFider(undefined, undefined, firstName);

        StepLogger.stepId(1);
        StepLogger.step('Enter Search Criteria. e.g First Name.');
        await UserAndGroupFinderHelper.typeFirstName(firstName);
        StepLogger.verification('User should be to enter the search criteria.');
        await UserAndGroupFinderHelper.verifyFirstNameValue(firstName);

        StepLogger.stepId(2);
        StepLogger.step('Click Search.');
        await UserAndGroupFinderHelper.clickOnSearchIcon();
        StepLogger.verification('All Users matching the search criteria should be displayed.');
        await UserAndGroupFinderHelper.verifyUserDisplayedInSearchList(firstName);

        StepLogger.stepId(3);
        StepLogger.step('Click on the user name.');
        await UserAndGroupFinderHelper.ClickOnAUserDisplayedInSearchList(firstName);
        StepLogger.verification('Profile Editor page for that user should be displayed.');
        await UserCreatorHelper.verifyProfileEditorPageDisplayed();
    });

    // Jira References - KNOV-1176
    it('Verify Edit User - [22345152]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Feb 2019 17:51:43 GMT

        StepLogger.caseId = 22345152;
        StepLogger.preCondition('Create a user and search it from User & Group Finder page');
        const firstName = RandomHelper.getRandomString();
        await UserAndGroupFinderHelper.createUserAndFindItByFirstName(undefined, undefined, firstName);

        StepLogger.stepId(1);
        StepLogger.step('Edit any mandatory info like Username, Password, FirstName, LastName, Bio Information and Roles.');
        StepLogger.verification('User should be able to set the mandatory fields.');
        const newName = RandomHelper.getRandomString();
        await UserCreatorHelper.typeAndVerifyFirstName(newName);

        StepLogger.stepId(2);
        StepLogger.step('Click Save.');
        await UserCreatorHelper.clickOnSaveButton();
        StepLogger.verification('User Saved Successfully message should be displayed.');
        await UserCreatorHelper.verifyUserCreatedMessage();

        StepLogger.stepId(3);
        StepLogger.step('Click Submit.');
        await UserCreatorHelper.clickOnSubmitButton();
        StepLogger.verification('Users & Group Finder page should be displayed.');
        await UserAndGroupFinderHelper.verifyUserAndGroupFinderPageDisplayed();
    });

    // Jira References - KNOV-1191
    it('Verify Authoring Controls - Access Levels - [22375933]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Feb 2019 17:51:45 GMT

        StepLogger.caseId = 22375933;
        StepLogger.preCondition('Navigate to User and Group Finder page and fill in the mandatory fields');
        await AdminHomePageHelper.navigateToEditProfilePage();

        StepLogger.stepId(1);
        StepLogger.step('In the Authoring Controls, Click Select for Access Levels.');
        await UserCreatorHelper.clickOnSelectAccessLevelButton();
        StepLogger.verification('Select Access Levels dialog should be displayed.');
        await UserCreatorHelper.verifySelectAccessLevelsDialogDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select Access Levels. Click Add.');
        const level = await UserCreatorHelper.selectAccessLevelAndClickAddButton();
        StepLogger.verification('Selected Access levels should be displayed in the section below.');
        await UserCreatorHelper.verifySelectedAccessLevel(level);

        StepLogger.stepId(3);
        StepLogger.step('Click OK.');
        await UserCreatorHelper.clickOnOkButtonFromAccessLevelsDialog();
        StepLogger.verification(`Select Access Levels dialog should be dismissed.
        The selected Access levels should be displayed in the Authoring controls section.`);
        await UserCreatorHelper.verifySelectedAccessLevelFromEditProfilePage(level);
    });

    // Jira References - KNOV-1193
    it('Verify Authoring Controls- Unified Templates - [22375969]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Feb 2019 17:51:41 GMT

        StepLogger.caseId = 22375969;
        StepLogger.preCondition('Navigate to User and Group Finder page and fill in the mandatory fields');
        await AdminHomePageHelper.navigateToEditProfilePage();

        StepLogger.stepId(1);
        StepLogger.step('In the Authoring Controls, Click Select for Unified Templates.');
        await UserCreatorHelper.clickOnSelectUnfiedTemplateButton();
        StepLogger.verification('Select Unified Templates dialog should be displayed.');
        await UserCreatorHelper.verifySelectUnifiedTemplatesDialogDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Select Unified Templates from Available. Click Right Arrow to Add.');
        const availableTemplate = await UserCreatorHelper.selectAvailableUnifiedTemplatedAndClickAddIcon();
        StepLogger.verification('Selected Unified Templates should be displayed in the right Included section.');
        await UserCreatorHelper.verifyIncludedUnifiedTemplate(availableTemplate);

        StepLogger.stepId(3);
        StepLogger.step('Select Unified Template in the Included section . Click Left Arrow to remove.');
        const includedTemplate = await UserCreatorHelper.selectIncludedUnifiedTemplatedAndClickRemoveIcon();
        StepLogger.verification('Removed Unified Template should be displayed in the left Available .');
        await UserCreatorHelper.verifyAvailableUnifiedTemplate(includedTemplate);

        StepLogger.stepId(4);
        StepLogger.step('Click OK.');
        const template = await UserCreatorHelper.selectAvailableUnifiedTemplatedAndClickAddIcon();
        await UserCreatorHelper.clickOkButtonFromSelectLanguagesPopup();
        StepLogger.verification(`Select  Unified Templates dialog should be dismissed.
        The selected Unified Templates should be displayed in the Authoring controls section.`);
        await UserCreatorHelper.verifySelectedUnifiedTemplatedFromEditProfile(template);
    });

    // Jira References - KNOV-1181
    it('Verify Add Community in Expertise Profile - [22351676]', async () => {
        // Auto generated by aurea-automation - util on Thu, 28 Feb 2019 17:51:42 GMT

        StepLogger.caseId = 22351676;
        StepLogger.preCondition('Navigate to User and Group Finder page and fill in the mandatory fields');
        await AdminHomePageHelper.navigateToEditProfilePage();

        StepLogger.stepId(1);
        StepLogger.step('Click on "Select" button beside the Enterprise Profile label/section');
        await UserCreatorHelper.clickOnSelectExpertiseProfileButton();
        StepLogger.verification('Enterprise profile window should be displayed.');
        await UserCreatorHelper.verifyExpertiseProfileDialogDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click Add Community.');
        await UserCreatorHelper.clickOnAddComunityButton();
        StepLogger.verification('Add Expertise Window should be displayed.');
        await UserCreatorHelper.verifyAddExpertiseDialogDisplayed();

        StepLogger.stepId(3);
        StepLogger.step(`Select Community, Reputation Level.
        Enter short phrases for Skills.
        Select Skill Level.
        Click Ok.`);
        const skill = RandomHelper.getRandomString();
        await UserCreatorHelper.enterComunityReputationLevelAndSkillsInfo(skill);
        StepLogger.verification(`Add Expertise Window should be dismissed.
        Expertise Profile should be displayed.
        The added Community should be displayed.`);
        await UserCreatorHelper.verifyAddedComunityDisplayed(skill);
    });
});
