import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { CredentialsHelper } from '../../../components/misc-utils/credentials-helper';
import { AdminHomePageHelper } from '../../../page-objects/pages/admin-home-page/admin-home.helper';
import { AdminHomePage } from '../../../page-objects/pages/admin-home-page/admin-home.po';
import { AdminLoginPageHelper } from '../../../page-objects/pages/admin-login-page/admin-login.helper';
import { AdminLoginPage } from '../../../page-objects/pages/admin-login-page/admin-login.po';
import { EmailTemplateBuilderPageHelper } from '../../../page-objects/pages/email-template-builder-page/email-template-builder.helper';
import { EmailTemplateBuilderPage } from '../../../page-objects/pages/email-template-builder-page/email-template-builder.po';
import { SuiteNames } from '../../helpers/suite-names';

const { getTextOfElements } = PageHelper;
const { greetingSelections } = EmailTemplateBuilderPage;

describe(SuiteNames.smokeSuite, () => {
    let loginPageHelper: AdminLoginPageHelper;
    const user = CredentialsHelper.admin;
    const random = PageHelper.getUniqueId();

    beforeAll(async () => {
        loginPageHelper = AdminLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        await loginPageHelper.goTo();
        await AdminLoginPageHelper.loginAsAdmin();
        await AdminHomePageHelper.navigateToEmailTemplateBuilderPage();
        await EmailTemplateBuilderPageHelper.deleteTestGreetingSelections();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await AdminLoginPageHelper.logout();
    });

    // Jira References - KNOV-69
    it('Verify that Menu Bar shows Manage workbench along with other options. - [22345078]', async () => {
        // Auto generated by aurea-automation - util on Wed, 13 Feb 2019 20:35:31 GMT

        StepLogger.caseId = 22345078;
        StepLogger.stepId(1);
        StepLogger.step(`Hit the URL of the application.
            Enter the credentials.`);
        await AdminLoginPageHelper.enterUserNameAndPassword(user);
        StepLogger.verification(`Log in page of the application is displayed.
            User is able to enter the credentials.`);
        await AdminLoginPageHelper.verifyEnteredUsernameAndPassword(user);

        StepLogger.stepId(2);
        StepLogger.step('Log in to the application.');
        await AdminLoginPage.loginForm.login.clickButton();
        StepLogger.verification('Administrator page is displayed.');
        await AdminHomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(3);
        StepLogger.step('Click on the lines present at the left hand corner of the screen top menu.');
        await AdminHomePage.hamburgerIcon.clickButton();
        StepLogger.verification('Menu bar options are displayed as present in SS.');
        await AdminHomePageHelper.verifySidebarFieldsDisplayed();
    });

    // Jira References - KNOV-69
    it('Verify the user is able to add a new selection by selecting New . - [22345093]', async () => {
        // Auto generated by aurea-automation - util on Wed, 13 Feb 2019 11:38:04 GMT

        StepLogger.caseId = 22345093;
        StepLogger.preCondition('Logged in to Knova Administrator test environment with admin credentials');
        await AdminLoginPageHelper.loginAsAdmin();
        await AdminHomePage.hamburgerIcon.clickButton();

        StepLogger.stepId(1);
        StepLogger.step('Click on Manage Workbench.');
        await AdminHomePageHelper.clickManageWorkbenchButton();
        StepLogger.verification('options are displayed.');
        await AdminHomePage.manageWorkbench.interviewBuilder.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Hover over the Master Email Template Builder.');
        StepLogger.verification('');
        await AdminHomePage.manageWorkbench.masterEmailTemplateBuilder.hoverOver();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Master Email Template Builder.');
        await AdminHomePage.manageWorkbench.masterEmailTemplateBuilder.clickLink();
        StepLogger.verification('Email template Builder is displayed.');
        await EmailTemplateBuilderPage.contentIFrame.verifyDisplayedStatus();

        StepLogger.stepId(4);
        StepLogger.step('Modify the default subject line .');
        await EmailTemplateBuilderPageHelper.updateSubject(random, true);
        StepLogger.verification('The subject line is updated.');
        await EmailTemplateBuilderPage.subject.verifyTextEntered(random);

        StepLogger.stepId(5);
        StepLogger.step('Click on new button present with Greeting selection.');
        await greetingSelections.new.clickButton();
        StepLogger.verification('A new selection has been added at the bottom section present for Greetings.');
        await EmailTemplateBuilderPageHelper.verifyNewGreetingSelectionIsAdded();

        StepLogger.stepId(6);
        StepLogger.step('Click on new button present with Signature selection.');
        await EmailTemplateBuilderPage.signatureSelections.new.clickButton();
        StepLogger.verification('A new selection is added at the bottom area of the Signature.');
        await EmailTemplateBuilderPageHelper.verifyNewSignatureSelectionIsAdded();
    });

    // Jira References - KNOV-69
    it('Verify by select "Auto–insert this selection" text is inserted into the body of the message automatically. - [22345104]', async () => {
        // Auto generated by aurea-automation - util on Wed, 13 Feb 2019 11:38:06 GMT

        StepLogger.caseId = 22345104;
        StepLogger.preCondition('Logged in to Knova Administrator test environment with admin credentials');
        await AdminLoginPageHelper.loginAsAdmin();
        StepLogger.preCondition('Run the TC C22345093');
        const { greetingId } = await EmailTemplateBuilderPageHelper
            .addNewGreetingAndSignatureSelections();

        StepLogger.stepId(1);
        StepLogger.step('Enter some text in selection text field.');
        await PageHelper.switchToiFrame(EmailTemplateBuilderPage.contentIFrame);
        await greetingSelections.specificGreeting(greetingId).selectionText.sendKeys(random);
        StepLogger.verification('User is able to insert the data in selection text.');
        await greetingSelections.specificGreeting(greetingId).selectionText.verifyTextEntered(random);

        StepLogger.stepId(2);
        StepLogger.step('Tick the check box present with Auto insert this selection.');
        await greetingSelections.specificGreeting(greetingId).autoInsertThisSelection.clickButton();
        StepLogger.verification('The text of the selection  is inserted automatically into the body of the message .');
        await greetingSelections.specificGreeting(greetingId).selectionText.verifyTextEntered(random);

        StepLogger.stepId(3);
        StepLogger.step('--');
        StepLogger.verification('--');
    });

    // Jira References - KNOV-69
    it('Verify after selecting the Reorder ,the list of selections are re ordered. - [22345108]', async () => {
        // Auto generated by aurea-automation - util on Wed, 13 Feb 2019 11:38:06 GMT
        StepLogger.caseId = 22345108;
        StepLogger.preCondition('Logged in to Knova Administrator test environment with admin credentials');
        await AdminLoginPageHelper.loginAsAdmin();
        StepLogger.preCondition('Run the TC C22345093');
        await EmailTemplateBuilderPageHelper.addNewGreetingAndSignatureSelections(true, false);

        StepLogger.stepId(1);
        StepLogger.step('Click on Re order button.');
        const initialOrder = await EmailTemplateBuilderPageHelper.getInitialOrderOfGreetingSelections();
        await greetingSelections.reorder.clickButton();
        StepLogger.verification('Reorder selections pop up is displayed.');
        await EmailTemplateBuilderPageHelper.verifyReorderModalDisplayed(true);

        StepLogger.stepId(2);
        StepLogger.step('Click the arrows upward and downward and reorder the selections.');
        const reorderItemsInitialOrder = await getTextOfElements(EmailTemplateBuilderPage.reorder.allItems);
        await EmailTemplateBuilderPageHelper.moveItemUp(initialOrder[1]);
        StepLogger.verification('The selected item moves upwards or downwards as clicked on arrows.');
        await EmailTemplateBuilderPageHelper.verifyItemsReorderedOnReorderModal(reorderItemsInitialOrder);

        StepLogger.stepId(3);
        StepLogger.step('Click Ok button.');
        await EmailTemplateBuilderPage.reorder.ok.hoverOverAndClick();
        StepLogger.verification('The changes are saved and displayed on screen.');
        await EmailTemplateBuilderPageHelper.verifyGreetingSelectionsIsReordered(initialOrder, true);
    });

    // Jira References - KNOV-69
    it('Verify that email template is configured. - [22345111]', async () => {
        // Auto generated by aurea-automation - util on Wed, 13 Feb 2019 11:38:04 GMT

        StepLogger.caseId = 22345111;
        StepLogger.preCondition('Logged in to Knova Administrator test environment with admin credentials');
        await AdminLoginPageHelper.loginAsAdmin();
        await AdminHomePageHelper.navigateToEmailTemplateBuilderPage();

        StepLogger.stepId(1);
        StepLogger.step(`Verify that Greeting and Signature Selections. are present on this page with 2 buttons.
            New and Reorder`);
        await EmailTemplateBuilderPageHelper.verifyNewAndReorderButtonsOnGreetingSelections(true);
        StepLogger.verification('2 buttons ared displayed with Greeting and Signature selections.');
        await EmailTemplateBuilderPageHelper.verifyNewAndReorderButtonsOnSignatureSelections();

        StepLogger.stepId(2);
        StepLogger.step('Click on New in greeting selection.');
        await greetingSelections.new.clickButton();
        const newGreetingId = await EmailTemplateBuilderPageHelper.getIdOfNewlyAddedGreetingSelection();
        StepLogger.verification('A new selection has been added at the bottom section present for Greeting.');
        await greetingSelections.specificGreeting(newGreetingId).selectionText.verifyDisplayedStatus();

        StepLogger.stepId(3);
        StepLogger.step('Enter some text in Inserted text and selection text.');
        await greetingSelections.specificGreeting(newGreetingId).insertedText.sendKeys(random);
        await greetingSelections.specificGreeting(newGreetingId).selectionText.sendKeys(random);
        StepLogger.verification('User is able to enter text in both the fields.');
        await greetingSelections.specificGreeting(newGreetingId).insertedText.verifyTextEntered(random);
        await greetingSelections.specificGreeting(newGreetingId).selectionText.verifyTextEntered(random);

        StepLogger.stepId(4);
        StepLogger.step('Click on save button.');
        await EmailTemplateBuilderPage.save.clickButton();
        StepLogger.verification('The changes are saved.');
        await greetingSelections.specificGreeting(newGreetingId).autoInsertThisSelection.verifyDisplayedStatus();
    });

    // Jira References - KNOV-69
    it('Verify the error message displayed after leaving blank Greeting selections. - [22345204]', async () => {
        // Auto generated by aurea-automation - util on Wed, 13 Feb 2019 11:38:04 GMT

        StepLogger.caseId = 22345204;
        StepLogger.preCondition('Logged in to Knova Administrator test environment with admin credentials');
        await AdminLoginPageHelper.loginAsAdmin();
        StepLogger.preCondition('Run the TC C22345093');
        const { greetingId } = await EmailTemplateBuilderPageHelper
            .addNewGreetingAndSignatureSelections();

        StepLogger.stepId(1);
        StepLogger.step('Click on save after leaving the selection text field under greeting selection.');
        await EmailTemplateBuilderPageHelper.clearGreetingSelectionTextAndSave(greetingId, true);
        StepLogger.verification('Error message is displayed.');
        await EmailTemplateBuilderPageHelper.verifyGreetingSelectionTextErrorDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on save after leaving the inserted text field under greeting selection.');
        await EmailTemplateBuilderPageHelper.enterGreetingSelectionTextAndSave(greetingId, random, true);
        StepLogger.verification('Error message is displayed.');
        await EmailTemplateBuilderPageHelper.verifyGreetingInsertedTextErrorDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('--');
        StepLogger.verification('--');
    });

    // Jira References - KNOV-69
    it('Verify the error message displayed after leaving blank Signature Selections. - [22345205]', async () => {
        // Auto generated by aurea-automation - util on Wed, 13 Feb 2019 11:38:06 GMT

        StepLogger.caseId = 22345205;
        StepLogger.preCondition('Logged in to Knova Administrator test environment with admin credentials');
        await AdminLoginPageHelper.loginAsAdmin();
        StepLogger.preCondition('Run the TC C22345093');
        const { signatureId } = await EmailTemplateBuilderPageHelper
            .addNewGreetingAndSignatureSelections(false);

        StepLogger.stepId(1);
        StepLogger.step('Click on save after leaving blank  selection text under signature selection(newly added ).');
        await EmailTemplateBuilderPageHelper.clearSignatureSelectionTextAndSave(signatureId, true);
        StepLogger.verification('Error message is displayed.');
        await EmailTemplateBuilderPageHelper.verifySignatureSelectionTextErrorDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on save after leaving blank inserted text under signature selection(newly added ).');
        await EmailTemplateBuilderPageHelper.enterSignatureSelectionTextAndSave(signatureId, random, true);
        StepLogger.verification('Error message is displayed.');
        await EmailTemplateBuilderPageHelper.verifySignatureInsertedTextErrorDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('--');
        StepLogger.verification('--');
    });

    // Jira References - KNOV-69
    it('Verify that if multiple languages are configured then they are displayed in drop down list. - [22345207]', async () => {
        // Auto generated by aurea-automation - util on Wed, 13 Feb 2019 11:38:04 GMT

        StepLogger.caseId = 22345207;
        StepLogger.preCondition('Logged in to Knova Administrator test environment with admin credentials');
        await AdminLoginPageHelper.loginAsAdmin();
        await AdminHomePage.hamburgerIcon.clickButton();

        StepLogger.stepId(1);
        StepLogger.step('Click on Manage Workbench.');
        await AdminHomePage.sidebar.manageWorkbench.hoverOverAndClick();
        StepLogger.verification('options are displayed.');
        await AdminHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on the Master Email Template Builder.');
        await AdminHomePage.manageWorkbench.masterEmailTemplateBuilder.clickLink();
        StepLogger.verification('Email template Builder is displayed.');
        await EmailTemplateBuilderPageHelper.verifyDisplayed(true);

        StepLogger.stepId(3);
        StepLogger.step('Click on the language drop down present at the right hand side of the page.');
        await EmailTemplateBuilderPage.language.dropDown.clickButton();
        StepLogger.verification('All the languages are displayed that are configured.');
        await EmailTemplateBuilderPageHelper.verifyLanguagesDisplayed();
    });
});
