import { StepLogger } from '../../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../../components/html/page-helper';
import { AdminHomePageHelper } from '../../../../../page-objects/pages/admin-home-page/admin-home.helper';
import { AdminLoginPageHelper } from '../../../../../page-objects/pages/admin-login-page/admin-login.helper';
import { ManagePeopleHelper } from '../../../../../page-objects/pages/manage-people/manage-people.helper';
import { ManagePeople1Helper } from '../../../../../page-objects/pages/manage-people/manage-people1.helper';
import { UserAndGroupFinderConstant } from '../../../../../page-objects/pages/manage-people/user-and-group-finder/user-and-group-finder.constant';
import { UserAndGroupFinderHelper } from '../../../../../page-objects/pages/manage-people/user-and-group-finder/user-and-group-finder.helper';
import { UserCreatorHelper } from '../../../../../page-objects/pages/manage-people/user-creator/user-creator.helper';
import { SuiteNames } from '../../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: AdminLoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = AdminLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await AdminLoginPageHelper.logout(true);
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await AdminLoginPageHelper.loginAsAdmin();
    });

    // Jira References - KNOV-2316
    it('Verify User & Group Finder menu option - [22412430]', async () => {
        // Auto generated by chrome - extension on Fri, 26 Apr 2019 07: 54: 18 GMT
        StepLogger.caseId = 22412430;

        StepLogger.stepId(1);
        StepLogger.step('Click on the Menu icon.');
        await AdminHomePageHelper.clickOnBurgerIcon();
        StepLogger.verification('The menu list should be opened.');
        await AdminHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on Manage People.');
        await AdminHomePageHelper.clickOnManagePeopleButton();
        StepLogger.verification('The sub menu list should be opened.');
        await AdminHomePageHelper.verifyManagePeopleSubMenu();

        StepLogger.stepId(3);
        StepLogger.step('Verify that the option User & Group Finder should be available.');
        StepLogger.verification('The option User & Group Finder should be available.');
        await AdminHomePageHelper.verifyUserAndGroupFinderOptionIsAvailable();

        StepLogger.stepId(4);
        StepLogger.step('Click on User & Group Finder.');
        await AdminHomePageHelper.clickOnUserGroupFinderOption();
        StepLogger.verification('User & Group Finder page should be displayed.');
        await ManagePeople1Helper.verifyUserAndGroupFinderPageDisplayed();
    });

    // Jira References - KNOV-2317
    it('Verify Search User(s) by First Name - [22412440]', async () => {
        // Auto generated by chrome-extension on Fri, 26 Apr 2019 07:57:49 GMT
        StepLogger.caseId = 22412440;
        const criteria = UserAndGroupFinderConstant.labels.admin;

        StepLogger.preCondition('Navigate to User and Group Finder');
        await AdminHomePageHelper.navigateToUserAndGroupFinder();

        StepLogger.stepId(1);
        StepLogger.step('Enter a value in First Name.');
        await UserAndGroupFinderHelper.typeFirstName(criteria);
        StepLogger.verification('User should be able to set a value in First Name');
        await UserAndGroupFinderHelper.verifyFirstNameValue(criteria);

        StepLogger.stepId(2);
        StepLogger.step('Select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.clickOnEmployeedApplicationUser();
        StepLogger.verification('User should be able to select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.verifyEmployeedApplicationUser();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Search icon.');
        await UserAndGroupFinderHelper.clickOnSearchIcon();
        StepLogger.verification('All Users matching the First Name in the Employee or Customer Applications as selected.');
        await UserAndGroupFinderHelper.verifyUserDisplayedInSearchList(criteria);

        StepLogger.stepId(4);
        StepLogger.step('Click on the name of a User from the list of Found users.');
        await UserAndGroupFinderHelper.ClickOnAUserDisplayedInSearchList(criteria);
        StepLogger.verification('User Profile page for the selected user should be displayed.');
        await UserCreatorHelper.verifyProfileEditorPageDisplayed();
    });

    // Jira References - KNOV-2318
    it('Verify Search User(s) by Last Name - [22412658]', async () => {
        // Auto generated by chrome-extension on Fri, 26 Apr 2019 08:42:47 GMT
        StepLogger.caseId = 22412658;
        const criteria = UserAndGroupFinderConstant.labels.admin;

        StepLogger.preCondition('Navigate to User and Group Finder');
        await AdminHomePageHelper.navigateToUserAndGroupFinder();

        StepLogger.stepId(1);
        StepLogger.step('Enter a value in Last Name.');
        await UserAndGroupFinderHelper.typeLastName(criteria);
        StepLogger.verification('User should be able to set a value in Last Name');
        await UserAndGroupFinderHelper.verifyLastNameValue(criteria);

        StepLogger.stepId(2);
        StepLogger.step('Select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.clickOnEmployeedApplicationUser();
        StepLogger.verification('User should be able to select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.verifyEmployeedApplicationUser();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Search icon.');
        await UserAndGroupFinderHelper.clickOnSearchIcon();
        StepLogger.verification('All Users matching the Last Name in the Employee or Customer Applications as selected.');
        await UserAndGroupFinderHelper.verifyUserDisplayedInSearchList(criteria);

        StepLogger.stepId(4);
        StepLogger.step('Click on the name of a User from the list of Found users.');
        await UserAndGroupFinderHelper.ClickOnAUserDisplayedInSearchList(criteria);
        StepLogger.verification('User Profile page for the selected user should be displayed.');
        await UserCreatorHelper.verifyProfileEditorPageDisplayed();
    });

    // Jira References - KNOV-2319
    it('Verify Search User(s) by UserName - [22412666]', async () => {
        // Auto generated by chrome - extension on Fri, 26 Apr 2019 08: 50: 13 GMT
        StepLogger.caseId = 22412666;
        const criteria = UserAndGroupFinderConstant.labels.admin;

        StepLogger.preCondition('Navigate to User and Group Finder');
        await AdminHomePageHelper.navigateToUserAndGroupFinder();

        StepLogger.stepId(1);
        StepLogger.step('Enter a value in Username.');
        await UserAndGroupFinderHelper.typeUsername(criteria);
        StepLogger.verification('User should be able to set a value in UserName');
        await UserAndGroupFinderHelper.verifyUsernameValue(criteria);

        StepLogger.stepId(2);
        StepLogger.step('Select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.clickOnEmployeedApplicationUser();
        StepLogger.verification('User should be able to select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.verifyEmployeedApplicationUser();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Search icon.');
        await UserAndGroupFinderHelper.clickOnSearchIcon();
        StepLogger.verification('All Users matching the UserName in the Employee or Customer Applications as selected.');
        await UserAndGroupFinderHelper.verifyUserDisplayedInSearchList(criteria);

        StepLogger.stepId(4);
        StepLogger.step('Click on the name of a User from the list of Found users.');
        await UserAndGroupFinderHelper.ClickOnAUserDisplayedInSearchList(criteria);
        StepLogger.verification('User Profile page for the selected user should be displayed.');
        await UserCreatorHelper.verifyProfileEditorPageDisplayed();
    });

    // Jira References - KNOV-2324
    it('Verify Search User(s) using asterisk(*) - [22412723]', async () => {
        // Auto generated by chrome-extension on Fri, 26 Apr 2019 08:57:18 GMT
        StepLogger.caseId = 22412723;
        const criteria = UserAndGroupFinderConstant.labels.all;

        StepLogger.preCondition('Navigate to User and Group Finder');
        await AdminHomePageHelper.navigateToUserAndGroupFinder();

        StepLogger.stepId(1);
        StepLogger.step('Enter an asterisk in UserName/First Name/Last Name.');
        await UserAndGroupFinderHelper.enterFirsLastUsername(criteria);
        StepLogger.verification('User should be able to set an asterisk in UserName/First Name/Last Name.');
        await UserAndGroupFinderHelper.verifyFirsLastUsername(criteria);

        StepLogger.stepId(2);
        StepLogger.step('Select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.clickOnEmployeedApplicationUser();
        StepLogger.verification('User should be able to select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.verifyEmployeedApplicationUser();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Search icon.');
        await UserAndGroupFinderHelper.clickOnSearchIcon();
        StepLogger.verification('All Available Users in the Employee or Customer Applications as selected should be displayed.');
        await UserAndGroupFinderHelper.verifyAvailableUsers();

        StepLogger.stepId(4);
        StepLogger.step('Click on the name of a User from the list of Found users.');
        await UserAndGroupFinderHelper.clickFirstUserInSearchList();
        StepLogger.verification('User Profile page for the selected user should be displayed.');
        await UserCreatorHelper.verifyProfileEditorPageDisplayed();
    });

    // Jira References - KNOV-2320
    it('Verify Show All for Users - [22412670]', async () => {
        // Auto generated by chrome - extension on Fri, 26 Apr 2019 09: 23: 07 GMT
        StepLogger.caseId = 22412670;

        StepLogger.preCondition('Navigate to User and Group Finder');
        await AdminHomePageHelper.navigateToUserAndGroupFinder();

        StepLogger.stepId(1);
        StepLogger.step('Verify that Show All button should exist');
        StepLogger.verification('Show All button should be available.');
        await UserAndGroupFinderHelper.verifyShowAllButton();

        StepLogger.stepId(2);
        StepLogger.step('Select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.clickOnEmployeedApplicationUser();
        StepLogger.verification('User should be able to select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.verifyEmployeedApplicationUser();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Show All');
        await UserAndGroupFinderHelper.clickShowAll();
        StepLogger.verification('All Users in the Employee or Customer Applications as selected.');
        await UserAndGroupFinderHelper.verifyAvailableUsers();

        StepLogger.stepId(4);
        StepLogger.step('Click on the name of a User from the list of Found users.');
        await UserAndGroupFinderHelper.clickFirstUserInSearchList();
        StepLogger.verification('User Profile page for the selected user should be displayed.');
        await UserCreatorHelper.verifyProfileEditorPageDisplayed();
    });

    // Jira References - KNOV-2326
    it('Verify Search User(s) using combination of First Name, Last Name & Username - [22412735]', async () => {
        // Auto generated by chrome-extension on Fri, 26 Apr 2019 09:47:11 GMT
        StepLogger.caseId = 22412735;
        const criteria = UserAndGroupFinderConstant.labels.admin;

        StepLogger.preCondition('Navigate to User and Group Finder');
        await AdminHomePageHelper.navigateToUserAndGroupFinder();

        StepLogger.stepId(1);
        StepLogger.step('Enter a value in First Name.');
        await UserAndGroupFinderHelper.typeFirstName(criteria);
        StepLogger.verification('User should be able to set a value in First Name');
        await UserAndGroupFinderHelper.verifyFirstNameValue(criteria);

        StepLogger.stepId(2);
        StepLogger.step('Enter a value in UserName.');
        await UserAndGroupFinderHelper.typeUsername(criteria);
        StepLogger.verification('User should be able to set a value in UserName');
        await UserAndGroupFinderHelper.verifyUsernameValue(criteria);

        StepLogger.stepId(3);
        StepLogger.step('Select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.clickOnEmployeedApplicationUser();
        StepLogger.verification('User should be able to select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.verifyEmployeedApplicationUser();

        StepLogger.stepId(4);
        StepLogger.step('Click on the Search icon.');
        await UserAndGroupFinderHelper.clickOnSearchIcon();
        StepLogger.verification('All Users matching the First Name and the UserName in the Employee or Customer Applications as selected.');
        await UserAndGroupFinderHelper.verifyUserDisplayedInSearchList(criteria);

        StepLogger.stepId(5);
        StepLogger.step('Click on the name of a User from the list of Found users.');
        await UserAndGroupFinderHelper.ClickOnAUserDisplayedInSearchList(criteria);
        StepLogger.verification('User Profile page for the selected user should be displayed.');
        await UserCreatorHelper.verifyProfileEditorPageDisplayed();
    });

    // Jira References - KNOV-2321
    it('Verify Search Groups(s) by Group Name - [22412695]', async () => {
        // Auto generated by chrome-extension on Fri, 26 Apr 2019 10:00:54 GMT
        StepLogger.caseId = 22412695;

        StepLogger.preCondition('Navigate to User and Group Finder');
        await AdminHomePageHelper.navigateToUserAndGroupFinder();

        StepLogger.stepId(1);
        StepLogger.step('Enter a value in Group Name.');
        const group = await UserAndGroupFinderHelper.typeGroupName(true);
        StepLogger.verification('User should be able to set a value  in Group Name');
        await UserAndGroupFinderHelper.verifyGroupNameValue(group);

        StepLogger.stepId(2);
        StepLogger.step('Select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.clickOnEmployeedApplicationGroup();
        StepLogger.verification('User should be able to select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.verifyEmployeedApplicationGroup();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Search icon.');
        await UserAndGroupFinderHelper.clickOnSearchIconGroup();
        StepLogger.verification('All Groups matching the Group Name in the Employee or Customer Applications as selected.');
        await UserAndGroupFinderHelper.verifyGroupDisplayedInSearchList(group);

        StepLogger.stepId(4);
        StepLogger.step('Click on the name of a Group from the list of Found groups.');
        await UserAndGroupFinderHelper.clickOnGroupDisplayedInSearchList(group);
        StepLogger.verification('Group creator page for the selected group should be displayed.');
        await ManagePeopleHelper.verifyGroupCreatorPageDisplayed();
    });

    // Jira References - KNOV-2322
    it('Verify Search Groups(s) by Group Owners name - [22412710]', async () => {
        // Auto generated by chrome-extension on Fri, 26 Apr 2019 10:35:53 GMT
        StepLogger.caseId = 22412710;
        const criteria = UserAndGroupFinderConstant.labels.admin;

        StepLogger.preCondition('Navigate to User and Group Finder');
        await AdminHomePageHelper.navigateToUserAndGroupFinder();

        StepLogger.stepId(1);
        StepLogger.step('Enter a value in Owners Name.');
        await UserAndGroupFinderHelper.typeOwnerName(criteria);
        StepLogger.verification('User should be able to set a value in Owners Name');
        await UserAndGroupFinderHelper.verifyOwnerNameValue(criteria);

        StepLogger.stepId(2);
        StepLogger.step('Select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.clickOnEmployeedApplicationGroup();
        StepLogger.verification('User should be able to select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.verifyEmployeedApplicationGroup();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Search icon.');
        await UserAndGroupFinderHelper.clickOnSearchIconGroup();
        StepLogger.verification('All Groups matching the Owners Name in the Employee or Customer Applications as selected are displayed.');
        const group = await UserAndGroupFinderHelper.verifyAvailableGroups();

        StepLogger.stepId(4);
        StepLogger.step('Click on the name of a Group from the list of Found groups.');
        await UserAndGroupFinderHelper.clickOnGroupDisplayedInSearchList(group);
        StepLogger.verification('Group creator page for the selected group should be displayed.');
        await ManagePeopleHelper.verifyGroupCreatorPageDisplayed();
    });

    // Jira References - KNOV-2325
    it('Verify Search Groups(s) using asterisk(*) - [22412733]', async () => {
        // Auto generated by chrome-extension on Fri, 26 Apr 2019 10:48:34 GMT
        StepLogger.caseId = 22412733;
        const criteria = UserAndGroupFinderConstant.labels.all;

        StepLogger.preCondition('Navigate to User and Group Finder');
        await AdminHomePageHelper.navigateToUserAndGroupFinder();

        StepLogger.stepId(1);
        StepLogger.step('Enter an asterisk in Owners Name/Group Name.');
        await UserAndGroupFinderHelper.typeGroupOwnerName(criteria);
        StepLogger.verification('User should be able to set an asterisk in Group Name/Owners name');
        await UserAndGroupFinderHelper.verifyGroupOwnerName(criteria);

        StepLogger.stepId(2);
        StepLogger.step('Select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.clickOnEmployeedApplicationGroup();
        StepLogger.verification('User should be able to select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.verifyEmployeedApplicationGroup();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Search icon.');
        await UserAndGroupFinderHelper.clickOnSearchIconGroup();
        StepLogger.verification('All Available Groups in the Employee or Customer Applications as selected are displayed.');
        const group = await UserAndGroupFinderHelper.verifyAvailableGroups();

        StepLogger.stepId(4);
        StepLogger.step('Click on the name of a Group from the list of Found groups.');
        await UserAndGroupFinderHelper.clickOnGroupDisplayedInSearchList(group);
        StepLogger.verification('Group creator page for the selected group should be displayed.');
        await ManagePeopleHelper.verifyGroupCreatorPageDisplayed();
    });

    // Jira References - KNOV-2323
    it('Verify Show All for Groups(s) - [22412718]', async () => {
        // Auto generated by chrome-extension on Fri, 26 Apr 2019 10:56:49 GMT
        StepLogger.caseId = 22412718;

        StepLogger.preCondition('Navigate to User and Group Finder');
        await AdminHomePageHelper.navigateToUserAndGroupFinder();

        StepLogger.stepId(1);
        StepLogger.step('Verify that Show All button should exist under Groups section.');
        StepLogger.verification('Show All button should be available.');
        await UserAndGroupFinderHelper.verifyShowAllButtonGroup();

        StepLogger.stepId(2);
        StepLogger.step('Select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.clickOnEmployeedApplicationGroup();
        StepLogger.verification('User should be able to select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.verifyEmployeedApplicationGroup();

        StepLogger.stepId(3);
        StepLogger.step('Click on the Show All button');
        await UserAndGroupFinderHelper.clickShowAllGroup();
        StepLogger.verification('All Groups in the Employee or Customer Applications as selected.');
        const group = await UserAndGroupFinderHelper.verifyAvailableGroups();

        StepLogger.stepId(4);
        StepLogger.step('Click on the name of a Group from the list of Found groups.');
        await UserAndGroupFinderHelper.clickOnGroupDisplayedInSearchList(group);
        StepLogger.verification('Group creator page for the selected group should be displayed.');
        await ManagePeopleHelper.verifyGroupCreatorPageDisplayed();
    });

    // Jira References - KNOV-2327
    it('Verify Search Groups(s) using the combination of Group Name & Owners Name - [22412736]', async () => {
        // Auto generated by chrome - extension on Fri, 26 Apr 2019 11: 02: 09 GMT
        StepLogger.caseId = 22412736;
        const criteria = UserAndGroupFinderConstant.labels.admin;

        StepLogger.preCondition('Navigate to User and Group Finder');
        await AdminHomePageHelper.navigateToUserAndGroupFinder();

        StepLogger.stepId(1);
        StepLogger.step('Enter a value in Group Name.');
        const group = await UserAndGroupFinderHelper.typeGroupName(true);
        StepLogger.verification('User should be able to set a value  in Group Name');
        await UserAndGroupFinderHelper.verifyGroupNameValue(group);

        StepLogger.stepId(2);
        StepLogger.step('Enter a value in Owners Name.');
        await UserAndGroupFinderHelper.typeOwnerName(criteria);
        StepLogger.verification('User should be able to set a value  in Owners Name');
        await UserAndGroupFinderHelper.verifyOwnerNameValue(criteria);

        StepLogger.stepId(3);
        StepLogger.step('Select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.clickOnEmployeedApplicationGroup();
        StepLogger.verification('User should be able to select Employee Applications or Customer Applications.');
        await UserAndGroupFinderHelper.verifyEmployeedApplicationGroup();

        StepLogger.stepId(4);
        StepLogger.step('Click on the Search icon.');
        await UserAndGroupFinderHelper.clickOnSearchIconGroup();
        StepLogger.verification(`All Groups matching the Group Name and the Owners Name in the Employee or
            Customer Applications as selected should be displayed.`);
        await UserAndGroupFinderHelper.verifyAvailableGroups();

        StepLogger.stepId(5);
        StepLogger.step('Click on the name of a Group from the list of Found groups.');
        await UserAndGroupFinderHelper.clickOnGroupDisplayedInSearchList(group);
        StepLogger.verification('Group creator page for the selected group should be displayed.');
        await ManagePeopleHelper.verifyGroupCreatorPageDisplayed();
    });
});
