import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { KnowledgeCentralCollaborationConstant } from '../../../page-objects/pages/knowledge-central-collaboration/knowledge-central-collaboration.constant';
import { KnowledgeCentralCollaborationHelper } from '../../../page-objects/pages/knowledge-central-collaboration/knowledge-central-collaboration.helper';
import { KnowledgeCentralHomePageHelper } from '../../../page-objects/pages/knowledge-central-home-page/knowledge-central-home.helper';
import { KnowledgeCentralLoginPageHelper } from '../../../page-objects/pages/knowledge-central-login-page/knowledge-central-login.helper';
import { KnowledgeCentralLoginPage } from '../../../page-objects/pages/knowledge-central-login-page/knowledge-central-login.po';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: KnowledgeCentralLoginPage;

    beforeAll(async () => {
        loginPageHelper = KnowledgeCentralLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await KnowledgeCentralLoginPageHelper.logout();
        await KnowledgeCentralLoginPageHelper.loginAsAdmin();
    });

    it('To verify if user successfully login to Knova Knowledge Central application - [22908494]', async () => {
        // Auto generated by aurea-automation - util on Mon, 29 Apr 2019 05:10:59 GMT

        StepLogger.caseId = 22908494;
        // step 1,2 covered in before Each
        StepLogger.stepId(1);
        StepLogger.step('Open URL : http://10.25.212.11:8080/knowledgecentral/login.do');
        StepLogger.verification('Knova Knowledge Central login page should be displayed');

        StepLogger.stepId(2);
        StepLogger.step('Enter User Name : admin & Password : admin and Click on Login');
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(3);
        StepLogger.step('Verify the home page displayed');
        StepLogger.verification(`Knova Knowledge Central application homepage should be displayed with below:
        1. Menu Button
        2. A Search Bar
        3. Browse: Products
        4. My Favorites - Saved Documents, Saved Searches
        5. Hot Topics
        6. Work in Progress
        7. Answer Wizards
        8. My Subscriptions`);
        await KnowledgeCentralHomePageHelper.verifyHomePageProperties();
    });

    it('To verify if user is navigated to collaboration page when clicked on collaboration menu items - [22908506]', async () => {
        // Auto generated by aurea-automation - util on Mon, 29 Apr 2019 05:25:06 GMT

        StepLogger.caseId = 22908506;
        // step 1 covered in beforeEach
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on menu Bar button available to the LHS top corner');
        await KnowledgeCentralHomePageHelper.clickOnMenuIcon();
        StepLogger.verification(`Menu bar should display below menu items:
        1. Microsites
        2. Case Manager
        3. Collaboration
        4. Content Manager
        5. Settings
        6. Logout`);
        await KnowledgeCentralHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();
    });

    it('To verify the COLLABORATION page displayed - [22908510]', async () => {
        // Auto generated by aurea-automation - util on Mon, 29 Apr 2019 05:35:57 GMT

        StepLogger.caseId = 22908510;
        // step 1 covered in beforeEach
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on menu Bar button available to the LHS top corner');
        await KnowledgeCentralHomePageHelper.clickOnMenuIcon();
        StepLogger.verification(`Menu bar should display below menu items:
        1. Microsites
        2. Case Manager
        3. Collaboration
        4. Content Manager
        5. Settings
        6. Logout`);
        await KnowledgeCentralHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Verify the COLLABORATION page displayed');
        StepLogger.verification(`COLLABORATION page should display below:
        1. New Collaboration button
        2. Existing list of Collaborations create with columns Subject, Originator, Customer, Case ID, Last Update.Delete`);
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageItems();
    });

    it('To verify if Collaboration Builder Pane opens up when clicked on collaboration page - [22908521]', async () => {
        // Auto generated by aurea-automation - util on Mon, 29 Apr 2019 05:46:57 GMT

        StepLogger.caseId = 22908521;
        // step 1 covered in beforeEach
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on menu Bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on collaboration page');
        await KnowledgeCentralCollaborationHelper.clickOnCollaborationBlueLink();
        StepLogger.verification('Collaboration Builder Pane should be opened');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationBuilderWindow();
    });

    it('To verify Collaboration Builder Page displayed - [22908533]', async () => {
        // Auto generated by aurea-automation - util on Mon, 29 Apr 2019 06:13:48 GMT

        StepLogger.caseId = 22908533;
        // step 1 covered in beforeEach
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on Collaboration blue link');
        await KnowledgeCentralCollaborationHelper.clickOnCollaborationBlueLink();
        StepLogger.verification('Collaboration Builder Page should be displayed when clicked on collaboration');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationBuilderWindow();

        StepLogger.stepId(4);
        StepLogger.step('Verify Collaboration Builder Page');
        StepLogger.verification(`Collaboration Builder Page should display as below:
        1. Subject
        2. Collaborators
        3. Originator
        4. Message
        5. Post Message
        6. Add Collaborator
        7. Previously created message with user name
        8. Ok & Delete buttons`);
        await KnowledgeCentralCollaborationHelper.verifyCollaborationBuilderItems();
    });

    it('To verify if user is able to cancel deleting collaboration from Collaboration Builder Page - [22909070]', async () => {
        // Auto generated by aurea-automation - util on Mon, 29 Apr 2019 07:14:26 GMT

        StepLogger.caseId = 22909070;
        const message = KnowledgeCentralCollaborationConstant.deleteMessage;

        // step 1 covered in beforeEach
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on Collaboration blue link');
        await KnowledgeCentralCollaborationHelper.clickOnCollaborationBlueLink();
        StepLogger.verification('Collaboration Builder Page should be displayed when clicked on collaboration');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationBuilderWindow();

        StepLogger.stepId(4);
        StepLogger.step('Click on Delete button');
        await KnowledgeCentralCollaborationHelper.clickDeleteOnCollaborationBuilderPage();
        StepLogger.verification('A pop-up window should be displayed with "Are you sure you want to delete this Collaboration? " with OK & Cancel buttons');
        await KnowledgeCentralCollaborationHelper.verifyDeletePopup(message);

        StepLogger.stepId(5);
        StepLogger.step('Click on "No" button');
        await KnowledgeCentralCollaborationHelper.clickNoOnDeletePopup();
        StepLogger.verification('A pop-up window should be closed and user should remain on Collaboration Builder Page');
        await KnowledgeCentralCollaborationHelper.verifyDeletePopupClosed(message);
        await KnowledgeCentralCollaborationHelper.switchToContentIFrame();
        await KnowledgeCentralCollaborationHelper.verifyCollaborationBuilderWindow();
    });

    it('To verify if user is able to cancel deleting collaboration from Collaboration page - [22909097]', async () => {
        // Auto generated by aurea-automation - util on Mon, 29 Apr 2019 16:17:16 GMT

        StepLogger.caseId = 22909097;
        const message = KnowledgeCentralCollaborationConstant.deleteMessage;

        // step 1 covered in beforeEach
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on Delete (X) button');
        await KnowledgeCentralCollaborationHelper.clickDeleteButtonOnCollaborationPage();
        StepLogger.verification('A pop-up window should be displayed with "Are you sure you want to delete this Collaboration? " with Yes & No buttons');
        await KnowledgeCentralCollaborationHelper.verifyDeletePopup(message);

        StepLogger.stepId(4);
        StepLogger.step('Click on "No" button');
        await KnowledgeCentralCollaborationHelper.clickNoOnDeletePopup();
        StepLogger.verification('A pop-up window should be closed and user should remain on Collaboration Page');
        await KnowledgeCentralCollaborationHelper.verifyDeletePopupClosed(message);
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();
    });

    it('To verify if user is able to delete collaboration from Collaboration Page - [22909100]', async () => {
        // Auto generated by aurea-automation - util on Mon, 29 Apr 2019 16:35:03 GMT

        StepLogger.caseId = 22909100;
        const message = KnowledgeCentralCollaborationConstant.deleteMessage;

        // step 1 covered in beforeEach
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on Delete (X) button');
        await KnowledgeCentralCollaborationHelper.clickDeleteButtonOnCollaborationPage();
        StepLogger.verification('A pop-up window should be displayed with "Are you sure you want to delete this Collaboration? " with Yes & No buttons');
        await KnowledgeCentralCollaborationHelper.verifyDeletePopup(message);

        StepLogger.stepId(4);
        StepLogger.step('Click on "Yes" button');
        await KnowledgeCentralCollaborationHelper.clickYesOnDeletePopup();
        StepLogger.verification('Pop-up window should be closed and user should be navigated back to Collaboration page');
        await KnowledgeCentralCollaborationHelper.verifyDeletePopupClosed(message);
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();
    });

    it('To verify if user is able to delete collaboration from Collaboration Builder Page - [22909091]', async () => {
        // Auto generated by aurea-automation - util on Mon, 29 Apr 2019 16:51:59 GMT

        StepLogger.caseId = 22909091;
        const message = KnowledgeCentralCollaborationConstant.deleteMessage;

        // step 1 covered in beforeEach
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on Collaboration blue link');
        await KnowledgeCentralCollaborationHelper.clickOnCollaborationBlueLink();
        StepLogger.verification('Collaboration Builder Page should be displayed when clicked on collaboration');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationBuilderWindow();

        StepLogger.stepId(4);
        StepLogger.step('Click on Delete button');
        await KnowledgeCentralCollaborationHelper.clickDeleteOnCollaborationBuilderPage();
        StepLogger.verification('A pop-up window should be displayed with "Are you sure you want to delete this Collaboration? " with OK & Cancel buttons');
        await KnowledgeCentralCollaborationHelper.verifyDeletePopup(message);

        StepLogger.stepId(5);
        StepLogger.step('Click on "Yes" button');
        await KnowledgeCentralCollaborationHelper.clickYesOnDeletePopup();
        StepLogger.verification('Pop-up window should be closed and user should be navigated back to Collaboration page');
        await KnowledgeCentralCollaborationHelper.verifyDeletePopupClosed(message);
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();
    });
});
