export class UserCreatorConstant {

    static get titles() {
        return {
            profileEditor: 'Profile Editor',
            selectGroups: 'Select Groups',
            selectLanguages: 'Select Languages',
            expertiseProfile: 'Expertise Profile',
            addExpertise: 'Add Expertise',
            selectUniversalMetadata: 'Select Universal Metadata',
            selectAccessLevels: 'Select Access Levels',
            selectUnifiedTemplates: 'Select Unified Templates',
        };
    }

    static get attributes() {
        return {
            name: {
                userName: 'userName',
                password: 'password',
                cpassword: 'cpassword',
                firstName: 'firstName',
                lastName: 'lastName',
                biodata: 'biodata',
                showall: 'showall',
                isActive: 'isActive',
                selectItems: 'selectItems',
                lang: 'lang',
                waccessl: 'waccessl',
                available: 'available',
                included: 'included',
                utempalte: 'utempalte',
                product: 'product',
                erllist: 'erllist',
                skill1: 'skill1',
                level: 'level',
                emailLanguage: 'emailLanguage',
                fullNameFormat: 'fullNameFormat',
                dateFormat: 'dateFormat',
                timeFormat: 'timeFormat',
                itemsPerPage: 'itemsPerPage',
                defaultMicrosite: 'defaultMicrosite',
                numDocsPerPage: 'numDocsPerPage',
                whatsNew: 'whatsNew',
                showThreads: 'showThreads',
                notificationsForm: 'notificationsForm',
                notifyExists: 'notifyExists',
                email: 'email',
                notifyCollaborate: 'notifyCollaborate',
                notifyFeedbackAssigned: 'notifyFeedbackAssigned',
                notifyCaseAvailable: 'notifyCaseAvailable',
            },
            id: {
                saveID: 'saveID',
                submitID: 'submitID',
                memStatus: 'memStatus',
                groupname: 'groupname',
                Image2: 'Image2',
                submitBtn: 'submitBtn',
                groupCount: 'groupCount',
                externalData: 'externalData',
                externalAuth: 'externalAuth',
                addID: 'addID',
                removeID: 'removeID',
                selectedUM: 'selectedUM',
                submitDialogID: 'submitDialogID',
                authAccessLevel: 'authAccessLevel',
                authUTemplates: 'authUTemplates',
                authoringEvents: 'authoringEvents',
                collabEvents: 'collabEvents',
                feedbackEvents: 'feedbackEvents',
                webCaseEvents: 'webCaseEvents',
            },
            value: {
                AddMetadata: 'Add Metadata',
                select: 'Select',
                add: 'Add',
                addCommunity: 'Add Community',
                oK: 'OK',
                expandAll: 'Expand All',
                collapseAll: 'Collapse All',
            },
            class: {
                treediv: 'treediv',
                headerLtBlu: 'headerLtBlu',
            },
        };
    }

    static get names() {
        return {
            userName: 'User name',
            password: 'Password',
            passwordConfirmation: 'Password confrimation',
            firstName: 'First Name',
            lastName: 'Last Name',
            bioInfo: 'Bio Info',
            roleCheckbox: 'Role checkbox',
            saveButton: 'Save',
            userSuccessfullySavedMessage: 'User successfully saved',
            submitButton: 'Submit',
            selectGroupsButton: 'Select groups buttoon',
            showAll: 'Show All',
            inactiveUSer: 'Inactive User',
            availableGroups: 'Available groups',
            groupname: 'Group Name',
            searchIcon: 'Search icon',
            availableGroupCheckbox: 'Available group checkbox',
            okButton: 'OK',
            selectedNumberOfGroups: 'Number of Groups',
            selectLanguages: 'Select Languages',
            selectAccessLevel: 'Select Access Levels',
            dataManagedExternallyForThisUser: 'Data Managed Externally For This User',
            authenticateThisUserExternally: 'Authenticate this User Externally',
            availableLanguages: 'Available languages',
            addIcon: 'Add icon',
            removeIcon: 'Remove icon',
            includedLanguagesList: 'Included languages list',
            selectedLanguageFromUserProfileDialog: 'Selected Language From User Profile Dialog',
            selectManageExpertiseButton: 'Select manage expertise button',
            AddMetadata: 'Add Metadata',
            selectMetadataButton: 'Select Metadata button',
            metadataItem: 'Metadata item',
            selectedUM: 'Selected Universal Metadata',
            accessLevel: 'Access level',
            addButton: 'Add',
            unifiedTemplates: 'Unified templates',
            availableUnifiedTemplates: 'Available Unified templates',
            includedUnifiedTemplates: 'Included Unified templates',
            selectUniversalMetadataButton: 'Select Universal Metadata button',
            addCommunity: 'Add Community',
            selectComunity: 'Select comunity',
            reputationLevel: 'Reputation level',
            skills: 'Skills',
            skillLevel: 'Skill level',
            comunities: 'Communities',
            AllReputationLevels: 'All Reputation Levels',
            tabs: {
                preferences: 'Preferences',
                notifications: 'Notifications',
            },
            resultsPerPage: 'Results Per Page',
            showThreadsInResults: 'Show Threads in Results',
            fullNameFormat: 'Full Name Format',
            authoringEvent: 'Authoring Events',
            collaborationEvent: 'Collaboration Events',
            feedBackEvent: 'Feedback Events',
            webCasesEvent: 'Web Cases Events',
        };
    }

    static get roles() {
        return {
            administrator: 'Administrator',
            agent: 'Agent',
        };
    }

    static get testData() {
        return {
            resultsPerPage: '25',
            whatsNew: '3 days',
            showThreadsInResults: 'Yes',
            criteria: 'admin',
            language: 'English',
            fullNameFormat: 'First Last',
            dateFormat: 'DD-MM-YYYY',
            timeFormat: '12-hour',
            itemsPerPage: 20,
            defaultMicrosite: 'Agent Microsite',
        };
    }
}
