import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { KnowledgeCentralCollaborationHelper } from '../../../page-objects/pages/knowledge-central-collaboration/knowledge-central-collaboration.helper';
import { KnowledgeCentralContentManagerPageHelperExtend } from '../../../page-objects/pages/knowledge-central-content-manager/knowledge-central-content-manager-extend.helper';
import { KnowledgeCentralContentManagerConstant } from '../../../page-objects/pages/knowledge-central-content-manager/knowledge-central-content-manager.constant';
import { KnowledgeCentralContentManagerPageHelper } from '../../../page-objects/pages/knowledge-central-content-manager/knowledge-central-content-manager.helper';
import { KnowledgeCentralHomePageHelper } from '../../../page-objects/pages/knowledge-central-home-page/knowledge-central-home.helper';
import { KnowledgeCentralLoginPageHelper } from '../../../page-objects/pages/knowledge-central-login-page/knowledge-central-login.helper';
import { WorkflowBuilderHelper } from '../../../page-objects/pages/manage-knowledge/knowledge-authoring/workflow-buider.helper';
import { WorkflowBuilderConstant } from '../../../page-objects/pages/manage-knowledge/knowledge-authoring/workflow-builder.constants';
import { KnowledgeReContributionHelper } from '../../../page-objects/pages/manage-knowledge/knowledge-contribution/knowledge-re-contribution.helper';
import { KnowledgeReContributionPage } from '../../../page-objects/pages/manage-knowledge/knowledge-contribution/knowledge-re-contribution.po';
import { ProfileEditorHelper } from '../../../page-objects/pages/profile-editor/profile-editor.helper';
import { CommunitiesPageHelper } from '../../../page-objects/pages/self-service/communities.helper';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: KnowledgeCentralLoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = KnowledgeCentralLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        StepLogger.preCondition('Login and search for random document');
        await loginPageHelper.goTo();
        await KnowledgeCentralLoginPageHelper.loginAsAdmin();
    });

    // Jira References - KNOV-506
    it('Verify admin user is able to access the Content Manager Screen of Knova Knowledge Central application - [23168600]', async () => {
        // Auto generated by aurea-automation - util on Sun, 07 Jul 2019 08:34:31 GMT

        StepLogger.caseId = 23168600;
        StepLogger.stepId(1);
        StepLogger.step('Launch the Knova Knowledge Central with Admin Credentials');
        // Handled in Before all
        StepLogger.verification('Admin User should be able to login to the Knova Knowledge Central successfully');
        await KnowledgeCentralLoginPageHelper.verifyLoginSuccessfully();

        StepLogger.stepId(2);
        StepLogger.step('Click the burger icon from the top left corner of the page.');
        await KnowledgeCentralHomePageHelper.clickOnMenuIcon();
        StepLogger.verification('The vertical menu bar with the available modules and options should be displayed on the left end of the page.');
        await KnowledgeCentralHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click the "Content Manager" tab');
        await KnowledgeCentralHomePageHelper.clickOnContentManagerMenu();
        StepLogger.verification('User should be navigated to the "Content Manager" page with the list of available documents displayed.');
        await KnowledgeCentralContentManagerPageHelper.verifyContentManagerPageDisplayed();
    });

    // Jira References - KNOV-506
    it('Verify admin user is able to view and access the tabs displayed in the Content Manager Screen - [23168601]', async () => {
        // Auto generated by aurea-automation - util on Sun, 07 Jul 2019 09:01:22 GMT

        StepLogger.caseId = 23168601;
        StepLogger.stepId(1);
        StepLogger.step('Admin user navigates to Content Manager Screen as specified in the pre-condition');
        // Handled in Before all
        StepLogger.verification('Admin user should navigated to Content Manager Screen');
        await KnowledgeCentralContentManagerPageHelper.verifyContentManagerPageDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on Tasks tab of Content Manager Screen');
        await KnowledgeCentralContentManagerPageHelper.clickOnTaskTab();
        StepLogger.verification('User should get navigated to the Tasks tab of Content Manager Screen successfully without errors');
        await KnowledgeCentralContentManagerPageHelper.verifyTaskPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on Content Feedback tab of Content Manager Screen');
        await KnowledgeCentralContentManagerPageHelper.clickOnContentFeedbackTab();
        StepLogger.verification('User should get navigated to the Content Feedback tab of Content Manager Screen successfully without errors');
        await KnowledgeCentralContentManagerPageHelper.verifyContentFeedbackPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click on Lifecycle Manager tab of Content Manager Screen');
        await KnowledgeCentralContentManagerPageHelper.clickOnLifeclycleManagerTab();
        StepLogger.verification('User should get navigated to the Lifecycle Manager tab of Content Manager Screen successfully without errors');
        await KnowledgeCentralContentManagerPageHelper.verifyLifecycleManagerPageDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on Locked Document Manager tab of Content Manager Screen');
        await KnowledgeCentralContentManagerPageHelper.clickOnLockedDocumentManagerTab();
        StepLogger.verification('User should get navigated to the Locked Document Manager tab of Content Manager Screen successfully without errors');
        await KnowledgeCentralContentManagerPageHelper.verifyLockedDocumentManagerPageDisplayed();
    });

    // Jira References - KNOV-506
    it('Verify user is able to search for a document in Search Criteria section of Lifecycle Manager tab - [23168602]', async () => {
        // Auto generated by aurea-automation - util on Sun, 07 Jul 2019 09:45:01 GMT

        StepLogger.caseId = 23168602;
        StepLogger.stepId(1);
        StepLogger.step('Admin user navigates to Content Manager Screen as specified in the pre-condition');
        // Handled in Before all
        StepLogger.verification('Admin user should navigated to Content Manager Screen');
        await KnowledgeCentralContentManagerPageHelper.verifyContentManagerPageDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on Lifecycle Manager tab of Content Manager Screen');
        await KnowledgeCentralContentManagerPageHelper.clickOnLifeclycleManagerTab();
        StepLogger.verification('User should get navigated to the Lifecycle Manager tab of Content Manager Screen');
        await KnowledgeCentralContentManagerPageHelper.verifyLifecycleManagerPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('In the Search Criteria section, enter a search criteria in "Enter a new Search" fieldEx: Test');
        await KnowledgeCentralContentManagerPageHelper.enterSearch(WorkflowBuilderConstant.labels.test);
        StepLogger.verification('User should be able to enter search criteria in "Enter a new Search" field');
        await KnowledgeCentralContentManagerPageHelper.getSearchFieldValue(WorkflowBuilderConstant.labels.test);

        StepLogger.stepId(4);
        StepLogger.step('Click on Search button');
        // Handled in verification
        StepLogger.verification('The c Results section should get displayed with results of Search criteria');
        await CommunitiesPageHelper.clickSearchAndVerifyRefresh(false);
    });

    // Jira References - KNOV-506
    it('Verify admin user is able to delete draft document in the Search Results section of Lifecycle Manager tab - [23168603]', async () => {
        // Auto generated by aurea-automation - util on Sun, 07 Jul 2019 10:58:11 GMT

        StepLogger.caseId = 23168603;
        StepLogger.stepId(1);
        StepLogger.step('Admin user performs Search in Search Criteria section of Lifecycle Manager tabas specified in the pre-condition');
        // Handled in verification
        StepLogger.verification('Search Results should get displayed for the criteria searched');
        await CommunitiesPageHelper.clickSearchAndVerifyRefresh(false);

        StepLogger.stepId(2);
        StepLogger.step('Verify Delete Drafts button is visible in the Search Results section');
        // Handled in verification
        StepLogger.verification('Delete Drafts button should be visible in the Search Results section');
        await KnowledgeCentralContentManagerPageHelper.verifyDeleteDraftDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Select a Document having Publication Status as Draft in the Search Results section');
        // Handled in verification
        StepLogger.verification('User should be able to select a document of Publication Status - Draft');
        await KnowledgeCentralContentManagerPageHelper.clickOnResultCheckBoxAndVerify();

        StepLogger.stepId(4);
        StepLogger.step('Now click on Delete Drafts button');
        await KnowledgeCentralContentManagerPageHelper.clickDeleteDraftDisplayed();
        StepLogger.verification('A Webpage message gets displayed"Are you sure you want to delete these Drafts with YES and NO buttons"');
        await KnowledgeCentralContentManagerPageHelperExtend.verifyDeletePopUp();

        StepLogger.stepId(5);
        StepLogger.step('Click Yes for the Webpage message');
        await KnowledgeCentralContentManagerPageHelperExtend.clickDeleteConfirm();
        StepLogger.verification('Deleting Drafts popup message should get displayed "Deleting Drafts is Complete"');
        await KnowledgeCentralContentManagerPageHelperExtend.verifyDeletePopUp();

        StepLogger.stepId(6);
        StepLogger.step('Click OK for the Deleting Drafts popup message');
        await ProfileEditorHelper.clickOk();
        StepLogger.verification('The selected Draft should get deleted successfully without errors');
        await WorkflowBuilderHelper.verifyStateDeleted(WorkflowBuilderConstant.labels.test);
    });

    // Jira References - KNOV-506
    it('Verify admin user is able to delete entire document in the Search Results section of Lifecycle Manager tab - [23168604]', async () => {
        // Auto generated by aurea-automation - util on Sun, 07 Jul 2019 11:48:52 GMT

        StepLogger.caseId = 23168604;
        StepLogger.stepId(1);
        StepLogger.step('Admin user performs Search in Search Criteria section of Lifecycle Manager tab as specified in the pre-condition');
        // Handled in Before all
        StepLogger.verification('Search Results should get displayed for the criteria searched');
        await CommunitiesPageHelper.clickSearchAndVerifyRefresh(false);

        StepLogger.stepId(2);
        StepLogger.step('Verify Delete Entire Doc button is visible in the Search Results section');
        // Handled in verification
        StepLogger.verification('Delete Entire Doc button should be visible in the Search Results section');
        await KnowledgeCentralContentManagerPageHelperExtend.verifyDeleteEntireDocDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Select a Document in the Search Results section to delete');
        // Handled in verification
        StepLogger.verification('User should be able to select a document in the Search Results section');
        await KnowledgeCentralContentManagerPageHelper.clickOnResultCheckBoxAndVerify();

        StepLogger.stepId(4);
        StepLogger.step('Now click on Delete Entire Doc button');
        await KnowledgeCentralContentManagerPageHelperExtend.clickDeleteEntireDoc();
        StepLogger.verification('A Webpage message gets displayed"Are you sure you want to delete these Documents"');
        await KnowledgeCentralContentManagerPageHelperExtend.verifyDeleteEntirePopUp();

        StepLogger.stepId(5);
        StepLogger.step('Click Yes for the Webpage message');
        await KnowledgeCentralContentManagerPageHelperExtend.clickDeleteConfirm();
        StepLogger.verification('Processing message gets displayed "Deleting Documents"Processing 1 of 1Deleting Documents is Complete');
        await KnowledgeCentralContentManagerPageHelperExtend.verifyProcessingPopUp();

        StepLogger.stepId(6);
        StepLogger.step('Click OK for the Deleting Drafts popup message');
        await ProfileEditorHelper.clickOk();
        StepLogger.verification('The selected document should get deleted successfully without errors');
        await WorkflowBuilderHelper.verifyStateDeleted(WorkflowBuilderConstant.labels.test);
    });

    // Jira References - KNOV-506
    it(`Verify click on NO for the Delete Confirmation message does not delete the draft
        document in the Search Results section of Lifecycle Manager tab - [23168611]`, async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Jul 2019 09:16:49 GMT

        StepLogger.caseId = 23168611;
        StepLogger.stepId(1);
        StepLogger.step('Admin user performs Search in Search Criteria section of Lifecycle Manager tab as specified in the pre-condition');
        // Handled in Before all
        StepLogger.verification('Search Results should get displayed for the criteria searched');
        await CommunitiesPageHelper.clickSearchAndVerifyRefresh(false);

        StepLogger.stepId(2);
        StepLogger.step('Select a Document having Publication Status as Draft in the Search Results section');
        // Handled in verification
        StepLogger.verification('User should be able to select a document of Publication Status - Draft');
        await KnowledgeReContributionHelper.selectPublicationStatus(KnowledgeReContributionPage.publicationStatus.draft);

        StepLogger.stepId(3);
        StepLogger.step('Now click on Delete Drafts button');
        await KnowledgeCentralContentManagerPageHelper.clickDeleteDraftDisplayed();
        StepLogger.verification('A Webpage message gets displayed"Are you sure you want to delete these Drafts with YES and NO buttons"');
        await KnowledgeCentralContentManagerPageHelperExtend.verifyDeletePopUp();

        StepLogger.stepId(4);
        StepLogger.step('Click NO for the Webpage message');
        await KnowledgeCentralCollaborationHelper.clickNoOnDeletePopup();
        StepLogger.verification('The selected draft document should not get deleted in the Search Results section of Lifecycle Manager tab');
        await KnowledgeCentralCollaborationHelper.verifyDeletePopupClosed(KnowledgeCentralContentManagerConstant.elementNames.deleteDraftsPopUp);
    });

    // Jira References - KNOV-506
    it(`Verify click on NO for the delete confirmation message does not delete the
        entire document in the Search Results section of Lifecycle Manager tab - [23168612]`, async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Jul 2019 10:18:47 GMT

        StepLogger.caseId = 23168612;
        StepLogger.stepId(1);
        StepLogger.step('Admin user performs Search in Search Criteria section of Lifecycle Manager tab as specified in the pre-condition');
        // Handled in Before all
        StepLogger.verification('Search Results should get displayed for the criteria searched');
        await CommunitiesPageHelper.clickSearchAndVerifyRefresh(false);

        StepLogger.stepId(2);
        StepLogger.step('Select a Document in the Search Results section to delete');
        // Handled in verification
        StepLogger.verification('User should be able to select a document in the Search Results section');
        await KnowledgeCentralContentManagerPageHelper.clickOnResultCheckBoxAndVerify();

        StepLogger.stepId(3);
        StepLogger.step('Now click on Delete Entire Doc button');
        await KnowledgeCentralContentManagerPageHelperExtend.clickDeleteEntireDoc();
        StepLogger.verification('A Webpage message gets displayed"Are you sure you want to delete these Documents"');
        await KnowledgeCentralContentManagerPageHelperExtend.verifyDeleteEntirePopUp();

        StepLogger.stepId(4);
        StepLogger.step('Click NO for the Webpage message');
        await KnowledgeCentralCollaborationHelper.clickNoOnDeletePopup();
        StepLogger.verification('The selected document should not get deleted in the Search Results section of Lifecycle Manager tab');
        await KnowledgeCentralCollaborationHelper.verifyDeletePopupClosed(KnowledgeCentralContentManagerConstant.elementNames.deleteEntirePopUp);
    });
});
