import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { EmailTemplateManagerPageHelper } from '../../../page-objects/pages/administer-system/email-template-manager-page/email-template-manager.helper';
import { LanguageManagementPageConstant } from '../../../page-objects/pages/administer-system/language-management-page/language-management-page.constant';
import { KnowledgeCentralContentManagerPageHelperExtend } from '../../../page-objects/pages/knowledge-central-content-manager/knowledge-central-content-manager-extend.helper';
import { KnowledgeCentralContentManagerConstant } from '../../../page-objects/pages/knowledge-central-content-manager/knowledge-central-content-manager.constant';
import { KnowledgeCentralContentManagerPageHelper } from '../../../page-objects/pages/knowledge-central-content-manager/knowledge-central-content-manager.helper';
import { KnowledgeCentralHomePageHelper } from '../../../page-objects/pages/knowledge-central-home-page/knowledge-central-home.helper';
import { KnowledgeCentralLoginPageHelper } from '../../../page-objects/pages/knowledge-central-login-page/knowledge-central-login.helper';
import { ContentAlertManagerHelper } from '../../../page-objects/pages/manage-communities/content-alert-manager/content-alert-manager.helper';
import { WorkflowBuilderConstant } from '../../../page-objects/pages/manage-knowledge/knowledge-authoring/workflow-builder.constants';
import { KnowledgeModelHelper } from '../../../page-objects/pages/manage-knowledge/knowledge-model/knowledge-model.helper';
import { ManagePeopleHelper } from '../../../page-objects/pages/manage-people/manage-people.helper';
import { ProfileEditorHelper } from '../../../page-objects/pages/profile-editor/profile-editor.helper';
import { SelfServiceModerateWorkbenchPage } from '../../../page-objects/pages/self-service-moderate-workbench/self-service-moderate-workbench.po';
import { AgentMicrositeSelfServiceHelper } from '../../../page-objects/pages/self-service/agent-microsite-tab/agent-microsite.helper';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: KnowledgeCentralLoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = KnowledgeCentralLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        StepLogger.preCondition('Login and search for random document');
        await loginPageHelper.goTo();
        await KnowledgeCentralLoginPageHelper.loginAsAdmin();
    });

    // Jira References - KNOV-507
    it('Verify Admin user is able to view and access the "Content Manager" tab in Knova Knowledge Central application - [23204782]', async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Jul 2019 10:31:56 GMT

        StepLogger.caseId = 23204782;
        StepLogger.stepId(1);
        StepLogger.step('Login to to Knova Knowledge Central with Admin credentials');
        // Handled in Before all
        StepLogger.verification('Admin User should be able to login to the Knova Knowledge Central successfully');
        await KnowledgeCentralLoginPageHelper.verifyLoginSuccessfully();

        StepLogger.stepId(2);
        StepLogger.step('Click the burger icon from the top left corner of the page.');
        await KnowledgeCentralHomePageHelper.clickOnMenuIcon();
        StepLogger.verification('The vertical menu bar with the available modules and options should be displayed on the left end of the page.');
        await KnowledgeCentralHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on "Content Manager" tab');
        await KnowledgeCentralHomePageHelper.clickOnContentManagerMenu();
        StepLogger.verification('User should get navigated to the "Content Manager" tab successfully without errors');
        await KnowledgeCentralContentManagerPageHelper.verifyContentManagerPageDisplayed();
    });

    // Jira References - KNOV-507
    it('Verify the tabs displayed in the Content Manager Screen of Knova Knowledge Central application - [23204783]', async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Jul 2019 10:47:15 GMT

        StepLogger.caseId = 23204783;
        StepLogger.stepId(1);
        StepLogger.step('Click on "Content Manager" tab as specified in the pre-condition');
        // Handled in last case
        StepLogger.verification('User should get navigated to the "Content Manager" tab');
        await KnowledgeCentralContentManagerPageHelper.verifyContentManagerPageDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Verify the tabs displayed in the "Content Manager" tab');
        // Handled in verification
        StepLogger.verification('Below tabs should be displayed in "Content Manager" tab TasksContent FeedbackLifecycle ManagerLocked Document Manager');
        await KnowledgeCentralContentManagerPageHelperExtend.verifyContentManagerTabs();

        StepLogger.stepId(3);
        StepLogger.step('Click on Tasks tab in the Content Manager Screen');
        await KnowledgeCentralContentManagerPageHelper.clickOnTaskTab();
        StepLogger.verification('User should be able to view and access Tasks tab successfully without errors');
        await KnowledgeCentralContentManagerPageHelper.verifyTaskPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Click on Content Feedback tab in the Content Manager Screen');
        await KnowledgeCentralContentManagerPageHelper.clickOnContentFeedbackTab();
        StepLogger.verification('User should be able to view and access Content Feedback tab successfully without errors');
        await KnowledgeCentralContentManagerPageHelper.verifyContentFeedbackPageDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on Lifecycle Manager tab in the Content Manager Screen');
        await KnowledgeCentralContentManagerPageHelper.clickOnLifeclycleManagerTab();
        StepLogger.verification('User should be able to view and access Lifecycle Manager tab successfully without errors');
        await KnowledgeCentralContentManagerPageHelper.verifyLifecycleManagerPageDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Click on Locked Document Manager tab in the Content Manager Screen');
        await KnowledgeCentralContentManagerPageHelper.clickOnLockedDocumentManagerTab();
        StepLogger.verification('User should be able to view and access Locked Document Manager tab successfully without errors');
        await KnowledgeCentralContentManagerPageHelper.verifyLockedDocumentManagerPageDisplayed();
    });

    // Jira References - KNOV-507
    it('Verify click on Select Columns button displays Select Columns Pane in the Content Manager>Life Cycle Manager tab - [23204785]', async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Jul 2019 11:29:59 GMT

        StepLogger.caseId = 23204785;
        StepLogger.stepId(1);
        StepLogger.step('User performs Search in Search Criteria section of Life Cycle Manager tab');
        await KnowledgeCentralContentManagerPageHelper.enterSearch(WorkflowBuilderConstant.labels.test);
        StepLogger.verification('Search Results matching the search criteria should get displayed');
        await KnowledgeCentralContentManagerPageHelper.getSearchFieldValue(WorkflowBuilderConstant.labels.test);

        StepLogger.stepId(2);
        StepLogger.step('Observe Export List, Select Columns, Save View, Print List buttons are displayed in the top right corner of Search Results section');
        // Handled in verification
        StepLogger.verification(`Export List, Select Columns, Save View, Print List buttons
         should be displayed in the top right corner of Search Results section`);
        await KnowledgeCentralContentManagerPageHelper.verifySearchResultsOptionsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on "Select Columns" button');
        await KnowledgeCentralContentManagerPageHelperExtend.clickSelectColumns();
        StepLogger.verification('Select Columns pane should get displayed successfully without errors in the lifeycle manager tab');
        await KnowledgeCentralContentManagerPageHelperExtend.verifySelectColumnPopUp();
    });

    // Jira References - KNOV-507
    it(`Verify user is able to select/unselect columns, move columns upward/downward
        in Select Columns pane of Content Manager>Lifecycle Manager tab - [23204786]`, async () => {
        // Auto generated by aurea-automation - util on Mon, 08 Jul 2019 12:35:01 GMT

        StepLogger.caseId = 23204786;
        StepLogger.stepId(1);
        StepLogger.step('Click Select Columns Button in Search Results section of Lifecycle Manager tab as specified in the pre-condition');
        // Handled in last case
        StepLogger.verification('Select Columns pane should get displayed');
        await KnowledgeCentralContentManagerPageHelperExtend.verifySelectColumnPopUp();

        StepLogger.stepId(2);
        StepLogger.step('Now try to move few columns from left pane to right pane of Select Columns window by using arrow key(-->)');
        await KnowledgeCentralContentManagerPageHelperExtend.clickOnAvailableColumn();
        await ManagePeopleHelper.clickOnPushRightIcon();
        StepLogger.verification('The selected columns should get moved from left pane to right pane of Select Columns window');
        await KnowledgeCentralContentManagerPageHelperExtend.verifySelectedColumnMovedRight();

        StepLogger.stepId(3);
        StepLogger.step('Now move few columns from right pane to left pane of Select Columns window by using arrow key(<--)');
        await KnowledgeCentralContentManagerPageHelperExtend.clickOnAvailableColumn();
        await ManagePeopleHelper.clickOnPushLeftIcon();
        StepLogger.verification('The selected columns should get moved from right pane to left pane of Select Columns window');
        await KnowledgeCentralContentManagerPageHelperExtend.verifySelectedColumnMovedLeft();

        StepLogger.stepId(4);
        StepLogger.step('Now in the right pane of Select Columns window, perform ordering of columns by selecting upward and downward keys');
        await KnowledgeCentralContentManagerPageHelperExtend.clickOnAvailableColumn();
        await AgentMicrositeSelfServiceHelper.clickOnUpwardArrow();
        StepLogger.verification('User should be able to move the columns upward and downward and perform ordering');
        await KnowledgeCentralContentManagerPageHelperExtend.verifyColumnReorder([KnowledgeCentralContentManagerConstant.elementNames.accessLevels]);

        StepLogger.stepId(5);
        StepLogger.step('Now click on OK button in the Select Columns window');
        await ProfileEditorHelper.clickOk();
        StepLogger.verification('Select Columns window should get closed and user is navigated back to Lifecycle Manager tab');
        await KnowledgeCentralContentManagerPageHelper.verifyLifecycleManagerPageDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Verify the order of the columns displayed in Search Results section');
        // Handled in verification
        StepLogger.verification(`Order of the columns displayed in Search Results section should be in
            the same order of the Selected columns in Select Columns pane window`);
        await KnowledgeCentralContentManagerPageHelperExtend.verifyColumnReorder([KnowledgeCentralContentManagerConstant.elementNames.accessLevels]);
    });

    // Jira References - KNOV-507
    it('Verify click on Save View button displays Save View Pane in the Content Manager>Lifecycle Manager tab - [23204788]', async () => {
        // Auto generated by aurea-automation - util on Tue, 09 Jul 2019 09:41:13 GMT

        StepLogger.caseId = 23204788;
        StepLogger.stepId(1);
        StepLogger.step('User performs Search in Search Criteria section of Life Cycle Manager tab');
        await KnowledgeCentralContentManagerPageHelper.enterSearch(WorkflowBuilderConstant.labels.test);
        StepLogger.verification('Search Results matching the search criteria should get displayed');
        await KnowledgeCentralContentManagerPageHelper.getSearchFieldValue(WorkflowBuilderConstant.labels.test);

        StepLogger.stepId(2);
        StepLogger.step('Observe Export List, Select Columns, Save View, Print List buttons are displayed in the top right corner of Search Results section');
        // Handled in verification
        StepLogger.verification(`Export List, Select Columns, Save View, Print List buttons should be displayed
         in the top right corner of Search Results section`);
        await KnowledgeCentralContentManagerPageHelper.verifySearchResultsOptionsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on "Save View" button');
        await KnowledgeCentralContentManagerPageHelperExtend.clickSaveView();
        StepLogger.verification('Save View pane should get displayed successfully without errors');
        await KnowledgeCentralContentManagerPageHelperExtend.saveViewPanel();
    });

    // Jira References - KNOV-507
    it(`Verify user is able to enter details of fields in Save View window
        and save the view in Content Manager>Lifecycle Manager tab - [23204789]`, async () => {
        // Auto generated by aurea-automation - util on Tue, 09 Jul 2019 10:52:03 GMT

        StepLogger.caseId = 23204789;
        StepLogger.stepId(1);
        StepLogger.step('Click Save View button in Search Results section of Lifecycle Manager tab as specified in the precondition');
        // Handled in verification
        StepLogger.verification('Save View window should get displayed');
        await KnowledgeCentralContentManagerPageHelperExtend.saveViewPanel();

        StepLogger.stepId(2);
        StepLogger.step(`Enter values for fields in Save View windowEnglish Name : Test ViewEnglish Description : Test DescriptionCheck
        the Make Public Checkbox Additiona; Names Section:Greek(Example for other language if available)Name : English ViewDescription : English Desc`);
        const name = `${PageHelper.getUniqueId()}Test ViewEnglish`;
        const description = `${PageHelper.getUniqueId()}Test DescriptionCheck`;
        await KnowledgeModelHelper.typeNameAndDescription(name, description);
        await KnowledgeCentralContentManagerPageHelperExtend.markPublicCheckbox();
        await ContentAlertManagerHelper.enterWordInTextArea(SelfServiceModerateWorkbenchPage.elements.toolsSection,
            LanguageManagementPageConstant.languages.english);
        StepLogger.verification('User should be able to enter values for the given fields successfully without errors');
        await KnowledgeModelHelper.verifyNameAndDescription(name, description);
        await KnowledgeCentralContentManagerPageHelperExtend.verifyMarkPublicCheckbox();

        StepLogger.stepId(3);
        StepLogger.step('Now click on Submit button in the Save View pane');
        await EmailTemplateManagerPageHelper.clickOnSubmit();
        StepLogger.verification('The View should get submitted and user gets navigated back to Lifecycle Manager tab');
        await KnowledgeCentralContentManagerPageHelper.verifyLifecycleManagerPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Go to the StepLogger view under Views section displayed in the left pane of Lifecycle Manager tab');
        await KnowledgeCentralContentManagerPageHelperExtend.clickOnNewView(name);
        StepLogger.verification('Newly saved view should get displayed successfully without errors');
        await KnowledgeCentralContentManagerPageHelperExtend.verifySavedViewDisplayed(name);
    });

    // Jira References - KNOV-507
    it(`Verify click on Submit button without entering the English Name field in Save View
        pane throws error message in Save View pane - [23204790]`, async () => {
        // Auto generated by aurea-automation - util on Wed, 10 Jul 2019 07:44:44 GMT

        StepLogger.caseId = 23204790;
        StepLogger.stepId(1);
        StepLogger.step('Click Save View button in Search Results section of Lifecycle Manager tab as specified in the precondition');
        await KnowledgeCentralContentManagerPageHelperExtend.clickSaveView();
        StepLogger.verification('Save View window should get displayed');
        await KnowledgeCentralContentManagerPageHelperExtend.saveViewPanel();

        StepLogger.stepId(2);
        StepLogger.step('Observe "English Name" field is displayed as Mandatory field in Save View pane with symbol beside the field');
        // Handled in verification
        StepLogger.verification('English Name field should be displayed as Mandatory field with symbol');
        await KnowledgeCentralContentManagerPageHelperExtend.verifyEnglishNameDisplayedAsMandatory();

        StepLogger.stepId(3);
        StepLogger.step('Do not enter value for "English Name" field in Save View window and click on Submit button');
        await EmailTemplateManagerPageHelper.clickOnSubmit();
        StepLogger.verification('Error message should get displayed"The following properties cannot be blank : English Name" with OK button');
        await KnowledgeCentralContentManagerPageHelperExtend.errorMessageDisplayedWithOk();
    });
});
