import { browser } from 'protractor';

import { StepLogger } from '../../../core/logger/step-logger';
import { AlertHelper } from '../../components/html/alert-helper';
import { PageHelper } from '../../components/html/page-helper';
import { CredentialsHelper } from '../../components/misc-utils/credentials-helper';
import { KnowledgeCentralHomePageHelper } from '../../page-objects/pages/knowledge-central-home-page/knowledge-central-home.helper';
import {
    KnowledgeCentralHomePage
} from '../../page-objects/pages/knowledge-central-home-page/knowledge-central-home.po';
import {
    KnowledgeCentralLoginPageHelper
} from '../../page-objects/pages/knowledge-central-login-page/knowledge-central-login.helper';
import {
    KnowledgeCentralLoginPage
} from '../../page-objects/pages/knowledge-central-login-page/knowledge-central-login.po';
import { SuiteNames } from '../helpers/suite-names';

describe(SuiteNames.healthCheckSuite, () => {
    let loginPageHelper: KnowledgeCentralLoginPage;
    const user = CredentialsHelper.admin;

    beforeAll(async () => {
        loginPageHelper = KnowledgeCentralLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        await loginPageHelper.goTo();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await KnowledgeCentralLoginPageHelper.logout();
    });

    // Jira References - KNOV-412
    it('Validation of logging to Knova Knowledge Central with valid username and password - [22325181]', async () => {
        // Auto generated by aurea-automation - util on Mon, 18 Feb 2019 21:14:21 GMT
        StepLogger.caseId = 22325181;

        // Step 1 is covered in the beforeAll block
        StepLogger.stepId(1);
        StepLogger.step('Open the IE browser and launch the Knova Knowledge Central application using' +
                        ' http://10.25.212.11:8080/knowledgecentral/login.do link.');
        StepLogger.verification('The Knova Knowledge Central application should be up and running.');

        // Step 2 is covered in step 3
        StepLogger.stepId(2);
        StepLogger.step('Enter valid username in the "USERNAME" field. (e.g, admin)');
        StepLogger.verification('User should be able to enter value in the "USERNAME" field.');

        StepLogger.stepId(3);
        StepLogger.step('Enter valid password in the "PASSWORD" field. (e.g, admin)');
        await KnowledgeCentralLoginPageHelper.enterUserNameAndPassword(user);
        StepLogger.verification('User should be able to enter value in the "PASSWORD" field.');
        await KnowledgeCentralLoginPageHelper.verifyEnteredUsernameAndPassword(user);

        StepLogger.stepId(4);
        StepLogger.step('Click the "LOGIN" button.');
        await KnowledgeCentralLoginPage.loginForm.login.clickButton();
        StepLogger.verification('User should be able to login successfully to the Knova Knowledge Central.');
        await KnowledgeCentralHomePage.hamburgerIcon.verifyDisplayedStatus();

        StepLogger.stepId(5);
        StepLogger.step('Verify that the logged in admin user"s name is displayed at the top right corner of the page.');
        StepLogger.verification('The logged in admin user"s name should be displayed at the top right corner of the page.');
        await KnowledgeCentralHomePageHelper.verifyHeaderBannerDisplayed();
    });

    // Jira References - KNOV-412
    it('Validation of logging to Knova Knowledge Central with invalid username and valid password - [22325533]', async () => {
        // Auto generated by aurea-automation - util on Mon, 18 Feb 2019 23:10:47 GMT
        const invalidUser = await PageHelper.getUniqueId();
        const invalidPassword = await PageHelper.getUniqueId();
        StepLogger.caseId = 22325533;

        // Step 1 is covered in the beforeAll block
        StepLogger.stepId(1);
        StepLogger.step('Open the IE browser and launch the Knova Knowledge Central application using' +
            ' http://10.25.212.11:8080/knowledgecentral/login.do link.');
        StepLogger.verification('The Knova Knowledge Central application should be up and running.');

        StepLogger.stepId(2);
        StepLogger.step('Enter invalid username in the "USERNAME" field. (e.g, track)');
        StepLogger.verification('User should be able to enter value in the "USERNAME" field.');
        await KnowledgeCentralLoginPageHelper.enterAndVerifyUserName(invalidUser);

        StepLogger.stepId(3);
        StepLogger.step('Enter valid admin password in the "PASSWORD" field. (e.g, admin)');
        StepLogger.verification('User should be able to enter value in the "PASSWORD" field.');
        await KnowledgeCentralLoginPageHelper.enterAndVerifyPassword(invalidPassword);

        StepLogger.stepId(4);
        StepLogger.step('Click the "LOGIN" button.');
        await KnowledgeCentralLoginPage.loginForm.login.clickButton();
        StepLogger.verification('The "Message from webpage" alert message box with the message as ' +
            '"Login Error! Ensure your user name and password are correct and try again." should be displayed ' +
            'and the user should not be logged in to the application.');
        await KnowledgeCentralLoginPageHelper.verifyAlertMessageDisplay();

        StepLogger.stepId(5);
        StepLogger.step('Click the "OK" button of the popup message box.');
        await AlertHelper.acceptAlert();
        StepLogger.verification('The message box should be closed and the user should be navigated to the Knova Knowledge Central login page.');
        await KnowledgeCentralLoginPage.loginForm.login.verifyPresentStatus();
    });

    // Jira References - KNOV-412
    it('Validation of logging to Knova Knowledge Central with blank values for username and password fields - [22336209]', async () => {
        // Auto generated by aurea-automation - util on Mon, 18 Feb 2019 23:41:08 GMT
        StepLogger.caseId = 22336209;

        // Step 1 is covered in beforeAll block
        StepLogger.stepId(1);
        StepLogger.step('Open the IE browser and launch the Knova Knowledge Central application ' +
            'using http://10.25.212.11:8080/knowledgecentral/login.do link.');
        StepLogger.verification('The Knova Knowledge Central application should be up and running.');

        StepLogger.stepId(2);
        StepLogger.step('Leave the "USERNAME", "PASSWORD" field blank and click the "LOGIN" button.');
        await KnowledgeCentralLoginPage.loginForm.login.clickButton();
        StepLogger.verification('The "Message from webpage" alert message box with the message as ' +
            '"Login Error! Ensure your user name and password are correct and try again." should be ' +
            'displayed and the user should not be logged in to the application.');
        await KnowledgeCentralLoginPageHelper.verifyAlertMessageDisplay();

        StepLogger.stepId(3);
        StepLogger.step('Click the "OK" button of the popup message box.');
        await AlertHelper.acceptAlert();
        StepLogger.verification('The message box should be closed and the user should be ' +
            'navigated to the Knova Knowledge Central login page.');
        await KnowledgeCentralLoginPage.loginForm.login.verifyPresentStatus();
    });

    // Jira References - KNOV-412
    it('Validation of logging to Knova Knowledge Central with valid username and invalid password - [22325516]', async () => {
        // Auto generated by aurea-automation - util on Mon, 18 Feb 2019 23:48:29 GMT
        const invalidPassword = await PageHelper.getUniqueId();
        StepLogger.caseId = 22325516;

        // Step 1 is covered in the beforeAll block
        StepLogger.stepId(1);
        StepLogger.step('Open the IE browser and launch the Knova Knowledge Central application using ' +
            'http://10.25.212.11:8080/knowledgecentral/login.do link.');
        StepLogger.verification('The Knova Knowledge Central application should be up and running.');

        StepLogger.stepId(2);
        StepLogger.step('Enter valid username in the "USERNAME" field. (e.g, admin)');
        StepLogger.verification('User should be able to enter value in the "USERNAME" field.');
        await KnowledgeCentralLoginPageHelper.enterAndVerifyUserName(user.username);

        StepLogger.stepId(3);
        StepLogger.step('Enter invalid password in the "PASSWORD" field. (e.g, track)');
        StepLogger.verification('User should be able to enter value in the "PASSWORD" field.');
        await KnowledgeCentralLoginPageHelper.enterAndVerifyPassword(invalidPassword);

        StepLogger.stepId(4);
        StepLogger.step('Click the "LOGIN" button.');
        await KnowledgeCentralLoginPage.loginForm.login.clickButton();
        StepLogger.verification('The "Message from webpage" alert message box with the message as ' +
            '"Login Error! Ensure your user name and password are correct and try again." should be ' +
            'displayed and the user should not be logged in to the application.');
        await KnowledgeCentralLoginPageHelper.verifyAlertMessageDisplay();

        StepLogger.stepId(5);
        StepLogger.step('Click the "OK" button of the alerts message box.');
        await AlertHelper.acceptAlert();
        StepLogger.verification('The message box should be closed and the user should be navigated to the Knova Knowledge Central login page.');
        await KnowledgeCentralLoginPage.loginForm.login.verifyPresentStatus();
    });

    // Jira References - KNOV-412
    it('Validation of logging to Knova Knowledge Central with blank value for username and valid password - [22336212]', async () => {
        // Auto generated by aurea-automation - util on Tue, 19 Feb 2019 02:03:44 GMT
        StepLogger.caseId = 22336212;

        // Step 1 is covered in the beforeAll block
        StepLogger.stepId(1);
        StepLogger.step('Open the IE browser and launch the Knova Knowledge Central application using ' +
            'http://10.25.212.11:8080/knowledgecentral/login.do link.');
        StepLogger.verification('The Knova Knowledge Central application should be up and running.');

        StepLogger.stepId(2);
        StepLogger.step('Leave the "USERNAME" field blank and enter the valid admin password in the "PASSWORD" field.');
        StepLogger.verification('User should be able to enter valid admin password in the "PASSWORD" field.');
        await KnowledgeCentralLoginPageHelper.enterAndVerifyPassword(user.password);

        StepLogger.stepId(3);
        StepLogger.step('Click the "LOGIN" button.');
        await KnowledgeCentralLoginPage.loginForm.login.clickButton();
        StepLogger.verification('The "Message from webpage" alert message box with the message as ' +
            '"Login Error! Ensure your user name and password are correct and try again." should be ' +
            'displayed and the user should not be logged in to the application.');
        await KnowledgeCentralLoginPageHelper.verifyAlertMessageDisplay();

        StepLogger.stepId(4);
        StepLogger.step('Click the "OK" button of the popup message box.');
        await AlertHelper.acceptAlert();
        StepLogger.verification('The message box should be closed and the user should be navigated to the ' +
            'Knova Knowledge Central login page.');
        await KnowledgeCentralLoginPage.loginForm.login.verifyPresentStatus();
    });

    // Jira References - KNOV-412
    it('Validation of logging to Knova Knowledge Central with value username and blank value for the password field - [22336217]', async () => {
        // Auto generated by aurea-automation - util on Tue, 19 Feb 2019 02:09:47 GMT
        StepLogger.caseId = 22336217;

        // Step 1 is covered in the beforeAll block
        StepLogger.stepId(1);
        StepLogger.step('Open the IE browser and launch the Knova Knowledge Central application using ' +
            'http://10.25.212.11:8080/knowledgecentral/login.do link.');
        StepLogger.verification('The Knova Knowledge Central application should be up and running.');

        StepLogger.stepId(2);
        StepLogger.step('Enter a valid admin username in the "USERNAME" field and leave the "PASSWORD" field blank/');
        StepLogger.verification('User should be able to enter valid admin username in the "USERNAME" field.');
        await KnowledgeCentralLoginPageHelper.enterAndVerifyUserName(user.username);

        StepLogger.stepId(3);
        StepLogger.step('Click the "LOGIN" button.');
        await KnowledgeCentralLoginPage.loginForm.login.clickButton();
        StepLogger.verification('The "Message from webpage" alert message box with the message as ' +
            '"Login Error! Ensure your user name and password are correct and try again." should be ' +
            'displayed and the user should not be logged in to the application.');
        await KnowledgeCentralLoginPageHelper.verifyAlertMessageDisplay();

        StepLogger.stepId(4);
        StepLogger.step('Click the "OK" button of the popup message box.');
        await AlertHelper.acceptAlert();
        StepLogger.verification('The message box should be closed and the user should be navigated to the ' +
            'Knova Knowledge Central login page.');
        await KnowledgeCentralLoginPage.loginForm.login.verifyPresentStatus();
    });

    // Jira References - KNOV-412
    it('Validation of logout feature for a valid user in Knova Knowledge Central application - [22336219]', async () => {
        // Auto generated by aurea-automation - util on Tue, 19 Feb 2019 02:15:16 GMT
        StepLogger.caseId = 22336219;

        // Step 1 is covered in beforeAll block
        StepLogger.stepId(1);
        StepLogger.step('Open the IE browser and launch the Knova Knowledge Central application using ' +
            'http://10.25.212.11:8080/knowledgecentral/login.do link.');
        StepLogger.verification('The Knova Knowledge Central application should be up and running.');

        // Step 2 and 3 are covered in step 4
        StepLogger.stepId(2);
        StepLogger.step('Enter valid username in the "USERNAME" field. (e.g, admin)');
        StepLogger.verification('User should be able to enter value in the "USERNAME" field.');

        StepLogger.stepId(3);
        StepLogger.step('Enter valid password in the "PASSWORD" field. (e.g, admin)');
        StepLogger.verification('User should be able to enter value in the "PASSWORD" field.');

        StepLogger.stepId(4);
        StepLogger.step('Click the "LOGIN" button.');
        StepLogger.verification('User should be able to login successfully to the Knova Knowledge Central.');
        await KnowledgeCentralLoginPageHelper.loginAsAdmin();

        StepLogger.stepId(5);
        StepLogger.step('Verify that the logged in admin user"s name is displayed at the top right ' +
            'corner of the page.');
        StepLogger.verification('The logged in admin user"s name should be displayed at the top ' +
            'right corner of the page.');
        await KnowledgeCentralHomePageHelper.verifyHeaderBannerDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Click the burger icon available at the top left corner of the page.');
        await KnowledgeCentralHomePage.hamburgerIcon.clickButton();
        StepLogger.verification('The vertical menu bar with the list of available modules should be ' +
            ' displayed on the left end of the page.');
        await KnowledgeCentralHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(7);
        StepLogger.step('Select the "Logout" option from the options displayed in the menu bar.');
        await KnowledgeCentralLoginPageHelper.logout();
        StepLogger.verification('User should be logged out and the Knova Knowledge Central application login ' +
            'page should be displayed.');
        await KnowledgeCentralLoginPage.loginForm.login.verifyPresentStatus();
    });

    // Jira References - KNOV-412
    it('Validation of the options/modules available for the admin user in the menu bar of Knova Knowledge Central application - [22336223]', async () => {
        // Auto generated by aurea-automation - util on Tue, 19 Feb 2019 02:32:02 GMT
        StepLogger.caseId = 22336223;

        StepLogger.preCondition('Execute C22325181 - Validation of logging to Knova Knowledge Central ' +
            'with valid username and password');
        await KnowledgeCentralLoginPageHelper.loginAsAdmin();

        StepLogger.stepId(1);
        StepLogger.step('Click the burger icon available at the top left corner of the page.');
        await KnowledgeCentralHomePage.hamburgerIcon.clickButton();
        StepLogger.verification('The vertical menu bar with the list of available options/modules for ' +
            'the admin user should be displayed on the left end of the page.');
        await KnowledgeCentralHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(2);
        StepLogger.step(`Verify that the below mentioned options/modules are displayed in the menu bar.
        - Microsites
        - Case Manager
        - Collaboration
        - Content Manager
        - Settings
        - Logout`);
        StepLogger.verification(`The below mentioned options/modules should be displayed in the menu bar.
        - Microsites
        - Case Manager
        - Collaboration
        - Content Manager
        - Settings
        - Logout`);
        await KnowledgeCentralHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Select the "Logout" option from the options displayed in the menu bar.');
        await KnowledgeCentralLoginPageHelper.logout();
        StepLogger.verification('User should be logged out and the Knova Knowledge Central application login ' +
            'page should be displayed.');
        await KnowledgeCentralLoginPage.loginForm.login.verifyPresentStatus();
    });

    // Jira References - KNOV-412
    it('Validation if the admin is not taken to the user homepage on clicking the browser back button after user logging out - [22336317]', async () => {
        // Auto generated by aurea-automation - util on Tue, 19 Feb 2019 02:44:46 GMT
        StepLogger.caseId = 22336317;

        StepLogger.preCondition('Execute C22325181 - Validation of logging to Knova Knowledge Central ' +
            'with valid username and password');
        await KnowledgeCentralLoginPageHelper.loginAsAdmin();

        StepLogger.stepId(1);
        StepLogger.step('Verify that the admin user homepage is displayed with the user name displayed on ' +
            'the top right corner of the page.');
        StepLogger.verification('The admin user name should be displayed on the top right corner of the page.');
        await KnowledgeCentralHomePageHelper.verifyHeaderBannerDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click the burger icon available at the top left corner of the page.');
        await KnowledgeCentralHomePage.hamburgerIcon.clickButton();
        StepLogger.verification('The vertical menu bar with the list of available options/modules for ' +
            'the admin user should be displayed on the left end of the page.');
        await KnowledgeCentralHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Select the "Logout" option from the options displayed in the menu bar.');
        await KnowledgeCentralLoginPageHelper.logout();
        StepLogger.verification('User should be logged out and the Knova Knowledge Central application ' +
            'login page should be displayed.');
        await KnowledgeCentralLoginPage.loginForm.login.verifyPresentStatus();

        StepLogger.stepId(4);
        StepLogger.step('Click the browser"s "<- " (back) button available at the top left corner of the screen.');
        await browser.navigate().back();
        StepLogger.verification('User should remain in the login page after the page refresh and should not be ' +
            'taken to the admin user homepage.');
        await KnowledgeCentralLoginPage.loginForm.login.verifyPresentStatus();
    });
});
