import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { AdminLoginPageHelper } from '../../../../page-objects/pages/admin-login-page/admin-login.helper';
import { ThreshHoldConfigurationManagerConstant } from '../../../../page-objects/pages/administer-system/analytics/threshhold-configuration-manager/threshhold-configuration-manager.constants';
import { ThreshHoldConfigurationManagerHelper } from '../../../../page-objects/pages/administer-system/analytics/threshhold-configuration-manager/threshhold-configuration-manager.helper';
import { ThreshHoldConfigurationManagerPage } from '../../../../page-objects/pages/administer-system/analytics/threshhold-configuration-manager/threshhold-configuration-manager.po';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: AdminLoginPageHelper;
    const decimalValue = ThreshHoldConfigurationManagerConstant.elementNames.decimalValue;
    const alphabets = ThreshHoldConfigurationManagerConstant.elementNames.alphabets;
    const specialCharacter = ThreshHoldConfigurationManagerConstant.elementNames.specialCharacter;
    const textBoxField = ThreshHoldConfigurationManagerPage.textBox;

    beforeAll(async () => {
        loginPageHelper = AdminLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        await loginPageHelper.goTo();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await AdminLoginPageHelper.logout();
    });

    // Jira References - KNOV-608
    it('To verify the error message when a decimal value is provided to Last Linked Threshold (days) attribute field. - [22378050]', async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:42:03 GMT

        StepLogger.caseId = 22378050;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Linked Threshold (days)" attribute.');
        StepLogger.verification('"Last Linked Threshold (days)" attribute should be displayed.');
        await textBoxField.lastLinked.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a decimal value between the range 1 to 9999 (For Ex: 14.8)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastLinked, decimalValue);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it('To verify the error message when a decimal value is provided to Last Used as Solution Threshold (days) attribute field. - [22378051]', async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:42:03 GMT

        StepLogger.caseId = 22378051;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Used as Solution Threshold (days)" attribute.');
        StepLogger.verification('"Last Used as Solution Threshold (days)" attribute should be displayed.');
        await textBoxField.lastUsedAsSolution.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a decimal value between the range 1 to 9999 (For Ex: 14.8)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsedAsSolution, decimalValue);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it('To verify the error message when a decimal value is provided to Last Viewed Threshold (days) attribute field. - [22378052]', async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:42:23 GMT

        StepLogger.caseId = 22378052;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Viewed Threshold (days)" attribute.');
        StepLogger.verification('"Last Viewed Threshold (days)" attribute should be displayed.');
        await textBoxField.lastViewed.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a decimal value between the range 1 to 9999 (For Ex: 14.8)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsed, decimalValue);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it('To verify the error message when a decimal value is provided to Last Used Threshold (days) attribute field. - [22378053]', async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:42:23 GMT

        StepLogger.caseId = 22378053;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Used Threshold (days)" attribute.');
        StepLogger.verification('"Last Used Threshold (days)" attribute should be displayed.');
        await textBoxField.lastUsed.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a decimal value between the range 1 to 9999 (For Ex: 14.8)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsed, decimalValue);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it(`To verify the error message when alphabets or special characters are provided to '+
        'Last Linked Threshold (days) attribute field. - [22375349]`, async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:41:49 GMT

        StepLogger.caseId = 22375349;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Linked Threshold (days)" attribute.');
        StepLogger.verification('"Last Linked Threshold (days)" attribute should be displayed.');
        await textBoxField.lastLinked.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide any alphabetical value.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastLinked, alphabets);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide specials characters in the field.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastLinked, specialCharacter);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it(`To verify the error message when alphabets or special characters are provided to Last Used as '+
        'Solution Threshold (days) attribute field. - [22375350]`, async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:41:49 GMT

        StepLogger.caseId = 22375350;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Used as Solution Threshold (days)" attribute.');
        StepLogger.verification('"Last Used as Solution Threshold (days)" attribute should be displayed.');
        await textBoxField.lastUsedAsSolution.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide any alphabetical value.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsedAsSolution, alphabets);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide specials characters in the field.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsedAsSolution, specialCharacter);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it(`To verify the error message when alphabets or special characters are provided to '+
        'Last Viewed Threshold (days) attribute field. - [22375351]`, async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:41:48 GMT

        StepLogger.caseId = 22375351;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Viewed Threshold (days)" attribute.');
        StepLogger.verification('"Last Viewed Threshold (days)" attribute should be displayed.');
        await textBoxField.lastViewed.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide any alphabetical value.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastViewed, alphabets);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide specials characters in the field.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastViewed, specialCharacter);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it(`To verify the error message when alphabets or special characters are provided to '+
     'Last Used Threshold (days) attribute field. - [22375352]`, async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:41:49 GMT

        StepLogger.caseId = 22375352;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Used Threshold (days)" attribute.');
        StepLogger.verification('"Last Used Threshold (days)" attribute should be displayed.');
        await textBoxField.lastUsed.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide any alphabetical value.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsed, alphabets);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide specials characters in the field.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsed, specialCharacter);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });
});
