import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { AdminLoginPageHelper } from '../../../../page-objects/pages/admin-login-page/admin-login.helper';
import { ThreshHoldConfigurationManagerConstant } from '../../../../page-objects/pages/administer-system/analytics/threshhold-configuration-manager/threshhold-configuration-manager.constants';
import { ThreshHoldConfigurationManagerHelper } from '../../../../page-objects/pages/administer-system/analytics/threshhold-configuration-manager/threshhold-configuration-manager.helper';
import { ThreshHoldConfigurationManagerPage } from '../../../../page-objects/pages/administer-system/analytics/threshhold-configuration-manager/threshhold-configuration-manager.po';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: AdminLoginPageHelper;
    const blank = ThreshHoldConfigurationManagerConstant.errorConditionTestData.blank;
    const zero = ThreshHoldConfigurationManagerConstant.errorConditionTestData.zero;
    const negativeNumber = ThreshHoldConfigurationManagerConstant.errorConditionTestData.minusFive;
    const tenLakh = ThreshHoldConfigurationManagerConstant.errorConditionTestData.tenLakh;
    const textBoxField = ThreshHoldConfigurationManagerPage.textBox;

    beforeAll(async () => {
        loginPageHelper = AdminLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        await loginPageHelper.goTo();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await AdminLoginPageHelper.logout();
    });

    // Jira References - KNOV-608
    it(`To verify the error message when the field is left blank or zero is provided to
        Last Linked Threshold (days) attribute field. - [22375455]`, async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:41:49 GMT

        StepLogger.caseId = 22375455;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Linked Threshold (days)" attribute.');
        StepLogger.verification('"Last Linked Threshold (days)" attribute should be displayed.');
        await textBoxField.lastLinked.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Leave the field blank.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastLinked, blank);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide "0" in the field.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastLinked, zero);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it(`To verify the error message when the field is left blank or zero is provided
        to Last Used as Solution Threshold (days) attribute field. - [22375456]`, async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:42:03 GMT

        StepLogger.caseId = 22375456;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Used as Solution Threshold (days)" attribute.');
        StepLogger.verification('"Last Used as Solution Threshold (days)" attribute should be displayed.');
        await textBoxField.lastUsedAsSolution.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Leave the field blank.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsedAsSolution, blank);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide "0" in the field.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsedAsSolution, zero);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it(`To verify the error message when the field is left blank or zero is provided to
        Last Viewed Threshold (days) attribute field. - [22375457]`, async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:42:03 GMT

        StepLogger.caseId = 22375457;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Viewed Threshold (days)" attribute.');
        StepLogger.verification('"Last Viewed Threshold (days)" attribute should be displayed.');
        await textBoxField.lastViewed.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Leave the field blank.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastViewed, blank);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide "0" in the field.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastViewed, zero);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it('To verify the error message when the field is left blank or zero is provided to Last Used Threshold (days) attribute field. - [22375458]', async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:42:03 GMT

        StepLogger.caseId = 22375458;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Used Threshold (days)" attribute.');
        StepLogger.verification('"Last Used Threshold (days)" attribute should be displayed.');
        await textBoxField.lastUsed.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Leave the field blank.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsed, blank);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide "0" in the field.');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsed, zero);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it(`To verify the error message when a negative value and a value more than 9999 is provided to Last Used as
        Solution Threshold (days) attribute field. - [22365693]`, async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:41:33 GMT

        StepLogger.caseId = 22365693;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Used as Solution Threshold (days)" attribute.');
        StepLogger.verification('"Last Used as Solution Threshold (days)" attribute should be displayed.');
        await textBoxField.lastUsedAsSolution.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a negative value in the field next to the attribute. (For ex: -50)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsedAsSolution, negativeNumber);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide a value in the field next to the attribute which is more than 9999. (For ex: 1000001)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsedAsSolution, tenLakh);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });
        // Jira References - KNOV-608
    it(`To verify the error message when a negative value and a value more than 9999 is provided to
        Last Viewed Threshold (days) attribute field. - [22365694]`, async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:41:49 GMT

        StepLogger.caseId = 22365694;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Viewed Threshold (days)" attribute.');
        StepLogger.verification('"Last Viewed Threshold (days)" attribute should be displayed.');
        await textBoxField.lastViewed.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a negative value in the field next to the attribute. (For ex: -50)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastViewed, negativeNumber);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide a value in the field next to the attribute which is more than 9999. (For ex: 1000001)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastViewed, tenLakh);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it(`To verify the error message when a negative value and a value more than 9999 is provided to
        Last Used Threshold (days) attribute field. - [22365695]`, async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:41:48 GMT

        StepLogger.caseId = 22365695;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Used Threshold (days)" attribute.');
        StepLogger.verification('"Last Used Threshold (days)" attribute should be displayed.');
        await textBoxField.lastUsed.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a negative value in the field next to the attribute. (For ex: -50)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsed, negativeNumber);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide a value in the field next to the attribute which is more than 9999. (For ex: 1000001)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastUsed, tenLakh);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it(`To verify the error message when a negative value and a value more than 9999 is provided to
        Last Linked Threshold (days) attribute field. - [22365692]`, async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:41:33 GMT

        StepLogger.caseId = 22365692;
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Linked Threshold (days)" attribute.');
        StepLogger.verification('"Last Linked Threshold (days)" attribute should be displayed.');
        await textBoxField.lastLinked.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a negative value in the field next to the attribute. (For ex: -50)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastLinked, negativeNumber);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.stepId(4);
        StepLogger.step('Provide a value in the field next to the attribute which is more than 9999. (For ex: 1000001)');
        await ThreshHoldConfigurationManagerHelper.enterfieldValueAndClickSave(textBoxField.lastLinked, tenLakh);
        StepLogger.verification('An error message should be displayed.');
        await ThreshHoldConfigurationManagerHelper.verifyErrorPopUpDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on OK.');
        await ThreshHoldConfigurationManagerHelper.clickOk();
        StepLogger.verification('The error message should be closed.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });
});
