import { StepLogger } from '../../../../../core/logger/step-logger';
import { PageHelper } from '../../../../components/html/page-helper';
import { CredentialsHelper } from '../../../../components/misc-utils/credentials-helper';
import { AdminHomePageHelper } from '../../../../page-objects/pages/admin-home-page/admin-home.helper';
import { AdminHomePage } from '../../../../page-objects/pages/admin-home-page/admin-home.po';
import { AdminLoginPageHelper } from '../../../../page-objects/pages/admin-login-page/admin-login.helper';
import { ThreshHoldConfigurationManagerHelper } from '../../../../page-objects/pages/administer-system/analytics/threshhold-configuration-manager/threshhold-configuration-manager.helper';
import { ThreshHoldConfigurationManagerPage } from '../../../../page-objects/pages/administer-system/analytics/threshhold-configuration-manager/threshhold-configuration-manager.po';
import { SuiteNames } from '../../../helpers/suite-names';

describe(SuiteNames.regressionSuite, () => {
    let loginPageHelper: AdminLoginPageHelper;

    beforeAll(async () => {
        loginPageHelper = AdminLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
        await loginPageHelper.goTo();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await AdminLoginPageHelper.logout();
    });

    // Jira References - KNOV-608
    it('To access Threshold Configuration Manager screen. - [22363137]', async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:41:33 GMT

        StepLogger.caseId = 22363137;
        StepLogger.preCondition('Execute C22308069 - Login to Knova Administrator portal with a valid admin username and valid password');
        await AdminLoginPageHelper.loginAsAdmin();
        await AdminHomePageHelper.verifyUserNameAtTheTopRightCorner(CredentialsHelper.admin.username);

        StepLogger.stepId(1);
        StepLogger.step('Click on the options icon (3 lines at the top left corner).');
        await AdminHomePageHelper.clickOnBurgerIcon();

        StepLogger.verification(`The following options should be displayed.
			-Home
			-Manage workbench
			-Manage communities
			-Manage Knowledge
			-Manage People
			-Manage Site Experience
			-Administer System
			-Settings
			-Logout`);
        await AdminHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(2);
        StepLogger.step('Click on Administer System.');
        await AdminHomePageHelper.clickAdministerSystem();
        StepLogger.verification('List of options should be displayed.');
        await AdminHomePageHelper.verifyAdministerSystemSubMenu();

        StepLogger.stepId(3);
        StepLogger.step('Click on Analytics.');
        await AdminHomePage.administerSystem.analytics.hoverOverAndClick();
        StepLogger.verification('List of options should be displayed.');
        await AdminHomePageHelper.verifyAnalyticsSubMenu();

        StepLogger.stepId(4);
        StepLogger.step('Click on Threshold Configuration Manager.');
        await AdminHomePage.administerSystem.threshholdConfManager.hoverOverAndClick();
        StepLogger.verification('List of thresholds should be displayed with Save and Cancel buttons at the bottom.');
        await ThreshHoldConfigurationManagerHelper.verifyNavigation();

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it('To configure "Last Linked Threshold (days)" attribute. - [22363159]', async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:41:33 GMT

        StepLogger.caseId = 22363159;
        const uniqueNumber = await ThreshHoldConfigurationManagerHelper.getUniqueThreshHoldNumber();
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Linked Threshold (days)" attribute.');
        StepLogger.verification('"Last Linked Threshold (days)" attribute should be displayed.');
        await ThreshHoldConfigurationManagerPage.textBox.lastLinked.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a value in the field next to the attribute. The value can only be an integer ranging from 1 to 9999 ' +
            'and no decimal values allowed.');
        await ThreshHoldConfigurationManagerPage.textBox.lastLinked.sendKeys(uniqueNumber);
        StepLogger.verification('The value should be displayed in the field.');
        await ThreshHoldConfigurationManagerPage.textBox.lastLinked.verifyTextEntered(uniqueNumber);

        StepLogger.stepId(3);
        StepLogger.step('Click on Save.');
        await ThreshHoldConfigurationManagerPage.buttons.save.hoverOverAndClick();
        StepLogger.verification('The value of the attribute should be saved.');
        await ThreshHoldConfigurationManagerPage.textBox.lastLinked.verifyTextEntered(uniqueNumber);

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it('To configure "Last Used as Solution Threshold (days)" attribute. - [22363161]', async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:41:33 GMT

        StepLogger.caseId = 22363161;
        const uniqueNumber = await ThreshHoldConfigurationManagerHelper.getUniqueThreshHoldNumber();
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Used as Solution Threshold (days)" attribute.');
        StepLogger.verification('"Last Used as Solution Threshold (days)" attribute should be displayed.');
        await ThreshHoldConfigurationManagerPage.textBox.lastUsedAsSolution.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a value in the field next to the attribute. The value can only be an integer ranging from 1 to 9999 ' +
            'and no decimal values allowed.');
        await ThreshHoldConfigurationManagerPage.textBox.lastUsedAsSolution.sendKeys(uniqueNumber);
        StepLogger.verification('The value should be displayed in the field.');
        await ThreshHoldConfigurationManagerPage.textBox.lastUsedAsSolution.verifyTextEntered(uniqueNumber);

        StepLogger.stepId(3);
        StepLogger.step('Click on Save.');
        await ThreshHoldConfigurationManagerPage.buttons.save.hoverOverAndClick();
        StepLogger.verification('The value of the attribute should be saved.');
        await ThreshHoldConfigurationManagerPage.textBox.lastUsedAsSolution.verifyTextEntered(uniqueNumber);

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it('To configure "Last Viewed Threshold (days)" attribute. - [22363162]', async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:41:33 GMT

        StepLogger.caseId = 22363162;
        const uniqueNumber = await ThreshHoldConfigurationManagerHelper.getUniqueThreshHoldNumber();
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Viewed Threshold (days)" attribute.');
        StepLogger.verification('"Last Viewed Threshold (days)" attribute should be displayed.');
        await ThreshHoldConfigurationManagerPage.textBox.lastViewed.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a value in the field next to the attribute. The value can only be an integer ranging from 1 to 9999 ' +
            'and no decimal values allowed.');
        await ThreshHoldConfigurationManagerPage.textBox.lastViewed.sendKeys(uniqueNumber);
        StepLogger.verification('The value should be displayed in the field.');
        await ThreshHoldConfigurationManagerPage.textBox.lastViewed.verifyTextEntered(uniqueNumber);

        StepLogger.stepId(3);
        StepLogger.step('Click on Save.');
        await ThreshHoldConfigurationManagerPage.buttons.save.hoverOverAndClick();
        StepLogger.verification('The value of the attribute should be saved.');
        await ThreshHoldConfigurationManagerPage.textBox.lastViewed.verifyTextEntered(uniqueNumber);

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it('To configure "Last Used Threshold (days)" attribute. - [22363163]', async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:41:33 GMT

        StepLogger.caseId = 22363163;
        const uniqueNumber = await ThreshHoldConfigurationManagerHelper.getUniqueThreshHoldNumber();
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();

        StepLogger.stepId(1);
        StepLogger.step('Go to "Last Used Threshold (days)" attribute.');
        StepLogger.verification('"Last Used Threshold (days)" attribute should be displayed.');
        await ThreshHoldConfigurationManagerPage.textBox.lastUsed.verifyDisplayedStatus();

        StepLogger.stepId(2);
        StepLogger.step('Provide a value in the field next to the attribute. The value can only be an integer ranging from 1 to 9999 ' +
            'and no decimal values allowed.');
        await ThreshHoldConfigurationManagerPage.textBox.lastUsed.sendKeys(uniqueNumber);
        StepLogger.verification('The value should be displayed in the field.');
        await ThreshHoldConfigurationManagerPage.textBox.lastUsed.verifyTextEntered(uniqueNumber);

        StepLogger.stepId(3);
        StepLogger.step('Click on Save.');
        await ThreshHoldConfigurationManagerPage.buttons.save.hoverOverAndClick();
        StepLogger.verification('The value of the attribute should be saved.');
        await ThreshHoldConfigurationManagerPage.textBox.lastUsed.verifyTextEntered(uniqueNumber);

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });

    // Jira References - KNOV-608
    it('To verify the Cancel button. - [22378091]', async () => {
        // Auto generated by aurea-automation - util on Tue, 05 Mar 2019 08:42:23 GMT

        StepLogger.caseId = 22378091;
        const uniqueNumber = await ThreshHoldConfigurationManagerHelper.getUniqueThreshHoldNumber();
        StepLogger.preCondition('Execute test case C22363137 to access Threshold Configuration Manager screen.');
        await ThreshHoldConfigurationManagerHelper.navigateToThreshholdConfManager();
        const actualValue = await ThreshHoldConfigurationManagerHelper.getFieldValue(ThreshHoldConfigurationManagerPage.textBox.lastUsed);

        StepLogger.stepId(1);
        StepLogger.step('Make changes in some of the attributes.');
        await ThreshHoldConfigurationManagerPage.textBox.lastUsed.sendKeys(uniqueNumber);
        StepLogger.verification('The changes should be displayed in the fields.');
        await ThreshHoldConfigurationManagerPage.textBox.lastUsed.verifyTextEntered(uniqueNumber);

        StepLogger.stepId(2);
        StepLogger.step('Scroll down and click on cancel button.');
        await ThreshHoldConfigurationManagerPage.buttons.cancel.hoverOverAndClick();
        StepLogger.verification('Home screen of Knova should be displayed.');
        await AdminHomePageHelper.verifyWelcomePage();

        StepLogger.stepId(3);
        StepLogger.step('Again go to Administer System->Analytics->Threshold configuration manager');
        await ThreshHoldConfigurationManagerHelper.clickBurgerIconAndNavigateToThreshHoldmanager();
        StepLogger.verification('Verify that the changes made should not be saved.');
        await ThreshHoldConfigurationManagerPage.textBox.lastUsed.verifyTextEntered(actualValue);

        StepLogger.postCondition('LogOut');
        await AdminLoginPageHelper.logout(true);
    });
});
