import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { AdminHomePage } from '../../../page-objects/pages/admin-home-page/admin-home.po';
import { KnowledgeCentralCollaborationConstant } from '../../../page-objects/pages/knowledge-central-collaboration/knowledge-central-collaboration.constant';
import { KnowledgeCentralCollaborationHelper } from '../../../page-objects/pages/knowledge-central-collaboration/knowledge-central-collaboration.helper';
import { KnowledgeCentralCollaborationPage } from '../../../page-objects/pages/knowledge-central-collaboration/knowledge-central-collaboration.po';
import { KnowledgeCentralHomePageHelper } from '../../../page-objects/pages/knowledge-central-home-page/knowledge-central-home.helper';
import { KnowledgeCentralLoginPageHelper } from '../../../page-objects/pages/knowledge-central-login-page/knowledge-central-login.helper';
import { KnowledgeCentralLoginPage } from '../../../page-objects/pages/knowledge-central-login-page/knowledge-central-login.po';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.smokeSuite, () => {
    let loginPageHelper: KnowledgeCentralLoginPage;

    beforeAll(async () => {
        loginPageHelper = KnowledgeCentralLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await KnowledgeCentralLoginPageHelper.logout();
        await KnowledgeCentralLoginPageHelper.loginAsAdmin();
    });

    it('To verify if an error is displayed when clicked on Ok without adding collaborators in Expert Finder window - [22902305]', async () => {
        // Auto generated by aurea-automation - util on Thu, 25 Apr 2019 11:12:52 GMT

        StepLogger.caseId = 22902305;
        const error = KnowledgeCentralCollaborationConstant.errorMessages.addCollaborators;

        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
       User Name : admin
       Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on New Collaboration button');
        await KnowledgeCentralCollaborationHelper.clickOnNewCollaborationButton();
        StepLogger.verification('Collaborator Creator window should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Click on Add Collaborators button present beside * Collaborators: field');
        await KnowledgeCentralCollaborationHelper.clickOnAddCollaboratorButton();
        StepLogger.verification('Expert Finder Pane should be opened up');
        await KnowledgeCentralCollaborationHelper.verifyExpertFinderPaneDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Do NOT add any collaborator and click on Ok button');
        await KnowledgeCentralCollaborationHelper.clickOkInExpertFinderPane();
        StepLogger.verification('An window showing error message "Please add Collaborators." should be displayed with Ok button');
        await KnowledgeCentralCollaborationHelper.verifyErrorPopup(error);

        StepLogger.postCondition('Close Popup');
        await KnowledgeCentralCollaborationHelper.clickOkOnErrorPopup();
    });

    it('To verify if an error message is displayed when clicked on Submit without entering any data' +
        'in any fields in Collaborator Creator window - [22902333]', async () => {
            // Auto generated by aurea-automation - util on Thu, 25 Apr 2019 11:12:52 GMT

            StepLogger.caseId = 22902333;
            const error = KnowledgeCentralCollaborationConstant.errorMessages.subject;

            // Step 1 covered in the beforeEach block
            StepLogger.stepId(1);
            StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
       User Name : admin
       Password : admin`);
            StepLogger.verification('User should successfully login to Knova Knowledge Central application');

            StepLogger.stepId(2);
            StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
            await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
            StepLogger.verification('COLLABORATION page should be displayed');
            await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

            StepLogger.stepId(3);
            StepLogger.step('Click on New Collaboration button');
            await KnowledgeCentralCollaborationHelper.clickOnNewCollaborationButton();
            StepLogger.verification('Collaborator Creator window should be displayed');
            await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();

            StepLogger.stepId(4);
            StepLogger.step('Do NOT enter any data in any fields and click on Submit');
            await PageHelper.switchToiFrame(KnowledgeCentralCollaborationPage.dialogIFrame);
            await KnowledgeCentralCollaborationHelper.clickSubmitOnCollaboratorCreatorWindow();
            StepLogger.verification('An error window with message "Please enter a Subject." should be displayed with Ok button');
            await KnowledgeCentralCollaborationHelper.verifyErrorPopup(error);

            StepLogger.stepId(5);
            StepLogger.step('Click ok on error pop-up displayed');
            await KnowledgeCentralCollaborationHelper.clickOkOnErrorPopup();
            StepLogger.verification('Error pop-up window should be closed');
            await KnowledgeCentralCollaborationHelper.verifyErrorPopupClosed(error);
        });

    it('To verify if an error is displayed when clicked on Submit without entering Subject field in Collaborator Creator window - [22902346]', async () => {
        // Auto generated by aurea-automation - util on Thu, 25 Apr 2019 15:25:57 GMT

        StepLogger.caseId = 22902346;
        const value = KnowledgeCentralCollaborationConstant.errorMessages.subject;

        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
       User Name : admin
       Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on New Collaboration button');
        await KnowledgeCentralCollaborationHelper.clickOnNewCollaborationButton();
        StepLogger.verification('Collaborator Creator window should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Enter data in all fields except in "Subject" and click on Submit');
        await PageHelper.switchToiFrame(KnowledgeCentralCollaborationPage.dialogIFrame);
        await KnowledgeCentralCollaborationHelper.enterMessage(value);
        StepLogger.verification('An error pop-up window should be displayed with "Please enter a Subject." message');
        await KnowledgeCentralCollaborationHelper.clickSubmitOnCollaboratorCreatorWindow();
        await KnowledgeCentralCollaborationHelper.verifyErrorPopup(value);

        StepLogger.stepId(5);
        StepLogger.step('Click Ok on error pop-up window');
        await KnowledgeCentralCollaborationHelper.clickOkOnErrorPopup();
        StepLogger.verification('Error pop-up window should be closed');
        await KnowledgeCentralCollaborationHelper.verifyErrorPopupClosed(value);
    });

    it('To verify if an error is displayed when clicked on Submit without entering * Message: field in Collaborator Creator window - [22902347]', async () => {
        // Auto generated by aurea-automation - util on Thu, 25 Apr 2019 15:53:24 GMT

        StepLogger.caseId = 22902347;
        const value = KnowledgeCentralCollaborationConstant.errorMessages.message;

        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
       User Name : admin
       Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on New Collaboration button');
        await KnowledgeCentralCollaborationHelper.clickOnNewCollaborationButton();
        StepLogger.verification('Collaborator Creator window should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Enter data in all fields except in "* Message: " and click on Submit');
        await KnowledgeCentralCollaborationHelper.enterSubject(value);
        await KnowledgeCentralCollaborationHelper.clickSubmitOnCollaboratorCreatorWindow();
        StepLogger.verification('An error pop-up window should be displayed with "Please enter a Message." message');
        await KnowledgeCentralCollaborationHelper.verifyErrorPopup(value);

        StepLogger.stepId(5);
        StepLogger.step('Click Ok on error pop-up window');
        await KnowledgeCentralCollaborationHelper.clickOkOnErrorPopup();
        StepLogger.verification('Error pop-up window should be closed');
        await KnowledgeCentralCollaborationHelper.verifyErrorPopupClosed(value);
    });

    it('To verify if an error is displayed when clicked on Submit without entering "Collaborators" field' +
        'in Collaborator Creator window - [22902358]', async () => {
            // Auto generated by aurea-automation - util on Thu, 25 Apr 2019 16:01:35 GMT

            StepLogger.caseId = 22902358;
            const value = KnowledgeCentralCollaborationConstant.errorMessages.collaborators;

            // Step 1 covered in the beforeEach block
            StepLogger.stepId(1);
            StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
            User Name : admin
            Password : admin`);
            StepLogger.verification('User should successfully login to Knova Knowledge Central application');

            StepLogger.stepId(2);
            StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
            await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
            StepLogger.verification('COLLABORATION page should be displayed');
            await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

            StepLogger.stepId(3);
            StepLogger.step('Click on New Collaboration button');
            await KnowledgeCentralCollaborationHelper.clickOnNewCollaborationButton();
            StepLogger.verification('Collaborator Creator window should be displayed');
            await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();

            StepLogger.stepId(4);
            StepLogger.step('Enter data in all fields except in "Collaborators" and click on Submit');
            await KnowledgeCentralCollaborationHelper.enterSubject(value);
            await KnowledgeCentralCollaborationHelper.enterMessage(value);
            StepLogger.verification('An error pop-up window should be displayed with "Please enter a Collaborators." message');
            await KnowledgeCentralCollaborationHelper.clickSubmitOnCollaboratorCreatorWindow();
            await KnowledgeCentralCollaborationHelper.verifyErrorPopup(value);

            StepLogger.stepId(5);
            StepLogger.step('Click Ok on error pop-up window');
            await KnowledgeCentralCollaborationHelper.clickOkOnErrorPopup();
            StepLogger.verification('Error pop-up window should be closed');
            await KnowledgeCentralCollaborationHelper.verifyErrorPopupClosed(value);
        });

    it('To verify if Collaboration Builder Page Opens up when clicked on collaboration - [22902423]', async () => {
        // Auto generated by aurea-automation - util on Fri, 26 Apr 2019 05:04:48 GMT

        StepLogger.caseId = 22902423;
        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on Collaboration blue link');
        await KnowledgeCentralCollaborationHelper.clickOnCollaborationBlueLink();
        StepLogger.verification('Collaboration Builder Page should be displayed when clicked on collaboration');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationBuilderWindow();
    });

    it('To verify Collaboration Builder Page displayed - [22902454]', async () => {
        // Auto generated by aurea-automation - util on Fri, 26 Apr 2019 05:20:07 GMT

        StepLogger.caseId = 22902454;
        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on Collaboration blue link');
        await KnowledgeCentralCollaborationHelper.clickOnCollaborationBlueLink();
        StepLogger.verification('Collaboration Builder Page should be displayed when clicked on collaboration');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationBuilderWindow();

        StepLogger.stepId(4);
        StepLogger.step('Verify Collaboration Builder Page');
        StepLogger.verification(`Collaboration Builder Page should display as below:
        1. Subject
        2. Collaborators
        3. Originator
        4. Message
        5. Post Message
        6. Add Collaborator
        7. Ok & Delete buttons`);
        await KnowledgeCentralCollaborationHelper.verifyCollaborationBuilderItems();
    });

    it('To verify if user can Post Message to an existing collaboration - [22902472]', async () => {
        // Auto generated by aurea-automation - util on Fri, 26 Apr 2019 06:03:58 GMT

        StepLogger.caseId = 22902472;
        const value = await PageHelper.getUniqueId();

        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on Collaboration blue link');
        await KnowledgeCentralCollaborationHelper.clickOnCollaborationBlueLink();
        StepLogger.verification('Collaboration Builder Page should be displayed when clicked on collaboration');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationBuilderWindow();

        StepLogger.stepId(4);
        StepLogger.step('Enter text in Message text field');
        await KnowledgeCentralCollaborationHelper.enterMessageInCollaborationBuilderWindow(value);
        StepLogger.verification('User should be able to enter message');
        await KnowledgeCentralCollaborationHelper.verifyMessageInCollaborationBuilderWindow(value);

        StepLogger.stepId(5);
        StepLogger.step('Click on Post Message');
        await KnowledgeCentralCollaborationHelper.clickPostMessageInCollaborationBuilderWindow();
        StepLogger.verification('Collaboration Builder Page should be closed & Collaboration page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationBuilderWindowClosed();
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();
    });

    it('To verify if newly posted message is reflected in the collaboration - [22902508]', async () => {
        // Auto generated by aurea-automation - util on Fri, 26 Apr 2019 07:46:08 GMT

        StepLogger.caseId = 22902508;
        const value = await PageHelper.getUniqueId();

        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on Collaboration blue link');
        await KnowledgeCentralCollaborationHelper.clickOnCollaborationBlueLink();
        StepLogger.verification('Collaboration Builder Page should be displayed when clicked on collaboration');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationBuilderWindow();

        StepLogger.stepId(4);
        StepLogger.step('Enter text in Message text field and click on Post Message');
        await KnowledgeCentralCollaborationHelper.enterMessageInCollaborationBuilderWindow(value);
        await KnowledgeCentralCollaborationHelper.clickPostMessageInCollaborationBuilderWindow();
        StepLogger.verification('Collaboration Builder Page should be closed & Collaboration page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationBuilderWindowClosed();

        StepLogger.stepId(5);
        StepLogger.step('Click on Collaboration blue link');
        await KnowledgeCentralCollaborationHelper.clickOnCollaborationBlueLink();
        StepLogger.verification('Collaboration Builder Page should be displayed when clicked on collaboration');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationBuilderWindow();

        StepLogger.stepId(6);
        StepLogger.step('Verify if newly added message is displayed');
        StepLogger.verification('User should be able to view newly added message');
        await KnowledgeCentralCollaborationHelper.verifyAddedMessage(value);
    });

    it('To verify if user is able to create a new Collaboration with Priority as Urgent - [22902367]', async () => {
        // Auto generated by aurea-automation - util on Fri, 26 Apr 2019 01:01:29 GMT

        StepLogger.caseId = 22902367;
        const value = await PageHelper.getUniqueId();

        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
            User Name : admin
            Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on New Collaboration button');
        await KnowledgeCentralCollaborationHelper.clickOnNewCollaborationButton();
        StepLogger.verification('Collaborator Creator window should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Enter Subject, Message, Priority as "Urgent"');
        await KnowledgeCentralCollaborationHelper.enterValuesWithUrgent(value);
        StepLogger.verification('User should be able to enter Subject, Message, Priority as "Urgent"');
        await KnowledgeCentralCollaborationHelper.verifyValuesWithUrgent(value);

        StepLogger.stepId(5);
        StepLogger.step('Click on "Add Collaborators" button');
        await KnowledgeCentralCollaborationHelper.clickOnAddCollaboratorButtonAfterData();
        StepLogger.verification('Expert Finder window should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyExpertFinderPaneDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Click on Find tab and click on Show All button');
        await KnowledgeCentralCollaborationHelper.clickOnFindTab();
        await KnowledgeCentralCollaborationHelper.clickOnShowAllButton();
        StepLogger.verification('Click on Show All button should display list of collaborators available');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorsList();

        StepLogger.stepId(7);
        StepLogger.step('Select a collaborator and click on Ok button');
        await KnowledgeCentralCollaborationHelper.selectCollaboratorAndVerify();
        await KnowledgeCentralCollaborationHelper.clickOkInExpertFinderPaneNew();
        StepLogger.verification('Selected collaborator should be displayed beside Add Collaborators button of Collaborator Creator window');
        await PageHelper.switchToiFrame(AdminHomePage.contentIFrame);
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();

        StepLogger.stepId(8);
        StepLogger.step('Click on Submit button');
        await PageHelper.switchToiFrame(KnowledgeCentralCollaborationPage.dialogIFrame);
        await KnowledgeCentralCollaborationHelper.clickSubmitOnCollaboratorCreatorWindow();
        StepLogger.verification('Data should be saved & Collaborator Creator window should be closed');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindowClosed();
    });

    it('To verify if user is able to create a new Collaboration with Priority as Normal - [22902375]', async () => {
        // Auto generated by aurea-automation - util on Fri, 26 Apr 2019 11:45:25 GMT

        StepLogger.caseId = 22902375;
        const value = await PageHelper.getUniqueId();

        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
            User Name : admin
            Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on New Collaboration button');
        await KnowledgeCentralCollaborationHelper.clickOnNewCollaborationButton();
        StepLogger.verification('Collaborator Creator window should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Enter Subject, Message, Priority as "Normal"');
        await KnowledgeCentralCollaborationHelper.enterValuesWithNormal(value);
        StepLogger.verification('User should be able to enter Subject, Message, Priority as "Normal"');
        await KnowledgeCentralCollaborationHelper.verifyValuesWithNormal(value);

        StepLogger.stepId(5);
        StepLogger.step('Click on "Add Collaborators" button');
        await KnowledgeCentralCollaborationHelper.clickOnAddCollaboratorButtonAfterData();
        StepLogger.verification('Expert Finder window should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyExpertFinderPaneDisplayed();

        StepLogger.stepId(6);
        StepLogger.step('Click on Find tab and click on Show All button');
        await KnowledgeCentralCollaborationHelper.clickOnFindTab();
        await KnowledgeCentralCollaborationHelper.clickOnShowAllButton();
        StepLogger.verification('Click on Show All button should display list of collaborators available');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorsList();

        StepLogger.stepId(7);
        StepLogger.step('Select a collaborator and click on Ok button');
        await KnowledgeCentralCollaborationHelper.selectCollaboratorAndVerify();
        await KnowledgeCentralCollaborationHelper.clickOkInExpertFinderPaneNew();
        StepLogger.verification('Selected collaborator should be displayed beside Add Collaborators button of Collaborator Creator window');
        await PageHelper.switchToiFrame(AdminHomePage.contentIFrame);
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();

        StepLogger.stepId(8);
        StepLogger.step('Click on Submit button');
        await PageHelper.switchToiFrame(KnowledgeCentralCollaborationPage.dialogIFrame);
        await KnowledgeCentralCollaborationHelper.clickSubmitOnCollaboratorCreatorWindow();
        StepLogger.verification('Data should be saved & Collaborator Creator window should be closed');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindowClosed();
    });
});
