import { StepLogger } from '../../../../core/logger/step-logger';
import { PageHelper } from '../../../components/html/page-helper';
import { KnowledgeCentralCollaborationHelper } from '../../../page-objects/pages/knowledge-central-collaboration/knowledge-central-collaboration.helper';
import { KnowledgeCentralHomePageHelper } from '../../../page-objects/pages/knowledge-central-home-page/knowledge-central-home.helper';
import { KnowledgeCentralLoginPageHelper } from '../../../page-objects/pages/knowledge-central-login-page/knowledge-central-login.helper';
import { KnowledgeCentralLoginPage } from '../../../page-objects/pages/knowledge-central-login-page/knowledge-central-login.po';
import { SuiteNames } from '../../helpers/suite-names';

describe(SuiteNames.smokeSuite, () => {
    let loginPageHelper: KnowledgeCentralLoginPage;

    beforeAll(async () => {
        loginPageHelper = KnowledgeCentralLoginPageHelper.getInstance();
        await PageHelper.maximiseBrowser();
    });

    beforeEach(async () => {
        await PageHelper.switchToFirstTab();
        await loginPageHelper.goTo();
        await KnowledgeCentralLoginPageHelper.logout();
        await KnowledgeCentralLoginPageHelper.loginAsAdmin();

    });

    it('To verify if user successfully login to Knova Knowledge Central application - [22902123]', async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 07:45:53 GMT

        StepLogger.caseId = 22902123;
        // Step 1, 2 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step('Open URL : http://10.25.212.11:8080/knowledgecentral/login.do');
        StepLogger.verification('Knova Knowledge Central login page should be displayed');

        StepLogger.stepId(2);
        StepLogger.step('Enter User Name : admin & Password : admin and Click on Login');
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(3);
        StepLogger.step('Verify the home page displayed');
        StepLogger.verification(`Knova Knowledge Central application homepage should be displayed with below:
        1. Menu Button
        2. A Search Bar
        3. Browse: Products
        4. My Favorites - Saved Documents, Saved Searches
        5. Hot Topics
        6. Work in Progress
        7. Answer Wizards
        8. My Subscriptions`);
        await KnowledgeCentralHomePageHelper.verifyHomePageProperties();
    });

    it('To verify the menu items displayed when clicked on menu bar button - [22902134]', async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 08:53:34 GMT

        StepLogger.caseId = 22902134;
        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Verify the home page displayed');
        StepLogger.verification(`Knova Knowledge Central application homepage should be displayed with below:
        1. Menu Button
        2. A Search Bar
        3. Browse: Products
        4. My Favorites - Saved Documents, Saved Searches
        5. Hot Topics
        6. Work in Progress
        7. Answer Wizards
        8. My Subscriptions`);
        await KnowledgeCentralHomePageHelper.verifyHomePageProperties();

        StepLogger.stepId(3);
        StepLogger.step('Click on menu Bar button');
        await KnowledgeCentralHomePageHelper.clickOnMenuIcon();
        StepLogger.verification(`Menu bar should display below menu items:
        1. Microsites
        2. Case Manager
        3. Collaboration
        4. Content Manager
        5. Settings
        6. Logout`);
        await KnowledgeCentralHomePageHelper.verifySidebarFieldsDisplayed();
    });

    it('To verify if user is navigated to collaboration page when clicked on collaboration menu items - [22902139]', async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 11:21:04 GMT

        StepLogger.caseId = 22902139;
        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on menu Bar button available to the LHS top corner');
        await KnowledgeCentralHomePageHelper.clickOnMenuIcon();
        StepLogger.verification(`Menu bar should display below menu items:
        1. Microsites
        2. Case Manager
        3. Collaboration
        4. Content Manager
        5. Settings
        6. Logout`);
        await KnowledgeCentralHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();
    });

    it('To verify the COLLABORATION page displayed - [22902145]', async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 11:29:14 GMT

        StepLogger.caseId = 22902145;
        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on menu Bar button available to the LHS top corner');
        await KnowledgeCentralHomePageHelper.clickOnMenuIcon();
        StepLogger.verification(`Menu bar should display below menu items:
        1. Microsites
        2. Case Manager
        3. Collaboration
        4. Content Manager
        5. Settings
        6. Logout`);
        await KnowledgeCentralHomePageHelper.verifySidebarFieldsDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(4);
        StepLogger.step('Verify the COLLABORATION page displayed');
        StepLogger.verification(`COLLABORATION page should display below:
        1. New Collaboration button
        2. Existing list of Collaborations create with columns Subject, Originator, Customer, Case ID, Last Update.Delete`);
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageItems();
    });

    it('To verify if Collaboration Creator window is displayed when clicked on "New Collaboration" button - [22902210]', async () => {
        // Auto generated by aurea-automation - util on Wed, 24 Apr 2019 12:02:00 GMT

        StepLogger.caseId = 22902210;
        StepLogger.stepId(1);
        // Step 1 covered in the beforeEach block
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on New Collaboration button');
        await KnowledgeCentralCollaborationHelper.clickOnNewCollaborationButton();
        StepLogger.verification('Collaborator Creator window should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();
    });

    it('To verify the fields displayed in Collaboration Creator window - [22902222]', async () => {
        // Auto generated by aurea-automation - util on Thu, 25 Apr 2019 01:14:34 GMT

        StepLogger.caseId = 22902222;
        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on New Collaboration button');
        await KnowledgeCentralCollaborationHelper.clickOnNewCollaborationButton();
        StepLogger.verification('Collaborator Creator window should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Verify the fields displayed in Collaborator Creator window');
        StepLogger.verification(`Collaborator Creator window should be displayed with below :
        1. Subject:
        2.      Message:
        3.      Priority: as Urgent & Normal radio buttons
        4.      * Collaborators:        Add Collaborators button
        5.      Submit
        6.      Cancel`);
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindowItems();
    });

    it('To verify if Expert Finder Pane opens up when clicked on Add Collaborators button of Collaboration Creator pane - [22902260]', async () => {
        // Auto generated by aurea-automation - util on Thu, 25 Apr 2019 05:09:17 GMT

        StepLogger.caseId = 22902260;
        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : adminc`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on New Collaboration button');
        await KnowledgeCentralCollaborationHelper.clickOnNewCollaborationButton();
        StepLogger.verification('Collaborator Creator window should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Click on Add Collaborators button present beside * Collaborators: field');
        await KnowledgeCentralCollaborationHelper.clickOnAddCollaboratorButton();
        StepLogger.verification('Expert Finder Pane should be opened up');
        await KnowledgeCentralCollaborationHelper.verifyExpertFinderPaneDisplayed();
    });

    it('To verify the fields displayed in Expert Finder Pane - [22902262]', async () => {
        // Auto generated by aurea-automation - util on Thu, 25 Apr 2019 05:18:04 GMT

        StepLogger.caseId = 22902262;
        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on New Collaboration button');
        await KnowledgeCentralCollaborationHelper.clickOnNewCollaborationButton();
        StepLogger.verification('Collaborator Creator window should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Click on Add Collaborators button present beside * Collaborators: field');
        await KnowledgeCentralCollaborationHelper.clickOnAddCollaboratorButton();
        StepLogger.verification('Expert Finder Pane should be opened up');
        await KnowledgeCentralCollaborationHelper.verifyExpertFinderPaneDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Verify the fields / buttons displayed in Expert Finder Pane');
        StepLogger.verification(`Expert Finder Pane should have below:
        1. Suggested Tab - Search for expertise in search bar with Show All button
        2. Most Recent tab
        3. Find tab with - First Name, Last Name,Group Name, Search , Submit and Show All button
        4. Selected Collaborators: section with  Remove & Name
        5. Ok & Cancel buttons`);
        await KnowledgeCentralCollaborationHelper.verifyExpertFinderItems();
    });

    it('To verify if click on "Show All" button displays list of collaborators available - [22902268]', async () => {
        // Auto generated by aurea-automation - util on Thu, 25 Apr 2019 05:44:29 GMT

        StepLogger.caseId = 22902268;
        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
        User Name : admin
        Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on New Collaboration button');
        await KnowledgeCentralCollaborationHelper.clickOnNewCollaborationButton();
        StepLogger.verification('Collaborator Creator window should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Click on Add Collaborators button present beside * Collaborators: field');
        await KnowledgeCentralCollaborationHelper.clickOnAddCollaboratorButton();
        StepLogger.verification('Expert Finder Pane should be opened up');
        await KnowledgeCentralCollaborationHelper.verifyExpertFinderPaneDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on Find tab');
        await KnowledgeCentralCollaborationHelper.clickOnFindTab();
        StepLogger.verification(`Find tab should have below fields:
        1. First Name
        2. Last Name
        3. Group Name
        4. Search
        5. Submit
        6. Show All button`);
        await KnowledgeCentralCollaborationHelper.verifyFindTabItems();

        StepLogger.stepId(6);
        StepLogger.step('Click on "Show All" button');
        await KnowledgeCentralCollaborationHelper.clickOnShowAllButton();
        StepLogger.verification('Click on Show All button should display list of collaborators available');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorsList();
    });

    it('To verify if user can Check/Uncheck to add from the list of collaborators displayed - [22902285]', async () => {
        // Auto generated by aurea-automation - util on Thu, 25 Apr 2019 07:17:40 GMT

        StepLogger.caseId = 22902285;
        // Step 1 covered in the beforeEach block
        StepLogger.stepId(1);
        StepLogger.step(`Login to Knova Knowledge Central application using http://10.25.212.11:8080/knowledgecentral/login.do with
       User Name : admin
       Password : admin`);
        StepLogger.verification('User should successfully login to Knova Knowledge Central application');

        StepLogger.stepId(2);
        StepLogger.step('Click on Menu bar > Click on "Collaboration" menu item');
        await KnowledgeCentralHomePageHelper.clickOnMenuAndCollaboration();
        StepLogger.verification('COLLABORATION page should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaborationPageDisplayed();

        StepLogger.stepId(3);
        StepLogger.step('Click on New Collaboration button');
        await KnowledgeCentralCollaborationHelper.clickOnNewCollaborationButton();
        StepLogger.verification('Collaborator Creator window should be displayed');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorCreatorWindow();

        StepLogger.stepId(4);
        StepLogger.step('Click on Add Collaborators button present beside * Collaborators: field');
        await KnowledgeCentralCollaborationHelper.clickOnAddCollaboratorButton();
        StepLogger.verification('Expert Finder Pane should be opened up');
        await KnowledgeCentralCollaborationHelper.verifyExpertFinderPaneDisplayed();

        StepLogger.stepId(5);
        StepLogger.step('Click on Find tab > Click on "Show All" button');
        await KnowledgeCentralCollaborationHelper.clickOnFindTab();
        await KnowledgeCentralCollaborationHelper.clickOnShowAllButton();
        StepLogger.verification('Click on Show All button should display list of collaborators available');
        await KnowledgeCentralCollaborationHelper.verifyCollaboratorsList();

        StepLogger.stepId(6);
        StepLogger.step('Check / select  any collaborator and verify');
        StepLogger.verification('User should view that selected collaborator is added under Selected Collaborators: section');
        await KnowledgeCentralCollaborationHelper.selectCollaboratorAndVerify();

        StepLogger.stepId(7);
        StepLogger.step('UnCheck /deselect  any collaborator and verify');
        StepLogger.verification('User should view that selected collaborator is removed from Selected Collaborators: section');
        await KnowledgeCentralCollaborationHelper.deSelectCollaboratorAndVerify();
    });
});
